### ISSUE TITLE
Win7x64, Desktop v1.3.0-RC1: Taskbar icon is shows blue dot for notification instead of red dot

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#194] opened 2016-07-08 02:54 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Taskbar icon shows blue dot for notification instead of red dot

#### Steps to reproduce

- Win7x64, Desktop v1.3.0-RC1, Server v3.1.0
- Observe taskbar icon with unread messages

#### Expected behavior

Unread indicator should be red to be consistent with web experience, iOS app and Android app

![image](https://cloud.githubusercontent.com/assets/177788/16676137/5105ca22-447c-11e6-994c-484160e36901.png)

Blue unread indicator doesn't meet the "obvious" requirement in ["fast, obvious, forgiving" design principle.](http://www.mattermost.org/design-principles/) 

#### Observed behavior

Unread icon is BLUE

![image](https://cloud.githubusercontent.com/assets/177788/16676137/5105ca22-447c-11e6-994c-484160e36901.png)

#### Possible fixes

To be consistent with official repository, revert unread indicator to red

**Comment by Razzeee** [comment] 2016-07-08 07:42
The pixxelated is a duplicate of another issue. 

The blue dot is correct as the tray icon does the same. So it was very unobvious before and is now very obvious. As blue means new messages and red are real mentions.

**Comment by it33** [comment] 2016-07-08 12:42
Thanks @Razzeee, 

Updated this ticket so it's just about the color change, since pixelation is tracked here: https://github.com/mattermost/desktop/issues/192

Regarding blue vs. red, in the desktop app, I can see your point about showing unread more clearly in a different state--for the tray icon, since mention numbers are too small to see, it does help to have unreads and mentions in different colors. 

That said, 

1. Even within the desktop app, the blue color for unreads in the tray icon is inconsistent with the black unread indicator in tabs in the main UI. Having two different ways of expressing the same thing is going to put some users at a disadvantage in using the app.
2. Blue and black unreads are inconsistent with the existing web, iOS and Android experiences.
3. The obvious principle include the guidance "Implementing for the obvious principle means understanding the concepts and frameworks with which users are already familiar, and aligning to those standards, so nothing in Mattermost looks unfamiliar."

I agree that switching back to a red indicator for unreads might not be the best solution. 

I think there's an issue with consistency, which is going to confuse some users. 

I think it's worth spending some time sharing ideas to see if we can come up with a solution that's better than any of us could have developed on our own. 

Thoughts?

**Comment by Razzeee** [comment] 2016-07-08 12:49
I agree that it's still not what we want and that reverting wouldn't help. Other than that, not really an idea. Do we even want users to know there are new messages which don't mention them? Like should we also remove that from the tray? I can't think of any other app that handles something similar.

**Comment by Razzeee** [comment] 2016-07-10 16:58
Just looked at slack again, they have a green dot in the tray icon and no indicator for new messages on the task bar itself. Probably the way to go.

**Comment by jasonblais** [comment] 2016-07-11 15:38
Thanks @Razzeee, after doing a little bit of research, here is a proposal: 

Taskbar/Dock icon:
```
    - no messages: no indicator
    - unread messages: setting to enable a red dot. Should be in upper-right corner for Mac, bottom-right corner for Windows
    - unread mentions/DMs: red dot with a number counter on how many unreads you have. Should be in upper-right corner for Mac, bottom-right corner for Windows
```

System tray icon (Windows only):
```
    - no messages: no indicator
    - unread messages: cyan dot
    - unread mentions/DMs: red dot
```

Numbers would of course be too small for the system tray icon, so using a different colour to indicate unread messages would make sense there. However, I feel it would be more consistent to keep the dot always red in the taskbar.

Feedback is welcome, @Razzeee and others in the community

**Comment by it33** [comment] 2016-07-11 21:39
Makes sense to me. I'd propose doing something simple, which is to change the CYAN unread indicator on the taskbar icon to RED for v1.3.1, and then add a setting later to have it not show.

In my mind, it's easier to add a feature to disable something later than to add one.

**Comment by Razzeee** [comment] 2016-07-12 07:53
But we agree that it should be disabled by default? In that case let's just remove the code path. Nothing will break due to that removal. And when you want to bring the feature back, just look at the git history.

**Comment by jasonblais** [comment] 2016-07-12 12:12
Thanks @Razzeee, the red dot is on the other hand more consistent with our mobile apps, as well as with other apps we researched. I'm not sure a cyan/green would be more obvious for unread messages.

Agree with both of you:

 1. For v1.3, propose we change the CYAN icon in the taskbar back to RED which is what it used to be in v1.2
 2. In the future, we can add a setting to enable a red dot for unread messages in the taskbar icon, so users can turn it off if they'd like

Anyone open to help submitting a pull request for 1)?

**Comment by yuya-oc** [comment] 2016-07-12 14:29
For 1), it's enough by reverting #145. But simple reverting makes conflicts, so I will push later.

**Comment by Razzeee** [comment] 2016-07-12 14:32
Well haven't you researched Slack? They don't have a dot so we should just remove that part as long as we don't have a setting. Your proposal is slightly different.

**Comment by yuya-oc** [comment] 2016-07-12 14:44
Slack has the option for the dot of unread on OS X. But there is not on Windows.

![slack_notification](https://cloud.githubusercontent.com/assets/1412057/16771105/463bbb9e-488a-11e6-88c8-3c07c56c21cb.png)

**Comment by yuya-oc** [comment] 2016-07-12 15:02
Then, I feel it should be enabled by default. Messages are not always posted as mention. So if it was disabled by default, most of users can't notice new messages until switching back to the app.

**Comment by jasonblais** [comment] 2016-07-12 15:23
Thanks @Razzeee, as @yuya-oc noted above, Slack does in fact offer the option.

It might also be easier to add a setting to disable it in the future, rather than removing the functionality now to which users may have already accustomed to. So we will revert back to the 'red' dot for v1.3.

Again, open for further feedback as community input is very valuable in shaping the future of the Desktop App

**Closed** 2016-07-12 16:47 UTC
Labels: windows

**Comment by Razzeee** [comment] 2016-07-12 18:36
Well I can only speak for what I've seen so far at work and my colleagues seem to be confused by the red indicator on unread messages. That's why I prepared the color changing pr.

**Comment by TheDarocker** [comment] 2016-08-23 16:55
@jasonblais But on mobile, unread messages that don't contain mentions do not receive a red blip. They receive nothing, which is how it should be on desktop- or blue, which would make it consistent with the tray icon.
