### ISSUE TITLE
clicking on a file:// protocol path does not open windows explorer since version 3.5.0

### ISSUE THREAD

**Issue by maximd** [mattermost/desktop#579] opened 2017-08-29 15:43 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

clicking on a `file://` protocol path does not open windows explorer

**Steps to reproduce**

- os: windows 7
- mattermost desktop app version: 3.7.0
- mattermost server version: 3.6.0

steps to reproduce:
- type a new message containing:
```
file:c:\
```

(note that mattermost will autoconvert this to `file:///C:/`)
**Expected behavior**

the windows explorer opens when clicking on the path/file

**Observed behavior**

nothing happens

**Possible fixes**

none

**Comment by jasonblais** [comment] 2017-08-29 18:04
Thanks @maximd for the report!

Can you try if the expected behaviour
 - works in Chrome (or other browser)
 - works in another desktop app that you use?

**Comment by maximd** [comment] 2017-08-30 15:01
No, the expected behaviour does not work in chrome either.

Though this behaviour (clicking on a `file://` link opens windows explorer) works in [mattermost desktop 3.4.1](https://github.com/mattermost/desktop/releases/tag/v3.4.1). In fact, in version 3.4.1, a dialog box would appear the first time a `file://` link is clicked:

![image](https://user-images.githubusercontent.com/108709/29878823-cc8e1764-8da3-11e7-8a53-cb17c4f67ca8.png)

The expected behaviour stopped working in [mattermost desktop 3.5.0](https://github.com/mattermost/desktop/releases/tag/v3.5.0)

**Comment by jasonblais** [comment] 2017-08-30 15:40
Oh interesting, didn't realize it used to work.

@yuya-oc Would it be related to this PR? https://github.com/mattermost/desktop/pull/359

**Comment by yuya-oc** [comment] 2017-08-30 15:54
Not related.

I feel that Chrome's rule to handle `file://` was changed. Now Electron and Chrome show an error message `Not allowed to load local resource: file:///C:/` in the devtools console. And Electron doesn't emit the necessary event to open the dialog in our code.

electron/electron#9393 looks a similar issue of Electron. As far as I read it, changing `file:` protocol behavior seems hard in Electron and our end. And [`protocol.interceptFileProtocol('file', handler)`](https://electron.atom.io/docs/api/protocol/#protocolinterceptfileprotocolscheme-handler-completion) doesn't perform for me.

**Comment by lip-d** [comment] 2018-02-11 03:31
**Possible solution**
Using Electron's method "shell.openItem" when the error occurs.

This is not a smart way, but it works for me and may be a possible fix. What do you think?

**Sample code**
src/browser/components/MattermostView.jsx
added line 161-186
```javascript
    webview.addEventListener('console-message', (e) => {
      const message = `[${this.props.name}] ${e.message}`;
      switch (e.level) {
      case 0:
        console.log(message);
        break;
      case 1:
        console.warn(message);
        break;
      case 2:
        console.error(message);

        // Chrome's console message
        var regex = /Not allowed to load local resource:\s*file:\/+(.+)/;
        var match = regex.exec(e.message);
        if (match != null) {
          if (match.length == 2) {
            // For Windows, change path separator
            var fpath = match[1].replace(/\//g, "\\").trim();

            // For multibyte characters. (e.g. Japanese)
            fpath = decodeURI(fpath);

            // For local drive. (e.g. C:\Windows)
            if (fpath.search(/^[A-Z]:/i) == 0) {
              // Better not to open it for security reasons
            } 
            // For network drive. (e.g. \\COMPUTER\SharedFolder)
            else {
              fpath = "\\\\" + fpath;

              if (shell.openItem(fpath) != true) {
                console.log("Failed to open: " + fpath);
              }
            }
          }
        }
        break;
      default:
        console.log(message);
        break;
      }
    });
```
- Mattermost desktop app 4.0.0
- Windows 7 and 10

**Comment by jasonblais** [comment] 2018-02-12 14:07
Nice! @yuya-oc thoughts? The Electron issue was closed as "won't fix".

**Comment by jasonblais** [comment] 2018-02-15 03:47
Actually, @lip-d , would you be open to submitting a pull request and we'll review? We'll test it out and merge if it looks good

**Comment by lip-d** [comment] 2018-02-15 09:11
Would you give me a few weeks? Then I'd like to try it.

**Comment by jasonblais** [comment] 2018-02-15 14:48
@lip-d Most certainly. Let us know if you have any questions then

**Comment by yuya-oc** [comment] 2018-02-26 12:41
#712 would solve the problem. On macOS and Linux, I think remote servers should be mounted as local directories. So I guess the feature was originally not working. So I add "Windows" label for this.

**Closed** 2018-02-26 12:42 UTC
Labels: Bug, Electron, Help Wanted, Windows

**Comment by maximd** [comment] 2018-02-27 00:34
Awesome, thanks everyone for your work!

**Comment by synotic** [comment] 2019-03-12 09:26
Hi to all,

I think the problem is happening again.
Can't open "file:///O:/<path>" via a channel header. There is no reaction, freeze or anything else.
Could anybody help me out?

Happening on Desktop Version 4.1.2

Best wishes
Timo

**Comment by biva** [comment] 2021-07-07 14:58
Hello, I see that this problem is still happening while it was working in the first versions of Mattermost. @jasonblais @amyblais Would you have any plan to solve it? It would be great :) (related PR and issues: https://github.com/mattermost/desktop/pull/712 and https://github.com/mattermost/mattermost-server/issues/12042)

**Comment by amyblais** [comment] 2021-07-07 17:23
@Willyfrog Is this related to https://mattermost.atlassian.net/browse/MM-24160?

**Comment by Willyfrog** [comment] 2021-07-09 08:48
no, seems that it is trying to load the file into the window, I'll create a separate ticket for this

**Comment by Willyfrog** [comment] 2021-07-09 08:50
[MM-36924](https://mattermost.atlassian.net/browse/MM-36924)

**Comment by biva** [comment] 2021-07-09 09:59
Great, thanks @Willyfrog :)

**Comment by benj1m4n** [comment] 2022-02-10 08:31
Hi @all Are there any news on this issue? The file:// protocol still doesn't seem to work.
