### ISSUE TITLE
On Windows, set focus to the message box when switching back to Mattermost Desktop app

### ISSUE THREAD

**Issue by MetalCar** [mattermost/desktop#155] opened 2016-05-27 08:35 UTC
When Mattermost isn't the active window, and i switch back, then the chatbox should be focused. Appears on Win7

**Comment by jasonblais** [comment] 2016-08-12 14:10
Thanks again for the report @MetalCar, 

Wanted to circle back here -- would you be able to let us know if the following behaviour happens for you?

1) In Mattermost desktop app v1.3, set focus to the message box
2) Switch to another app
3) Switch back to Mattermost

Observed: Focus is set to the message box

**Comment by Razzeee** [comment] 2016-08-12 18:12
Reproduces for me.

But I think @MetalCar want's it to always switch to the input box. Slack is interesting in that regard, they seem to do something like this in their platform code. As you can click and select previous posts and your caret will be gone from the input box. But as soon as you start typing it's catched by the inputbox. Feels pretty smooth. But probably a platform improvement.

**Comment by jasonblais** [comment] 2016-08-21 04:30
Thanks for confirming @Razzeee! 

If the user has a modal open (say a channel switcher or account settings), switches to another app, then back to Mattermost, moving focus to the input box may not be desired. So I'm not sure we want to implement the proposal at this time.

> As you can click and select previous posts and your caret will be gone from the input box. But as soon as you start typing it's catched by the inputbox. Feels pretty smooth. But probably a platform improvement.

That's a good suggestion, but would indeed be a platform improvement. @MetalCar and @Razzeee , if that's something you'd like to see, I encourage you to submit a feature request in our [Feature Idea forum post](https://mattermost.uservoice.com/forums/306457-general), where it can be discussed, upvoted and considered by the platform team.

Closing this particular issue for now, given the reason above.

**Closed by jasonblais** 2016-08-21 04:30 UTC
Labels: more information needed, windows

**Comment by Razzeee** [comment] 2016-08-21 08:05
This might already be asked for https://mattermost.uservoice.com/forums/306457-general/suggestions/13248267-auto-focus-cursor-to-input-box-on-typing-or-window
