### ISSUE TITLE
[Bug]: Windows app sizing issues

### ISSUE THREAD

**Issue by tjdownes** [mattermost/desktop#2638] opened 2023-03-26 23:36 UTC
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.2.2

### Operating System

Windows 11 Pro Version 10.0.22621 Build 22621

### Mattermost Server Version

7.9.1

### Steps to reproduce

- Open Mattermost Desktop. 
- Try to resize diagonally
- Try to resize from the left
- Try to resize from the top

### Expected behavior

Should be able to be resized from any of the resize indications on the cursor, with behavior expected to be the same as any desktop app on Windows.

### Observed behavior

- Resize the window in a diagonal direction. Window cannot be resized this way
- Can always be resized diagonally when you use Ctrl+R to refresh Mattermost, and only while Mattermost is refreshing (be quick!)
- Can sometimes be resized from the right and bottom, but not always. Window position seems to matter.
- Can sometimes be resized from the top, but the behavior is weird
- Cannot be resized from the left

See attached video

### Log Output

```shell
There is no Help >> Show Logs in my desktop app
```

### Additional Information

https://user-images.githubusercontent.com/273720/227811982-ae6ebad4-e387-4065-9edf-5aff0788bce5.mp4

**Comment by tjdownes** [comment] 2023-03-26 23:38
I forgot to mention: This is related to the following Github/JIRA issues:

- https://mattermost.atlassian.net/browse/MM-48574
- #2344

**Comment by devinbinnie** [comment] 2023-03-27 13:36
@tjdownes Can you try and see if it works on the latest RC for v5.3? https://github.com/mattermost/desktop/releases/tag/v5.3.0-rc.6

I personally can't reproduce it on the latest one myself.

**Comment by tjdownes** [comment] 2023-03-27 19:44
> Can you try and see if it works on the latest RC for v5.3?

@devinbinnie the behavior is the same in 5.3. To be clear, this behavior has existed for quite some time for me. I'm pretty sure since 5.0

**Comment by kelderek** [comment] 2023-03-30 20:36
I was able replicate this and at least find a workaround, if not a fix.  My guess is a fix would have to come upstream from electron.  Here's how I was able to work around this:
Go to Windows settings > System > About > Advanced System Settings
Hit the Settings button in the Performance section
Make sure the "Show window contents while dragging" box is checked

![image](https://user-images.githubusercontent.com/6126101/228957740-ddd4c21c-4263-4cd6-b16d-cf2a71171aea.png)

If I uncheck that box, it replicates the behavior in your video.  Checking the box again fixes it.  

If you are running it on a remote machine connected via remote desktop, there is a "Show window contents while dragging" option under the Experience tab of the remote desktop connection software.  Other remote desktop clients probably have a similar option in their settings to enable it, too.

**Comment by tjdownes** [comment] 2023-04-04 22:00
> I was able replicate this and at least find a workaround, if not a fix

I tested @kelderek's fix. It seems to resolve the worst of the issues, albeit there are still some problems with certain cases. It's a workable solution, for now. Still a bug, and I'm not convinced entirely that it's Electron. I say this because it works perfectly when the app is reloading. In other words, when the UI code from MM is not at play, the window resizes correctly in all cases.

Thanks for the workaround, @kelderek !

**Comment by devinbinnie** [comment] 2023-05-02 19:08
@tjdownes I fixed an issue related to window snapping and sizing here: https://github.com/mattermost/desktop/pull/2686

Can you try the latest nightly and see if any of your issues are resolved now? https://community.mattermost.com/core/channels/desktop-builds

**Comment by sk-tjdownes** [comment] 2023-05-02 19:33
I am happy to report that this seems resolved in the nightly build `mattermost-desktop-5.4.0-nightly.20230502-x64.msi`! Super snappy, too. Well done, and thank you. Also, love the new installer. It's wicked fast!

**Comment by tjdownes** [comment] 2023-05-02 19:35
I am happy to report that this seems resolved in the nightly build `mattermost-desktop-5.4.0-nightly.20230502-x64.msi`! Super snappy, too. Well done, and thank you. Also, love the new installer. It's wicked fast!

**Comment by devinbinnie** [comment] 2023-05-02 19:36
No problem, happy to have solved it :)
Closing.

**Closed by devinbinnie** 2023-05-02 19:36 UTC
Labels: Type/Bug, Awaiting Submitter Action
