### ISSUE TITLE
Desktop application top bar menu, minimize, maximize or close icons do not respond/work on 4.7.0. on Windows 10.

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/desktop#1645] opened 2021-07-04 07:36 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Desktop application top bar menu, minimize, maximize or close icons do not respond/work on 4.7.0. on Windows 10.

**Environment**
- Operating System: Windows 10 Pro 21H1
- Mattermost Desktop App version: 4.7.0
- Mattermost Server version: 5.31.1 

**Steps to reproduce**
Install/update the latest desktop client for Windows which is 4.7.0 and try to access the file menu (three dots left upper corner or try to minimize, maximize or close the app on top right icons.

**Expected behavior**
File menu and minimize, maximize or close icons should work as normal.

**Observed behavior**
Nothing works and there is not even shortcut keys to access to the file menu (!).

**Possible fixes**
I have no idea.

**Comment by kaksikanaa** [comment] 2021-07-04 07:37
Tested with two different machines and the behaviour is the same.

**Comment by kaksikanaa** [comment] 2021-07-04 08:07
https://user-images.githubusercontent.com/15322015/124378040-091e3580-dcb8-11eb-9bb2-057a41bcb8fb.mp4

**Comment by kaksikanaa** [comment] 2021-07-04 08:09
My first idea was to check if the GPU acceleration setting was enable by default and this might be the reason but cannot do that because the file menu is unaccessable.

**Comment by jprusch** [comment] 2021-07-05 05:59
Not an issue with my environment:
![image](https://user-images.githubusercontent.com/9337414/124424030-94ee9b00-dd66-11eb-8bc2-19f33ae409ce.png)

Server 5.37.0 Community-Daily / 5.36.1 Company

Desktop 4.7.0

Windows 10 Build 19093

**Comment by ffaur** [comment] 2021-07-07 09:59
Hello
I'm experiencing exactly the same issue as @kaksikanaa 

Windows 10 Pro version 20H2 (19042.1081)

**Comment by clicksrv** [comment] 2021-07-07 14:35
I'm also experience the exact same issue. The notifications are also not showing on the icon for me, neither does the taskbar flash or something on receiving a new message. Used to work fine in 4.6.2.

**Comment by aagha** [comment] 2021-07-08 23:01
Having the same issue.

Mattermost Version: 5.35.1
Database Schema Version: 5.35.0
Database: postgres

Windows 10 Pro
Version	10.0.19043 Build 19043

**Comment by gitjp** [comment] 2021-07-09 03:12
I'm also having the same issue.

Mattermost Version: 5.34.2
Database Schema Version: 5.34.0
Database: mysql

Desktop 4.7.0

Windows 10 Enterprise
Version: 10.0.19042 Build 19042

**Comment by Willyfrog** [comment] 2021-07-09 08:58
> My first idea was to check if the GPU acceleration setting was enable by default and this might be the reason but cannot do that because the file menu is unaccessable.

you can go to the config file to change it (it should be in `c:\Users\<user>\AppData\Roaming\Mattermost\`)

I'll try to investigate, but so far I haven't been able to reproduce the problem.

**Comment by Willyfrog** [comment] 2021-07-09 16:30
[Ticket created](https://mattermost.atlassian.net/browse/MM-36938). Feel free to add any details to it

**Comment by ggutter79** [comment] 2021-07-12 10:22
@kaksikanaa I had the same issue and it looks like your idea was right, i changed the GPU acceleration setting in %appdata%\Mattermost\config.json from false to true - now the menu works again. seems like a workaround for now.
Thanx @Willyfrog for the tip where to find the setting.

**Comment by gitjp** [comment] 2021-07-12 15:02
> @kaksikanaa I had the same issue and it looks like your idea was right, i changed the GPU acceleration setting in %appdata%\Mattermost\config.json from false to true - now the menu works again. seems like a workaround for now.
> Thanx @Willyfrog for the tip where to find the setting.

This same fix worked for me too. Thank you!

**Comment by Willyfrog** [comment] 2021-07-12 16:04
yes, seems that some of the config is taking longer to read in windows, so it is breaking with disabling GPU acceleration as this needs to be done before the app initializes

**Comment by kaksikanaa** [comment] 2021-07-18 06:26
Willyfrog  thanks for the investigaton & workaround & pull request.

**Comment by amyblais** [comment] 2021-08-03 23:13
This is fixed in v4.7.1 dot release,

**Closed by amyblais** 2021-08-03 23:13 UTC
