### ISSUE TITLE
Problem with notifications on mac client Desktop

### ISSUE THREAD

**Issue by teger** [mattermost/desktop#1994] opened 2022-02-04 10:44 UTC
Hi,

I upgraded my mattermost server on 6.3.1 LTS version and my client mac to 5.02.
I have a problem with notifications and user's status.

Mattermost Desktop pass in offline when i change apps. And i have no notifications for Mattermost !!!!
And i click on Mattermost desktop app, the notifcations appears !!
It's a big problem beacause i don't see the urgent message 

I test the mattermost desktop mac version 5.03-rc4 and the problem is already here !
I change the config on the server to increase the time before offline, and pass to 300 secondes at 10800 secondes.
But nothing, the problem is already here !!

Thanks for your help

**Comment by devinbinnie** [comment] 2022-02-04 14:06
@teger I'm not sure I fully understand the issue. Are you saying you don't get notifications on the Desktop App? Do you get them when using the browser?

**Comment by teger** [comment] 2022-02-04 14:46
Mattermost pass offline very fast and after, i don't have the notifications !
When i click on the app, the status come back online and the notifications appers ont the dock icon !

Impossible to control the status offline !

Thanks

**Comment by mileagainst** [comment] 2022-02-11 07:20
Same issue here, since the server upgrade clients are going offline randomly. Predominantly Windows Clients, i updated to latest 5.0.4 Version but the problem persists.

**Comment by devinbinnie** [comment] 2022-02-14 15:26
@teger @mileagainst Does the issue reproduce in the web browser as well?

**Comment by teger** [comment] 2022-02-21 15:11
Hi,

yes in the browser, all is OK !
The problem is only on the desktop app (in my case, on mac !)

Thanks

**Comment by devinbinnie** [comment] 2022-02-22 17:24
Thanks @teger, created a ticket to investigate: https://mattermost.atlassian.net/browse/MM-42016

**Comment by devinbinnie** [comment] 2022-03-15 16:07
@teger I'm having trouble reproducing your issue. Can you step me through what you're seeing, possibly with some screenshots or a video? Thanks!

**Comment by agenceKanvas** [comment] 2022-10-10 08:52
We have a team of 20 having the same issue.
The problem is as they say, the offline status is set automatically randomly. 
We have to reload the app and set the status as active to get it. 
Can't really give you any screenshot except the status icon but it won't give you any information.
We are all on mac and the version is the self hosted (managed by our hosting provider)

**Comment by mmjurov** [comment] 2022-12-27 20:07
Facing same problem almost every day for a long time (2 years or so) with teammates (20+ persons). Not very critical for us, but annoying sometimes.
Now on Mattermost Desktop 5.22, Mac OS Ventura 13.1
Same behavior on other platforms (tested Ubuntu, Kubuntu, Debian, Windows, OSX) via desktop app. Not using Mattermost via browser, so don't know how it works there.
Server is Omnibus Gitlab selfhosted, deployed via docker image. Gitlab version 15.7. 
Push server - default https://push-test.mattermost.com.
Desktop notification settings on desktop app - default "For mentions and direct messages" with Sound.

Today reached this problem during conversation with one teammate. Sent him some messages when he were in status "Away" (autoassigned due to app inactivity, probably). He saw my messages only after 2 hrs when unfolded his app from the "tray".

I face this problem in the same way every time. Open app from background and see there new messages im not notified with. On other platforms (windows and linux) at this moment notifications appears with standard way for OS (popup messages blinks). 

Which additional information can I provide to help you with problem resolution?

**Comment by devinbinnie** [comment] 2023-01-03 15:47
@mmjurov Are you also seeing the set to Offline bug? I'm wondering if that's the root cause here.

**Comment by mkddostro** [comment] 2023-05-10 17:49
I'm encountering being set to offline every once in a while.
I don't know what kind of info you need to look into it but I can try giving it to you when I know what to log, record, look for.

**Comment by mkddostro** [comment] 2023-05-31 12:46
Nobody able to tell me what info is needed? Looks like this may only be fixed by a new major version by accident without anyone knowing what happened.

**Comment by devinbinnie** [comment] 2024-09-27 16:46
Closing as stale/might already be fixed.

**Closed by devinbinnie** 2024-09-27 16:46 UTC
Labels: Type/Bug, More Information Needed, MacOS
