### ISSUE TITLE
Hour displayed incorrectly because of daylight saving time in Brazil.

### ISSUE THREAD

**Issue by nickolasdeluca** [mattermost/desktop#1102] opened 2019-11-07 13:01 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Message timestamps are displayed one hour forward because of daylight saving time that wasn't enforced in Brazil this year.

**Environment**
- Operating System: Windows 10 Pro [64 bit] [build 1903]
- Mattermost Desktop App version: 4.3.1
- Mattermost Server version: 5.16.0

**Steps to reproduce**
Just send a normal message, sent one at 09:55 AM, it was displayed as 10:55 AM

**Expected behavior**
It should be displayed 09:55

**Observed behavior**
This issue happens only on the Desktop App Version, same message displayed on the browser version displays the correct time stamp

**Possible fixes**
This was fixed in version 4.3.0, but suddenly started happening again.

**Comment by amyblais** [comment] 2019-11-12 16:01
This was an issue in Electron and seems that the issue is back https://github.com/electron/electron/issues/20998.

**Comment by nickolasdeluca** [comment] 2019-11-13 19:06
Apparently this is not a mattermost only issue, also noticed the same issue with Whatsapp's desktop client.

**Comment by amyblais** [comment] 2019-12-11 00:52
A bug ticket for this is here: https://mattermost.atlassian.net/browse/MM-21161.

**Comment by amyblais** [comment] 2021-09-08 18:42
Closing, this has been addressed,

**Closed by amyblais** 2021-09-08 18:42 UTC
