### ISSUE TITLE
Mattermost crashes with Segmentation Fault

### ISSUE THREAD

**Issue by InsOpDe** [mattermost/desktop#1235] opened 2020-03-12 11:31 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost crashes after a while

**Environment**
- Operating System: Ubuntu Focal Fossa (development branch)
```bash
uname -r 
5.4.0-14-generic
```
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.1.7.1

**Steps to reproduce**
Run Mattermost and wait

**Expected behavior**
Mattermost should not crash

**Observed behavior**
Mattermost crashes

```bash
/opt/Mattermost/mattermost-desktop
Current working directory is /home/marcel, changing into /opt/Mattermost
config.autostart has been configured: true
[1]    41221 segmentation fault (core dumped)  /opt/Mattermost/mattermost-desktop
```

**Comment by amyblais** [comment] 2020-03-12 12:03
@InsOpDe Do you see the same issue on a more recent Mattermost server version? Our most recent version is v5.20.1.

**Comment by wiggin77** [comment] 2020-03-12 12:25
I believe I am seeing the same thing.  

Desktop app (4.4.0) is seg faulting for me every few hours on Community.  Linux Mint 19 (Cinnamon).  

Syslog: 
```
Mar 11 12:29:52 mintdesk kernel: [105462.949177] mattermost-desk[20864]: segfault at 359591c5c000 ip 00007f440e519621 sp 00007ffeff853ab0 error 4 in libappindicator3.so.1.0.0[7f440e512000+c000]
```
It appears to be a problem with desktop notifications adding to the panel.

**Comment by Willyfrog** [comment] 2020-03-13 16:13
[ticket created](https://mattermost.atlassian.net/browse/MM-23228)

**Comment by gigawhitlocks** [comment] 2020-03-18 17:43
I hit this bug semi-regularly as well. Happy to share a core dump if necessary.

**Comment by gigawhitlocks** [comment] 2020-03-19 19:44
Anybody who is seeing this issue ( @wiggin77 ), could you share the version of libappindicator3 installed on your machine?

e.g. on mine it's:
```
rpm -qi libappindicator-gtk3
Name        : libappindicator-gtk3
Version     : 12.10.0
Release     : 25.fc31
Architecture: x86_64
Install Date: Tue 26 Nov 2019 03:38:21 PM CST
Group       : Unspecified
Size        : 108368
License     : LGPLv2 and LGPLv3
Signature   : RSA/SHA256, Fri 26 Jul 2019 01:50:38 AM CDT, Key ID 50cb390b3c3359c4
Source RPM  : libappindicator-12.10.0-25.fc31.src.rpm
Build Date  : Thu 25 Jul 2019 03:06:23 PM CDT
Build Host  : buildvm-21.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://launchpad.net/libappindicator
Bug URL     : https://bugz.fedoraproject.org/libappindicator
Summary     : Application indicators library - GTK 3
Description :
A library to allow applications to export a menu into the Unity Menu bar. Based
on KSNI it also works in KDE and will fallback to generic Systray support if
none of those are available.

This package contains the GTK 3 version of this library.
```

Take careful notice that I need the GTK 3 version of this library. Fedora packages libappindicator and libappindicator3 as separate packages so be careful not to get confused.

**Comment by wiggin77** [comment] 2020-03-19 20:00
According to the crash report I sent you, desktop is using `/usr/lib/x86_64-linux-gnu/libappindicator3.so.1.0.0`.  

Finding the package that provided that lib:
```
dpkg -S /usr/lib/x86_64-linux-gnu/libappindicator3.so.1.0.0
libappindicator3-1: /usr/lib/x86_64-linux-gnu/libappindicator3.so.1.0.0
```
Getting version info for that package:
```
$ apt-cache show libappindicator3-1
Package: libappindicator3-1
Architecture: amd64
Version: 12.10.1+18.04.20180322.1-0ubuntu1
Priority: optional
Section: libs
Source: libappindicator
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 76
Pre-Depends: multiarch-support
Depends: libc6 (>= 2.4), libdbusmenu-glib4 (>= 0.4.2), libdbusmenu-gtk3-4 (>= 0.4.2), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.0.0), libindicator3-7 (>= 0.4.90)
Suggests: indicator-application (>= 0.2.93)
Filename: pool/main/liba/libappindicator/libappindicator3-1_12.10.1+18.04.20180322.1-0ubuntu1_amd64.deb
Size: 19396
MD5sum: 28cb77afa429c82ee70262c7ced3e4fa
SHA1: 6a88747a448e46d9b6941288cf26b051afcbb422
SHA256: ff94b4a6f9da430280178dc2f02161fbb04db9b99c10e69f377091ed46cb2118
Homepage: https://launchpad.net/libappindicator
Description-en: Application Indicators
 A library and indicator to take menus from applications and place them in
 the panel.
```

**Comment by gigawhitlocks** [comment] 2020-03-19 20:02
OK thank you @wiggin77 and sorry for overlooking it in the dump

**Comment by InsOpDe** [comment] 2020-03-19 21:21
```bash
Package: libappindicator3-1
Architecture: amd64
Version: 12.10.1+18.04.20180322.1-0ubuntu5
Priority: optional
Section: libs
Source: libappindicator
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 93
Depends: libc6 (>= 2.4), libdbusmenu-glib4 (>= 0.4.2), libdbusmenu-gtk3-4 (>= 0.4.2), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.0.0)
Suggests: indicator-application (>= 0.2.93)
Filename: pool/main/liba/libappindicator/libappindicator3-1_12.10.1+18.04.20180322.1-0ubuntu5_amd64.deb
Size: 22920
MD5sum: 164e1ebed14f065c57012e9fb176cb09
SHA1: 2323c936e2ddedf4485f012f15aa0476f091925e
SHA256: ca0175ab04839fc1437b7180ac871413fc18b41ec65a8cf750ce493a3cc65513
Homepage: https://launchpad.net/libappindicator
Description-en: Application Indicators
 A library and indicator to take menus from applications and place them in
 the panel.
 .
 This package contains shared libraries to be used by applications.
Description-md5: 19c351a0f9348d05d8bfa4468c6db3f5
Task: ubuntu-desktop-minimal, ubuntu-desktop, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, xubuntu-core, xubuntu-desktop, lubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop
Supported: 9m
```

**Comment by gigawhitlocks** [comment] 2020-03-19 23:55
I believe this is the root cause of the bug https://bugs.launchpad.net/archlinux/+source/libappindicator/+bug/1867996

**Comment by gigawhitlocks** [comment] 2020-03-20 18:26
Current patch version isn't fixing it for me but I _think_ disabling the system tray icon in the Desktop settings works as a workaround.

More info here as well: https://bugs.archlinux.org/task/65885

**Comment by Willyfrog** [comment] 2020-03-21 15:38
@amyblais @deanwhillier should we add this as a known problem + workaround, the library seems to be maintained infrecuently, so I'm not sure how long will it take until they fix it.

**Comment by amyblais** [comment] 2020-03-23 13:40
Sure, I opened a doc PR here: https://github.com/mattermost/docs/pull/3471.

**Comment by wiggin77** [comment] 2020-03-23 15:07
Not all Electron apps that have a tray icon are crashing.  I suspect there may be a fix that doesn't require a patch to libappindicator.  For example, Wavebox (Electron app that hosts web pages) has a tray icon and does notifications that change the tray icon.  They had a crash in libappindicator but apparently fixed it via updating the version of Chromium they we building with.  https://github.com/wavebox/waveboxapp/issues/902#issuecomment-457192358

Slack is also not crashing for me.

**Comment by Willyfrog** [comment] 2020-03-24 14:42
maybe we can use `lsof -p <pid>` to check if slack is using libappindicator? it's interesting to know there might be other way

**Comment by gigawhitlocks** [comment] 2020-04-17 16:54
>Slack is also not crashing for me.

Funny you mention this, I decided to fire up Slack just to compare.. on the same system where I see Mattermost segfaults with the notification tray enabled, both Slack and Mattermost fail to draw the notification tray icon at all. 

For what it's worth @Willyfrog and @wiggin77, I do see that (with the system tray enabled) both Mattermost and Slack are using the same underlying library. Not sure if Slack crashes or not for me -- I don't usually have it open.

```
$ locate libappindicator3 | grep -e '^/usr' | xargs lsof 2>/dev/null
COMMAND      PID USER  FD   TYPE DEVICE SIZE/OFF    NODE NAME
slack     350751  ian mem    REG  253,1    66288 3933258 /usr/lib64/libappindicator3.so.1.0.0
mattermos 352387  ian mem    REG  253,1    66288 3933258 /usr/lib64/libappindicator3.so.1.0.0
```

**Comment by wiggin77** [comment] 2020-04-17 17:00
Good info @gigawhitlocks .   This suggests we're possibly calling it in a different way than Slack, or their Electron build is different.  That could be good news as it may be possible to fix this in code.  Unfortunately it's going to require a deep dive into that code path.

**Comment by devinbinnie** [comment] 2021-12-09 20:40
Closing as this appears to have been an upstream issue.

https://mattermost.atlassian.net/browse/MM-23228?focusedCommentId=104391

**Closed by devinbinnie** 2021-12-09 20:40 UTC
