### ISSUE TITLE
[Bug]: Mattermost 5.10 version installer doesn't upgrade the 5.8.1 version

### ISSUE THREAD

**Issue by metaad** [mattermost/desktop#3220] opened 2024-11-25 06:37 UTC
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.8.1

### Operating System

Windows 10 and 11 x64

### Steps to reproduce

1. Install Mattermost 5.8.1 and execute Mattermost 5.10.1 installer.
2. It doesn't upgrade to the latest version.
3. 5.9 is an ESR but it gets upgrades by 5.10.1 version installer.
4. In release notes page, 5.10.1 wasn't mentioned as extended support release.

![Mattermost](https://github.com/user-attachments/assets/df05d2b9-33da-43c8-8329-ae7c9d7e94b7)

### Expected behavior

I am confused whether to use 5.10.1 to upgrade Mattermost 5.9 ESR version or not.
Also, could you please confirm if 5.10.1 version is ESR or not.
If not, then why it is not upgrading the 5.8 version.

### Observed behavior

Matterost 5.10.1 is not upgrading the 5.8 version.
But it does upgrades 5.9 ESR version

### Log Output

```shell
[2024-11-24 22:22:42.696] [error] Logger Log level set to: info
[2024-11-24 22:22:42.839] [warn]  [Config] Failed to load configuration file from the filesystem. Using defaults.
[2024-11-24 22:22:42.840] [info]  [Config] Migrating config items successfully.
[2024-11-24 22:22:42.877] [warn]  [App.Initialize] Current working directory is C:\Windows\system32, changing into C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop
[2024-11-24 22:22:43.147] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:22:43.155] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:22:43.360] [error] [MainWindow] Error: ENOENT: no such file or directory, open 'C:\Users\MVelsamy\AppData\Roaming\Mattermost\bounds-info.json'
    at Object.readFileSync (node:fs:448:20)
    at t.readFileSync (node:electron/js2c/node_init:2:10175)
    at P.getSavedWindowState (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:877643)
    at P.init (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:874257)
    at P.show (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:876397)
    at C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:215780
    at Vr (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:216521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-11-24 22:22:43.419] [info]  [ServerDropdownView] init
[2024-11-24 22:22:43.478] [warn]  [i18nManager] Failed to set new language en-US
[2024-11-24 22:22:43.478] [warn]  [i18nManager] Failed to set new language 
[2024-11-24 22:22:43.526] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:22:43.542] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2024-11-24 22:22:43.903] [info]  [ModalView] [welcomeScreen] preloading with C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\internalAPI.js
[2024-11-24 22:22:48.362] [info]  [UpdateManager] Checking for update
[2024-11-24 22:22:48.366] [info]  [UpdateManager] Generated new staging user ID: 772ae9a2-da55-5291-b456-c0188e6db0f1
[2024-11-24 22:22:49.475] [info]  [UpdateManager] Update for version 5.10.1 is not available (latest version: 5.10.1, downgrade is disallowed).
[2024-11-24 22:23:06.217] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:24:24.232] [error] Logger Log level set to: info
[2024-11-24 22:24:24.406] [warn]  [App.Initialize] Current working directory is C:\Windows\system32, changing into C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop
[2024-11-24 22:24:24.490] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:24:24.582] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:24:24.914] [info]  [ServerDropdownView] init
[2024-11-24 22:24:24.966] [warn]  [i18nManager] Failed to set new language en-US
[2024-11-24 22:24:24.967] [warn]  [i18nManager] Failed to set new language 
[2024-11-24 22:24:25.075] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2024-11-24 22:24:25.080] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:24:25.237] [info]  [ModalView] [welcomeScreen] preloading with C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\internalAPI.js
[2024-11-24 22:24:28.677] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:24:29.872] [info]  [UpdateManager] Checking for update
[2024-11-24 22:24:30.832] [info]  [UpdateManager] Found version 5.10.1 (url: 5.10.1/mattermost-desktop-setup-5.10.1-win.exe)
[2024-11-24 22:24:30.834] [info]  [UpdateManager] New version available: 5.10.1
[2024-11-24 22:24:52.678] [error] [App.App] "child-process-gone" The child process has crashed. Details:  {
  type: 'Utility',
  reason: 'killed',
  exitCode: 1,
  serviceName: 'network.mojom.NetworkService',
  name: 'Network Service'
}
[2024-11-24 22:24:56.080] [error] [App.App] "child-process-gone" The child process has crashed. Details:  { type: 'GPU', reason: 'killed', exitCode: 1, serviceName: 'GPU' }
[2024-11-24 22:24:58.769] [error] [WebContentsEventM...] Renderer process for a webcontent is no longer available: killed
[2024-11-24 22:25:07.068] [error] Logger Log level set to: info
[2024-11-24 22:25:07.252] [warn]  [App.Initialize] Current working directory is C:\Windows\system32, changing into C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop
[2024-11-24 22:25:07.327] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:25:07.454] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:25:07.662] [error] [MainWindow] Error: Provided bounds info are outside the bounds of your screen, using defaults instead.
    at P.getSavedWindowState (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:877912)
    at P.init (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:874257)
    at P.show (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:876397)
    at C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:215780
    at Vr (C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:216521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-11-24 22:25:07.728] [info]  [ServerDropdownView] init
[2024-11-24 22:25:07.766] [warn]  [i18nManager] Failed to set new language en-US
[2024-11-24 22:25:07.766] [warn]  [i18nManager] Failed to set new language 
[2024-11-24 22:25:07.830] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2024-11-24 22:25:07.862] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:25:08.020] [info]  [ModalView] [welcomeScreen] preloading with C:\Users\MVelsamy\AppData\Local\Programs\mattermost-desktop\resources\app.asar\internalAPI.js
[2024-11-24 22:25:12.663] [info]  [UpdateManager] Checking for update
[2024-11-24 22:25:13.594] [info]  [UpdateManager] Update for version 5.10.1 is not available (latest version: 5.10.1, downgrade is disallowed).
[2024-11-24 22:36:37.287] [error] Logger Log level set to: info
[2024-11-24 22:36:37.420] [warn]  [Config] app-update.yml does not exist, disabling auto-updates
[2024-11-24 22:36:37.649] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:36:37.828] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:36:38.032] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-11-24 22:36:38.147] [info]  [ServerDropdownView] init
[2024-11-24 22:36:38.207] [warn]  [i18nManager] Failed to set new language en-US
[2024-11-24 22:36:38.208] [warn]  [i18nManager] Failed to set new language 
[2024-11-24 22:36:38.248] [info]  [App.Config] config.autostart has been configured: true
[2024-11-24 22:36:38.273] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2024-11-24 22:36:38.829] [info]  [ModalView] [welcomeScreen] preloading with C:\Program Files\Mattermost\Desktop\resources\app.asar\internalAPI.js
```

**Comment by devinbinnie** [comment] 2024-11-25 14:17
Are you upgrading the MSI version? If so then yes there is a known issue that the new installer doesn't replace that due to a different in the identifier (we're working on that). The workaround would be to manually uninstall for now.

As for ESR, the ESR is v5.9, so v5.9.1 would be the one to download if you want to stay on the ESR. We don't support auto-updating with the ESR, with the assumption that the ESR is manually installed and maintained by your sysadmin if it is required to stay on the ESR. Otherwise, we recommend the latest v5.10.1 version.

Hope that clears up a bit.

**Comment by metaad** [comment] 2024-11-26 05:59
Thanks for the clarification on the bug with 5.10.
I tried to upgrade the ESR version from 5.9.0 to 5.9.1 using https://github.com/mattermost/desktop/releases/download/v5.9.1/mattermost-desktop-5.9.1-win-x64.msi .
But it also coexists.

![image](https://github.com/user-attachments/assets/95a57327-afa3-4351-9a9c-f44257bd2bb3)

**Comment by devinbinnie** [comment] 2024-11-27 15:51
@metaad I can't reproduce your above situation. Did you just run each installer in sequence? If not, can you step me through how you installed both packages?

**Comment by devinbinnie** [comment] 2024-12-06 18:32
Fixed by https://github.com/mattermost/desktop/pull/3237, the above issue is likely the problem with the two side by side v5.9 and v5.9.1 installers.

Closing.

**Closed by devinbinnie** 2024-12-06 18:32 UTC
Labels: Type/Bug, Windows
