### ISSUE TITLE
Mattermost-desktop makes the system freeze when Ubuntu Unity menu is opened

### ISSUE THREAD

**Issue by AlexanderMelnichuk** [mattermost/desktop#1711] opened 2021-08-29 02:14 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost-desktop makes the system freeze when Ubuntu Unity menu is opened

**Environment**
OS version: Ubuntu 18.04.5, 
also checked on Ubuntu 20.04.
Unity 7.5.0
Mattermost Desktop version: 4.7.1
Not sure about the mattermost server version.

**Steps to reproduce**
- Open Mattermost Desktop window, position it near screen's top left corner.
- Open Unity Dash menu

**Expected behavior**
The system operates normally, menu opens, Mattermost Desktop is responsive.

**Observed behavior**
The system freezes, Unity Dash menu is displayed semi-transparent, as if it started to appear and then got stuck. Mattermost Desktop becomes unresponsive along with Unity Dash. Htop shows high CPU usage by `mattermost-desktop --type=renderer`. The freeze can be released by clicking any window other than Mattermost Desktop and Unity bar.

Download screencast here: https://drive.google.com/file/d/1hmbgmxJpy7glvSqabufjIcwyD1qF6Dz4/view

**Possible fixes**
Renderer is suspect.

**Comment by Willyfrog** [comment] 2021-08-30 07:56
Hi there! Thanks for reporting!

Have you tried changing the setting for gpu acceleration and see if that helps?

**Comment by AlexanderMelnichuk** [comment] 2021-08-30 09:17
Hi! I tried it (with reloading the app, and even rebooting), but it didn't help.

**Comment by devinbinnie** [comment] 2021-08-31 15:36
I can reproduce this, ticket created: https://mattermost.atlassian.net/browse/MM-38270

**Comment by bladernr** [comment] 2023-03-30 14:15
Any chance this can get some love?  This affects me pretty badly, to the point where I have to kill and restart the MM desktop all multiple times per day.  Same problem, if the MM window is in focus, and I open the Unity Dash either on purpose or accidentally by my hand brushing over the Super key that triggers the Dash to open, the MM Desktop app completely freezes and the only resolution is to kill it and relaunch it.
In my case I've observed this on:

Ubuntu 22.04
Mattermost Desktop snap 5.2.2 (and ever prior version I've tried)
Unity 7.6.0+22.04.20220601.1-0ubuntu1

**Comment by devinbinnie** [comment] 2023-05-04 15:52
@bladernr Unfortunately I'm still not sure what causing this, as it seems to hard hang the application, which is usually an indication of an issue with Electron/Chromium.

Have you tried v5.3.1 or the latest nightly build? https://community.mattermost.com/core/channels/desktop-builds

**Comment by devinbinnie** [comment] 2023-05-19 21:11
Since there isn't really any solution to this one, and is likely an issue caused by Electron/Chromium, coupled with the fact that Unity is no longer used by the main distribution of Ubuntu, I'm going to close this one as Won't Fix.

I'm happy to have someone work on it still if there's interest, but this won't be looked at by our development team at this time. I apologize for any inconvenience this causes.

**Closed by devinbinnie** 2023-05-19 21:11 UTC
Labels: Type/Bug, Help Wanted, Linux, Up For Grabs, Difficulty/2:Medium
