### ISSUE TITLE
Gitlab Omnibus connection convoluted

### ISSUE THREAD

**Issue by robmoggach** [mattermost/desktop#141] opened 2016-05-18 00:33 UTC
Currently connecting to mattermost server that is packaged with gitlab is tricky. It's extremely easy to create multiple teams with similar names and it defaults to creating a new incremented team. The only solution was to drag the URL from a browser to Mattermost Desktop and proceed with the login. It's a confusing process for end users for sure.

**Comment by jasonblais** [comment] 2016-06-23 18:39
Thanks @robmoggach for the report,

Are you referring to the Settings page that you land after launching the Mattermost Desktop application?

![image](https://cloud.githubusercontent.com/assets/13119842/16315408/25f86f7e-3950-11e6-955c-7982766b7a0c.png)

**Comment by robmoggach** [comment] 2016-06-23 18:41
If any user goes to the mattermost URL you give them Eg. http://mattermost.server.lan they are able to enter the group name but this creates a new group with the same name -

**Comment by robmoggach** [comment] 2016-06-23 18:42
further to that - once the new group is created the only way I can figure out to manage the groups and delete unneeeded ones is to manually edit the DB

**Comment by jasonblais** [comment] 2016-06-27 00:55
Thanks @robmoggach, just to make sure I understand:

In the screenshot below, one 
 1) adds the URL http://example.com/team with name Example Team
 2) adds another URL http://example2.com/team2 with name Example Team

Now, there are two 'groups' with the same name, which is confusing. Furthermore, the only way to change this in the UI is to delete the existing group and create a new one. Does this cover your use case?

![image](https://cloud.githubusercontent.com/assets/13119842/16366058/aac3fd78-3bde-11e6-85dd-c7eb43b66f91.png)

If so, there is an [old issue, #3](https://github.com/mattermost/desktop/issues/3) to look into improving the settings UI. It has recently been on hold given the [Mattermost Server moved to unified accounts across multiple teams in v3.0](https://forum.mattermost.org/t/unifying-user-accounts-across-teams-for-mattermost-3-0/1126) and we wanted to wait until that work was completed.

If not, could I have your help providing a concrete example, so I can fully understand the issue,

**Comment by Razzeee** [comment] 2016-06-27 06:01
You might want to test this with the dev branch as that let's you edit the servers.

**Comment by robmoggach** [comment] 2016-06-27 06:38
I believe that's the issue  - as well as the ability of any user to create groups

**Comment by jasonblais** [comment] 2016-06-28 12:06
Thanks @robmoggach, @Razzeee, closing this issue as a duplicate of #3 , and the use case presented here will be taken into consideration

**Closed by jasonblais** 2016-06-28 12:06 UTC
Labels: more information needed
