### ISSUE TITLE
Intermittent crashes (Linux Desktop App, rpm) 

### ISSUE THREAD

**Issue by thorseye** [mattermost/desktop#1856] opened 2021-11-08 13:21 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

App crashes very intermittent. 

**Environment**
- Operating System: Red Hat Enterprise Linux 8.4
- Mattermost Desktop App version: 5.0.1
- Mattermost Server version: 5.36.0

**Steps to reproduce**

Download and install the RPM from https://releases.mattermost.com/desktop/5.0.1/mattermost-desktop-5.0.1-linux-x86_64.rpm

Unfortunately, I can't reproduce the crashes in a controlled manner. 

**Expected behavior**

No crash...

**Observed behavior**

Syslog output: 

```
13:43:36 <host> kernel: mattermost-desk[634840]: segfault at 283603bf8000 ip 00007efc29762af5 sp 00007ffc808cba90 error 4 in libappindicator3.so.1.0.0[7efc2975b000+c000]
Nov 08 13:43:36 <host> kernel: Code: ff 49 89 c5 48 8b 45 18 48 83 78 28 00 74 4d 48 8d 54 24 0c 48 8d 74 24 10 4c 89 ef 31 db e8 e2 c0 ff ff 66 90 48 8b 44 24 10 <48> 8b 3c d8 39 5c 24 0c 7f 09 48 85 ff 0f 85 48 01 00 00 48 8b 45
Nov 08 13:43:36 <host> systemd[1]: Started Process Core Dump (PID 642104/UID 0).
Nov 08 13:43:38 <host> systemd-coredump[642107]: Process 634840 (mattermost-desk) of user 62405 dumped core.
                                                            
                                                            Stack trace of thread 634840:
                                                            #0  0x00007efc29762af5 status_icon_changes (libappindicator3.so.1)
                                                            #1  0x00007efc4a7733bd g_closure_invoke (libgobject-2.0.so.0)
                                                            #2  0x00007efc4a786945 signal_emit_unlocked_R (libgobject-2.0.so.0)
                                                            #3  0x00007efc4a78fa56 g_signal_emit_valist (libgobject-2.0.so.0)
                                                            #4  0x00007efc4a790093 g_signal_emit (libgobject-2.0.so.0)
                                                            #5  0x00007efc29761b4e app_indicator_set_icon_full (libappindicator3.so.1)
                                                            #6  0x0000558ce13f8ddd n/a (mattermost-desktop)
                                                            #7  0x0000558ce133d700 n/a (mattermost-desktop)
                                                            #8  0x0000558ce12b3926 n/a (mattermost-desktop)
                                                            #9  0x0000558ce306f4ff n/a (mattermost-desktop)
                                                            #10 0x0000558ce3c660ca n/a (mattermost-desktop)
                                                            #11 0x0000558ce3c38531 n/a (mattermost-desktop)
                                                            #12 0x0000558ce3c4e86a n/a (mattermost-desktop)
                                                            #13 0x0000558ce3c4fb1f n/a (mattermost-desktop)
                                                            #14 0x0000558ce3c040ff n/a (mattermost-desktop)
                                                            #15 0x00007efc4a4977ed g_main_context_dispatch (libglib-2.0.so.0)
                                                            #16 0x00007efc4a497ba8 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                                                            #17 0x00007efc4a497c40 g_main_context_iteration (libglib-2.0.so.0)
                                                            #18 0x0000558ce3c03dcb n/a (mattermost-desktop)
                                                            #19 0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #20 0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #21 0x0000558ce2fa33d3 n/a (mattermost-desktop)
                                                            #22 0x0000558ce2fa4ff2 n/a (mattermost-desktop)
                                                            #23 0x0000558ce2fa09a2 n/a (mattermost-desktop)
                                                            #24 0x0000558ce20701de n/a (mattermost-desktop)
                                                            #25 0x0000558ce206fce4 n/a (mattermost-desktop)
                                                            #26 0x0000558ce206dcf5 n/a (mattermost-desktop)
                                                            #27 0x0000558ce206ddd2 n/a (mattermost-desktop)
                                                            #28 0x0000558ce128a49e n/a (mattermost-desktop)
                                                            #29 0x00007efc4542b493 __libc_start_main (libc.so.6)
                                                            #30 0x0000558ce0f48aaa _start (mattermost-desktop)
                                                            
                                                            Stack trace of thread 634852:
                                                            #0  0x00007efc4abcc4a2 waitpid (libpthread.so.0)
                                                            #1  0x0000558ce3c86a1b n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c84300 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634861:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce72ea792 n/a (mattermost-desktop)
                                                            #3  0x0000558ce72e8302 n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634853:
                                                            #0  0x00007efc455050f7 epoll_wait (libc.so.6)
                                                            #1  0x0000558ce3dcfb9b n/a (mattermost-desktop)
                                                            #2  0x0000558ce3dcd6d5 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3ca8032 n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c58dad n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634897:
                                                            #0  0x00007efc4abcb8e4 read (libpthread.so.0)
                                                            #1  0x0000558ce13dcb99 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634863:
                                                            #0  0x00007efc4abcabd6 do_futex_wait.constprop.1 (libpthread.so.0)
                                                            #1  0x00007efc4abcacc8 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
                                                            #2  0x0000558ce1284b70 uv_sem_wait (mattermost-desktop)
                                                            #3  0x0000558ce73505cd n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634854:
                                                            #0  0x00007efc4abc86e8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87d7d n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c883c1 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c629ce n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c6335d n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62f4d n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634916:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8817e n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c038fa n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634857:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8817e n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c038fa n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634906:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8817e n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c038fa n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634858:
                                                            #0  0x00007efc455050f7 epoll_wait (libc.so.6)
                                                            #1  0x0000558ce1287b3d n/a (mattermost-desktop)
                                                            #2  0x0000558ce1279641 uv_run (mattermost-desktop)
                                                            #3  0x0000558ce72ea5e1 n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634859:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce72ea792 n/a (mattermost-desktop)
                                                            #3  0x0000558ce72e8302 n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634901:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce4aac395 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634900:
                                                            #0  0x00007efc454fc29f __select (libc.so.6)
                                                            #1  0x0000558ce3c8c468 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634896:
                                                            #0  0x00007efc455050f7 epoll_wait (libc.so.6)
                                                            #1  0x0000558ce3dcfb9b n/a (mattermost-desktop)
                                                            #2  0x0000558ce3dcd6d5 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3ca7f94 n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #9  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #10 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634903:
                                                            #0  0x00007efc455050f7 epoll_wait (libc.so.6)
                                                            #1  0x0000558ce13e3f4c n/a (mattermost-desktop)
                                                            #2  0x0000558ce13b7247 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634893:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c629ce n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c6335d n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62f7d n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634904:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c629ce n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c6335d n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62fad n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634890:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce1275dd7 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634913:
                                                            #0  0x00007efc455050f7 epoll_wait (libc.so.6)
                                                            #1  0x0000558ce3dcfb9b n/a (mattermost-desktop)
                                                            #2  0x0000558ce3dcd6d5 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3ca8032 n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #9  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #10 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634889:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce1275dd7 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 635137:
                                                            #0  0x00007efc454d0d98 __nanosleep (libc.so.6)
                                                            #1  0x00007efc454fcb28 usleep (libc.so.6)
                                                            #2  0x00007efc2798627d _ZN11CSupervisor10RunPollingEv (libiidp11.so)
                                                            #3  0x00007efc279862f6 _Z10PollThreadPv (libiidp11.so)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634888:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce1275dd7 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634887:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce1275dd7 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 638392:
                                                            #0  0x00007efc4abc86e8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87d7d n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c883c1 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c629ce n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c6335d n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62f4d n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634860:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce1284d29 uv_cond_wait (mattermost-desktop)
                                                            #2  0x0000558ce72ea792 n/a (mattermost-desktop)
                                                            #3  0x0000558ce72e8302 n/a (mattermost-desktop)
                                                            #4  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #5  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 641594:
                                                            #0  0x00007efc4abc86e8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87d7d n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c883c1 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c629ce n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c6335d n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62f4d n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634895:
                                                            #0  0x00007efc454f9a41 __poll (libc.so.6)
                                                            #1  0x00007efc4a497b16 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                                                            #2  0x00007efc4a497ed2 g_main_loop_run (libglib-2.0.so.0)
                                                            #3  0x00007efc49f745da gdbus_shared_thread_func (libgio-2.0.so.0)
                                                            #4  0x00007efc4a4bfe5a g_thread_proxy (libglib-2.0.so.0)
                                                            #5  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #6  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634856:
                                                            #0  0x00007efc455050f7 epoll_wait (libc.so.6)
                                                            #1  0x0000558ce3dcfb9b n/a (mattermost-desktop)
                                                            #2  0x0000558ce3dcd6d5 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3ca8032 n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #7  0x0000558ce2fa5f0f n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634844:
                                                            #0  0x00007efc454f9a41 __poll (libc.so.6)
                                                            #1  0x0000558ce348099f n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #3  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #4  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 641241:
                                                            #0  0x00007efc4abc86e8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87d7d n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c883c1 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c62992 n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c6335d n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62f4d n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634902:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8817e n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c038fa n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634894:
                                                            #0  0x00007efc454f9a41 __poll (libc.so.6)
                                                            #1  0x00007efc4a497b16 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                                                            #2  0x00007efc4a497c40 g_main_context_iteration (libglib-2.0.so.0)
                                                            #3  0x00007efc4a497c91 glib_worker_main (libglib-2.0.so.0)
                                                            #4  0x00007efc4a4bfe5a g_thread_proxy (libglib-2.0.so.0)
                                                            #5  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #6  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 641595:
                                                            #0  0x00007efc4abc86e8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87d7d n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c883c1 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c629ce n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c630b9 n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c62f4d n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #7  0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #8  0x00007efc45504dc3 __clone (libc.so.6)
                                                            
                                                            Stack trace of thread 634909:
                                                            #0  0x00007efc4abc82fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                            #1  0x0000558ce3c87c33 n/a (mattermost-desktop)
                                                            #2  0x0000558ce3c884f4 n/a (mattermost-desktop)
                                                            #3  0x0000558ce3c8817e n/a (mattermost-desktop)
                                                            #4  0x0000558ce3c038fa n/a (mattermost-desktop)
                                                            #5  0x0000558ce3c4ffef n/a (mattermost-desktop)
                                                            #6  0x0000558ce3c21ef7 n/a (mattermost-desktop)
                                                            #7  0x0000558ce3c68bc8 n/a (mattermost-desktop)
                                                            #8  0x0000558ce3c68d57 n/a (mattermost-desktop)
                                                            #9  0x0000558ce3c8b753 n/a (mattermost-desktop)
                                                            #10 0x00007efc4abc214a start_thread (libpthread.so.0)
                                                            #11 0x00007efc45504dc3 __clone (libc.so.6)
Nov 08 13:43:38 <host> systemd[1]: systemd-coredump@4-642104-0.service: Succeeded.
```

**Possible fixes**

**Comment by iyampaul** [comment] 2021-11-08 15:57
I've also run into this `error 4 in libappindicator3.so.1.0.0` segfault on Fedora 34/Gnome 40 (and now F35/Gnome41) using the tar.gz package.  Difficult to consistently reproduce, however definitely occurs on/around client events that cause a desktop notification (channel message, etc).

```
[ 1826.947964] mattermost-desk[3807]: segfault at 154602e33000 ip 00007ff102e54c85 sp 00007ffd27fa19c0 error 4 in libappindicator3.so.1.0.0[7ff102e50000+6000]
```

**Comment by rcaspart** [comment] 2021-11-09 10:10
Can confirm, this also occurs for me on F35.
At least behavior wise it seems to be similar/the same as #1235

**Comment by slopyz** [comment] 2021-11-22 15:52
Hi, I still have the problem with these versions : 
- Mattermost desktop : 5.0.2
- Mattermost Server : 5.37.0
- Window Manager : X11
- OS : Fedora 34 / Gnome 40.4

**Comment by JasperSiero** [comment] 2022-03-17 13:43
We have the same problem with Mattermost desktop 5.0.4, Fedora 35 and Mattermost Server 6.3.4. Tested it with X11 and Wayland (both situations Mattermost sometimes crashes)

**Comment by crami** [comment] 2022-03-21 09:41
Same here, version 5.0.4 on Debian/sid installed from the official deb package.
Syslog:
Mar 21 10:36:05 orinoco kernel: [229411.376723] mattermost-desk[298249]: segfault at 34fc01c3f000 ip 00007f0867f38125 sp 00007ffd0084d3b0 error 4 in libappindicator3.so.1.0.0[7f0867f34000+5000]

**Comment by devinbinnie** [comment] 2022-03-22 13:25
Just curious, does this happen with any other application that uses notifications? I'm wondering if it's an issue with `libappindicator` or a specific version of it. Unfortunately the communication between Electron and `libappindicator` isn't within our control.

**Comment by volker-schukai** [comment] 2022-04-25 09:20
Same here: debian bullseye 
kernel: mattermost-desk[3974392]: segfault at 167c017f8000 ip 00007fddb3b90175 sp 00007ffc272f9f40 error 4 in libappindicator3.so.1.0.0[7fddb3b8c000+5000]
other electron apps do not seem to be affected.

**Comment by adam820** [comment] 2022-05-20 03:36
> other electron apps do not seem to be affected.

I'm actually receiving a similar stacktrace and frequent crashes with Discord on Fedora 36, so it appears to have some common thread.

```
#0  0x00007f29dbb00c95 status_icon_changes (libappindicator3.so.1 + 0x8c95)
#1  0x00007f2a0093eda0 g_closure_invoke (libgobject-2.0.so.0 + 0x13da0)
#2  0x00007f2a0096b4b6 signal_emit_unlocked_R.isra.0 (libgobject-2.0.so.0 + 0x404b6)
#3  0x00007f2a0095ba0e g_signal_emit_valist (libgobject-2.0.so.0 + 0x30a0e)
#4  0x00007f2a0095bc93 g_signal_emit (libgobject-2.0.so.0 + 0x30c93)
#5  0x00007f29dbaffbd7 app_indicator_set_icon_full (libappindicator3.so.1 + 0x7bd7)
#6  0x00005599d3b93ebd n/a (Discord + 0x1f5aebd)
#7  0x00005599d3ae3d10 n/a (Discord + 0x1eaad10)
#8  0x00005599d3a57576 n/a (Discord + 0x1e1e576)
#9  0x00005599d576a9ef n/a (Discord + 0x3b319ef)
#10 0x00005599d6329d90 n/a (Discord + 0x46f0d90)
```

**Comment by AKorezin** [comment] 2022-05-23 17:44
I'm not sure, but it seems crash is described in [upstream issue](https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1867996).
I assume you should ask distro maintainers to actually apply latest(`r298` at the moment) patches from source like in [arch](https://github.com/archlinux/svntogit-community/tree/255c98613e4389db0b4d8c8cfe97a5b021e87711/repos/community-x86_64).

@adam820 it seems [fc36](https://src.fedoraproject.org/rpms/libappindicator/blob/287b0993111d37e40051920b869af8f40a06e535/f/libappindicator.spec) has no patches, because it uses plain `12.10.0` + single patch `r285`.

@volker-schukai there's no `libappindicator3.so.1.0.0` in `bullseye`. Explanation [here](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages).
So the solution to the issue will depend on your DE.

**Comment by devinbinnie** [comment] 2023-05-05 13:52
Electron has moved away from relying on `libappindicator`, see here: https://github.com/electron/electron/pull/36333
So this ticket likely isn't super relevant anymore, closing.

**Closed by devinbinnie** 2023-05-05 13:52 UTC
Labels: Type/Bug, Linux
