### ISSUE TITLE
Client freezes in Windows 10 (when app is minimized)

### ISSUE THREAD

**Issue by mdementev** [mattermost/desktop#520] opened 2017-04-28 06:54 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Client freezes in Windows 10 on getting messages

**Steps to reproduce**

1. Minimize app
2. Wait for mesasges
3. Try to open app

**Expected behavior**
App should be opened and interactible

**Observed behavior**
Main window is opened, but doesn't correspond to any actions. Will work again after few minutes.
Console output is clear.

**Possible fixes**
Problem has been solved for my team, by disabling Windows notifications for Mattermost. So it could be related.

**Notes**
Added comment in closed ticket: https://github.com/mattermost/desktop/issues/347

**Comment by jasonblais** [comment] 2017-04-28 12:08
@mdementev Really appreciate the report,

When you say "minimized", do you mean 
 - minimized to the taskbar, or 
 - closed (which minimizes to the system tray / notifications area)

**Comment by jasonblais** [comment] 2017-04-28 12:08
Related to https://github.com/mattermost/desktop/issues/494

**Comment by mdementev** [comment] 2017-04-28 12:17
@jasonblais to taskbar

**Comment by yuya-oc** [comment] 2017-04-28 12:43
Thanks @mdementev

Actually the code is injected for desktop notifications in the application. So it's most significant difference from normal web browsers.

**Comment by jasonblais** [comment] 2017-08-18 15:32
Closed via #563

**Comment by Boababa** [comment] 2017-10-18 15:30
I'm running 3.7.1 on Win10, bug still happens in both 32 and 64 bit client versions. Is the fix in 3.7.1 or slated for 3.8.0?

**Comment by jasonblais** [comment] 2017-10-18 15:51
Hm, that's unfortunate to hear @Boababa. It was indeed included in the v3.7.1 release. Are the reproduction steps the same as in the issue description, and turning off desktop notifications no longer causes the app to freeze?

@mdementev Are you still experiencing the issue on v3.7.1 as well?

**Comment by Boababa** [comment] 2017-10-20 12:13
Confirmed. Turning notifications off fixes the freezing issue. Tried on both 32 and 64 bit clients, same effect. Also it's independent of minimization for me - freezes both when window is up and when minimized. Wish I had time to debug....

**Comment by jasonblais** [comment] 2017-10-20 15:06
That's quite unfortunate.

@Boababa I understand you're busy and don't have time to debug now -- wondering if you'd have time later? We haven't been able to reliably reproduce this bug so rely on the community to help with the investigation.

The fix we included in v3.7.1 had resolved it for at least one community member, but further work may be needed.

**Comment by soletan** [comment] 2017-11-06 17:26
Same here ... kept kicking Mattermost every 2-3 minutes in a running conversation due to Windows freezing on returning to chat. Switching to browser was helping out for the moment ...

First I thought it might be related to having enabled WebRTC beta feature, but I think I didn't realize before as we've started to use Mattermost most recently.

**Comment by jasonblais** [comment] 2017-11-06 22:16
@soletan Confirming that turning off desktop notifications helps resolve the issue for you?

**Comment by soletan** [comment] 2017-11-06 22:30
Yes, I confirm. And I might add another interesting fact: one of my colleagues is using Win10 Home. It is Win10 Pro in my case. He doesn't have any issues with desktop notifications while I was having using the same server.

**Comment by jasonblais** [comment] 2017-11-06 22:35
@soletan That's a very helpful data point. We actually just heard reports of slowness on Windows 10 Enterprise. So maybe it's only affecting some of the operating systems. It might also explain why I haven't experienced it given I have Windows 10 Home.

@mdementev @Boababa Would you mind letting us know which Windows 10 system do you use? (Home vs Pro vs Enterprise vs Education).

**Comment by Boababa** [comment] 2017-11-13 18:36
@jasonblais Oops missed this question earlier: I'm running Win 10 Pro, 10.0.14393.

**Comment by Boababa** [comment] 2017-11-13 18:41
@jasonblais I'll have time to debug between Dec 24th and Jan 1st. It's a long time away, but I am thoroughly slammed by paying work till then.

**Comment by jasonblais** [comment] 2017-11-13 19:17
Thanks @Boababa, completely understand. Appreciate for following up here.

@yuya-oc There seems to be a pattern where freezing occurs on Win10 Pro or Enterprise only. Three of the most recent reports have been from that platform. The freezing seems to have resolved on Win10 Home. I don't think v4.0-Beta1 have any changes that would help with this issue?

**Comment by yuya-oc** [comment] 2017-11-14 13:46
@jasonblais Yeah, v4.0 doesn't have any changes for notifications excepting Electron version. I feel it's a little weird that the problem is related to edition of Windows because I'm using Win10 Pro.

By the way, I'm worried about that too many notifications might cause something like object leaking. However I have not investigated in detail yet. To make sure, I'd like to know how many messages are received at a moment. I'm not sure actual situations because my team is very small.

**Comment by jasonblais** [comment] 2017-11-14 14:48
@soletan @mdementev @Boababa 

When/if you have a chance, would you like to help grab a screenshot from **System Console > Site Statistics** for
 1. total number of users/teams/channels/posts

![image](https://user-images.githubusercontent.com/13119842/32785934-b0fdfb28-c920-11e7-8a3f-7ad63d2dfe84.png)

 2. number of posts per day

![image](https://user-images.githubusercontent.com/13119842/32785997-d38f8382-c920-11e7-8b4e-0487c0da2378.png)

That would help us get an idea on the size of your deployment and help us further investigate the problem. If you don't have access to it, you might need your System Admin to help.

Of course, if you don't feel comfortable sharing that information, totally understand.

Many thanks in advance!

**Comment by soletan** [comment] 2017-11-14 15:18
It's pretty solid in our case:

![grafik](https://user-images.githubusercontent.com/48088/32787697-787d8ea8-c957-11e7-9821-72a3984cace5.png)

![grafik](https://user-images.githubusercontent.com/48088/32787702-7e8aa696-c957-11e7-8829-b3c2039ce2ee.png)

**Comment by g371** [comment] 2018-02-07 00:30
I can confirm that exact same bug is present in 3.7.1 on Windows 10 Home. Fresh install with Slack data import:

![image](https://user-images.githubusercontent.com/18262108/35891802-bbcf43ba-0bae-11e8-837c-b37a78699b18.png)

**Comment by soletan** [comment] 2018-02-07 08:52
FWIW: I've upgraded server to 4.6 and client to 4.0 recently. After re-enabling notifications in account settings I haven't had any freezes for some days now. My Win10 has been upgraded to latest Fall Creators Update, too.

**Comment by jasonblais** [comment] 2018-02-07 13:42
@Boababa @g371 Wondering if either of you can download the latest release of the desktop app (v4.0), re-enable desktop notifications, and let us know if the client still freezes?

Download page: https://about.mattermost.com/downloads

We've been doing a bunch of investigation, and have some potential resolutions, but haven't been able to reproduce it unfortunately.

**Comment by g371** [comment] 2018-02-07 22:14
@jasonblais Just tested the Windows desktop app v4.0, bug is gone, thanks. Server v4.6.1.

**Comment by jasonblais** [comment] 2018-02-07 22:52
That's great news! @yuya-oc any thoughts what might have fixed this between v3.7.1 and v4.0.0?

**Comment by yuya-oc** [comment] 2018-02-08 11:30
@jasonblais I can't think of other than upgrading of Electron.

**Comment by jasonblais** [comment] 2018-02-08 13:07
I'll close this issue then, and re-open if anyone else reports it's still an issue.

**Closed by jasonblais** 2018-02-08 13:07 UTC
Labels: More Information Needed, Windows

**Comment by JoshuaaMichael** [comment] 2018-09-27 23:52
Hello. I'm having this issue, I'm running Windows desktop client v4.2.1.

The whole program becomes unresponsive.

Super easy to reproduce. I minimize the desktop program to taskbar. I open up the app on my iPhone and send a message to myself. Open up the app from taskbar and it's totally unresponsive.

What else can I provide you? My %appdata%\Roaming\Mattermost\logs folder is empty...

**Comment by JoshuaaMichael** [comment] 2018-09-27 23:55
After writing this comment, a colleague messaged me and when I opened it out of habit, it worked and I was able to reply. I've tried minimizing again, and sending a test to myself again, not freezing. I've tried quitting the windows app, opening it, minimizing, sending myself a test message again, not freezing.

Can someone help me figure out how to get better logging so I'm able to give more detail to reporting this issue? I don't like having something so difficult to reproduce without better logs. Us finding this bug is stopping us rolling it out this week to our company, so I'm keen to get it resolved.

**Comment by jasonblais** [comment] 2018-09-28 01:29
@yuya-oc or @wget would you have ideas on how to retrieve better error logs on the desktop app?

@JoshuaaMichael 
1. Did this reproduce for other users on the team?
2. Which Windows version? (e.g. Windows 10)

**Comment by JoshuaaMichael** [comment] 2018-09-28 02:05
We haven't been able to roll it out to the team because I've found this issue, and reproducing it as I've said above isn't as reliable as I'd like, so I don't have any more computers to reproduce it on. There are only two members in our admin team, myself and another guy who uses a Mac. I'm keen on getting some methods to produce logs, so if I can get it to occur again on my computer I'll have something to show for it.

I'm Windows 10. My colleague is the latest Mac version.

**Comment by JoshuaaMichael** [comment] 2018-09-28 04:40
It was totally locked up at the time, I couldn't click on that file menu. I did test that.
Was there anywhere else that there would be any logging on the machine? Or can I enable some?

**Comment by wget** [comment] 2018-09-28 12:40
@jasonblais Thanks for having ping me.

According from the report made by @JoshuaaMichael, since he wasn't able to click on menu bar (made by electron), the issue is likely not due to Mattermost but rather to electron itself.

On Windows, I would recommend listening for the events using procmon: https://electronjs.org/docs/development/debug-instructions-windows#using-procmon-to-observe-a-process

This will maybe help us narrowing down the issue.

Also, since 4.2.1 have been released on May 24th. You have to keep in mind this current repository has made much changes and upgraded the electron layer to the latest available. I would recommend rebuilding a Windows build from master and test this out.

My Windows build environment is not available today, so I cannot test myself. Maybe tomorrow I'll get my network issues sorted out and will be able to help.

In the meantime, I remember we built a more recent version to test the new msi installer, maybe @JoshuaaMichael can test that version and report if he is encountering the issue again: https://github.com/mattermost/desktop/pull/841#issuecomment-412614510

**Comment by JoshuaaMichael** [comment] 2018-10-02 00:03
Found that msi installer at the #841, installed that now and I'll report back with how it goes.

I think the issue may be something related to leaving the client open for "a long time". I just left it open over the long weekend here, then when I got into work I sent myself a message from the MM iOS client, tried opening the Windows client, and it was frozen (title bar and everything). I'm not sure if it's just from being left open for a long time, or if the message is also required to kill it. Very schrodinger's.

Although I understand by using the msi we're seeing if we can avoid the problem entirely after the new Electron work, I think it's worth noting that since it takes "a long time" for these to be left open for the issue to occur, I'll have to keep an eye on it.

Is there anything I can do when the program is frozen to give you any more information?
Or any logging I can enable to give you something when it freezes?

**Comment by wget** [comment] 2018-10-02 07:31
@JoshuaaMichael thanks for the feedback.

My Windows build machine is available again. I'll check these assumptions and leave the Mattermost client open for a few days to see if we can reproduce the issue.

Like I said, if you are willing to help narrowing down the issue playing with procmon (from the link) above could help.

**Comment by JoshuaaMichael** [comment] 2018-10-08 22:48
Hey @wget. I've been off work for a week between sickness and studying. So I've just come back to my computer, and the Mattermost client is completely frozen again, with the menu bar at the top also frozen.

But please note, when reloading the windows client back up it's sending me back to the login page, and my phone also send me a push message saying I need to re-log in as my session has expired.

Has there been any joy or investigation with this issue?

**Comment by JoshuaaMichael** [comment] 2018-10-10 00:39
Left the windows client open overnight, frozen again this morning.

Should I open a new issue for following this up, as this one is closed?

**Comment by jasonblais** [comment] 2018-10-10 00:52
Thanks @JoshuaaMichael for the updates

Would you be open to listening to the events via Procmon? https://electronjs.org/docs/development/debug-instructions-windows#using-procmon-to-observe-a-process

That might help us narrow down the issue. I've tried keeping my client open overnight too, but haven't reproduced the issue yet.

**Comment by JoshuaaMichael** [comment] 2018-10-10 00:56
Yeah, sure. Not too sure how all that works, so I'll need to get some time to look into it. I'll let you know what I find. Cheers for some next steps.

**Comment by JoshuaaMichael** [comment] 2018-10-10 05:50
Alright. I've watched the video and have an idea of how to do this.
I've started the procmon recording. Will check in on it tomorrow morning and see how it's going.
I'll keep doing that each night until I get that freeze event to occur and then I'll be back in touch.

Cheers.

**Comment by JoshuaaMichael** [comment] 2018-10-17 22:56
Hey guys. Although this freezing has certainty happened on this msi version of the client, I can't get it to reoccur and I've tried for quiet a few days now.

Due to time constraints I've still had to roll MM out to our company, so if staff here are able to replicate the issue during their normal use I'll follow this up.

Thanks for your help.
Regards,

**Comment by JoshuaaMichael** [comment] 2018-10-23 03:02
Hey guys. The client decided to crash a couple times on me today, so I fired up procmon to see if I could capture it and I was able to successfully do so.

After I found it was frozen at 1:57pm I stopped the collection and saved the data. It's 100MB but compressed very well down to just below 10MB.

[Logfile.zip](https://github.com/mattermost/desktop/files/2504279/Logfile.zip)

**Comment by JoshuaaMichael** [comment] 2018-11-05 23:53
Any update on this?

Should it be moved to an open ticket?

**Comment by jasonblais** [comment] 2018-11-05 23:56
> Should it be moved to an open ticket?

@yuya-oc or @wget thoughts?

**Comment by wget** [comment] 2018-11-06 07:53
@jasonblais When developping the msi installer, I have been able to notice weird things with the app. Please leave this issue open by the end of week.

**Comment by wget** [comment] 2018-11-06 09:10
@JoshuaaMichael When you said minimized, do you mean minimized to the sys tray or the task bar?

**Comment by JoshuaaMichael** [comment] 2018-11-07 02:37
> Please leave this issue open by the end of week.

It's currently not open

> When you said minimized, do you mean minimized to the sys tray or the task bar?

Down into the task bar. I've provided an image below of the area I mean in case there is confusion over terminology.

![image](https://user-images.githubusercontent.com/12680312/48107075-2e054500-e292-11e8-9109-8dd8cce18c26.png)

Looking forward to hearing how this goes. Thanks guys.

**Comment by wget** [comment] 2018-11-07 22:00
@JoshuaaMichael Thanks for these precisions. Currently running the latest build in the systray. No problem so far after 19h. Will leave it as it for the rest of the week. ill keep you posted.

**Comment by JoshuaaMichael** [comment] 2018-11-13 00:09
I haven't had any complaints from our other users, it happens infrequently enough to me that it doesn't matter enough. You've got the log files if you're interested in tracking down the issue. I'm going to close off the ticket in our internal system here and stop following this up.

**Comment by wget** [comment] 2018-11-13 11:17
@JoshuaaMichael OK :) Btw after one week Mattermost has been in the systray, I still wasn't able to reproduce the issue.

**Comment by philipooo** [comment] 2018-12-10 14:30
I currently have this issue on windows running the windows client 4.1.2. Hard to reproduce, but I will look into it.

**Comment by wget** [comment] 2018-12-10 14:34
@philipooo Please update to 4.2.0 as the issue is likely due to a wakelog where the roots are due to an old version of electron.

If you still encounter the issue, please come back to us.

**Comment by maxmukhin88** [comment] 2022-01-26 09:26
I'm having this issue in Windows Desktop client 5.0.0-5.0.1 - very annoying.
Extra info: my Xiaomi laptop is heavy loaded in terms of CPU and RAM. Could it be that the client freezes similar to Chrome tabs and then can't properly reload upon opening the app?
