### ISSUE TITLE
Problem with Syncronizing Group Chats

### ISSUE THREAD

**Issue by tomasnorre** [mattermost/desktop#281] opened 2016-09-13 11:57 UTC
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

Sometimes my laptop (osx) is not synchronizing my group chats?
#### Steps to reproduce

Please include: 
- OSX (10.10.5)
- Mattermost Desktop App version: 1.3.0
- Clear steps to reproduce the issue

I don't know how to reproduce this as it doesn't happen regulary.. But it seams to be a pattern of when the laptop gets back from sleep mode or change network from wifi to lan or vice versa.
#### Expected behavior

Would expect that my chats are always in sync when i'm connected to the internet, regardless of waking up from sleep mode or joining another network.
#### Observed behavior

My colleagues went to me face-to-face to inform me about stuff happened in Chat, that i didn't react to. 
#### Possible fixes

I honestly have no clue.. :(

**Comment by yuya-oc** [comment] 2016-09-13 14:11
Would you check following points? At the moment, it seems that the problem is caused by server's behavior.

- Server version
- Does that happen in web browsers?
- Are there any screenshots or console logs? (You can find it with `View->Toggle Developer Tools` menu).

**Comment by jasonblais** [comment] 2016-09-14 05:15
Thanks @tomasnorre for the report, we'll keep an eye on this.  It sounds like the reconnection isn't happening properly - the Mattermost team did some updates on the server side regarding WebSocket connections for the upcoming v3.4 release, so that might be helpful here.

Whenever it has happened, does changing a channel or making a post bring everything back into sync? Or does it require a refresh of the application page? 

If you have any more information, it would help us investigate the issue further. The Mattermost server version @yuya-oc is referencing above can be found by clicking on the three dots next to your profile picture, then **About Mattermost**).

**Comment by tomasnorre** [comment] 2016-09-14 06:26
Here is a little more information: 

**Server:** 
Mattermost Enterprise Edition
Modern communication from behind your firewall.
Version: 3.3.0
Database: mysql

I've not been using the browser, but will try it out for the next couple of days.

@yuya-oc I don't have any console logs or anything that supports the problem solving. 
@jasonblais I fixes the problem by restarting the Mattermost desktop app.

**Comment by tomasnorre** [comment] 2016-09-14 10:53
The issue happened to me again today, this time in the browser with Chrome - Version 52.0.2743.116 (64-bit) (osx)

When you compare the too screenshots, then you see that is a block missing in the lighter one.

![laptop_1](https://cloud.githubusercontent.com/assets/1212481/18509667/04eb5182-7a7a-11e6-9978-cd8792ef6dc2.jpg)
![laptop_2](https://cloud.githubusercontent.com/assets/1212481/18509668/04f02626-7a7a-11e6-9601-6e06cc9364bf.jpg)

**Comment by jasonblais** [comment] 2016-09-14 17:39
Aah, thanks @tomasnorre! This is really useful information. Mattermost submitted a fix for a related issue in 3.4. 

Wondering if you'd like to try and see if it reproduces on 3.4, once your team has upgraded to the newest version?

(Mattermost 3.4 will be officially released on Friday, but the download links should be available before then on [our downloads page](https://www.mattermost.org/download/))

**Comment by tomasnorre** [comment] 2016-09-14 20:04
I'll check when we will update, and follow up on this.

**Comment by jasonblais** [comment] 2016-09-19 18:44
@tomasnorre 

There have been some reports that users no longer experience missing messages after updating their desktop app from v1.3 to [v3.4 (RC1), which can be downloaded here](https://github.com/mattermost/desktop/issues/285). Would be curious to hear if you've downloaded the RC1, and if so, whether you've experienced missing messages?

Even though the fix I mentioned was done on the server side, maybe there were synchronization problems on the v1.3 client app as well.

**Comment by tomasnorre** [comment] 2016-09-20 05:49
@jasonblais 

I'll be happy to give it a try. :)

**Comment by tomasnorre** [comment] 2016-09-27 15:00
@jasonblais I haven't experienced the problem since client and server update.. 

I first updated the client, and that didn't cause me any problems. The server is now updated to, and didn't face the problem since client update to v1.4.0.

Feel free to close the ticket, it can always be re-opened if something pops up.

**Comment by jasonblais** [comment] 2016-09-30 14:14
Thanks for letting us know @tomasnorre! 

There was another user who reported seeing it at least once on v3.4 desktop. The issue is [suspected to be on the server side](https://mattermost.atlassian.net/browse/PLT-4233), but I'll keep the issue open until then just in case.

Thanks again, much appreciated

**Comment by tomasnorre** [comment] 2016-10-01 08:37
@jasonblais You're welcome, let me know if i should test or verify anything for you.

**Comment by jasonblais** [comment] 2017-01-17 15:13
This should now be fixed with Mattermost server 3.6 ([JIRA ticket here](https://mattermost.atlassian.net/browse/PLT-4233)).

**Closed by jasonblais** 2017-01-17 15:13 UTC
Labels: Server Side
