### ISSUE TITLE
Help users avoid bad UX having to type https://

### ISSUE THREAD

**Issue by vRobM** [mattermost/desktop#865] opened 2018-09-24 18:00 UTC
Summary

When users are on-boarding, every one of them has issues with the server URL, because they don't expect to have to enter http:// or https://

Expected behavior

Have the app accept server URLs without having to specify https:// or http://, it should know how to handle them and try the appropriate alternative in case the initial assumption fails.

Observed behavior

Users are being precise with the server name and the app tells them they have something wrong when they do not.

Possible fixes

Improve input handling at server textbox and checks for the right protocol.

**Comment by amyblais** [comment] 2019-02-13 21:51
Closing via feature request issue: https://mattermost.uservoice.com/forums/306457-general/suggestions/36845176-desktop-app-don-t-require-http-or-https.

**Closed by amyblais** 2019-02-13 21:51 UTC

**Comment by vRobM** [comment] 2019-02-13 23:55
Has this been implemented or just closed? It's not clear.

**Comment by amyblais** [comment] 2019-02-13 23:57
We're moving feature requests to Uservoice (e.g. the one that I opened above https://mattermost.uservoice.com/forums/306457-general/suggestions/36845176-desktop-app-don-t-require-http-or-https) and bugs are moved to Jira (but we'll leave bug reports open in Github until the issue is fixed).

**Comment by vRobM** [comment] 2019-02-14 00:00
ok, thank you.

++ Rob

About me <https://remote.com/r>

**Comment by Mannshoch** [comment] 2021-11-24 11:50
In my opinion that request is important. Mattermost should automatic suggest https. 

Only if https works in no way, inluding selfsigned certificate, it should warn and allow only after approofing to use http.
