### ISSUE TITLE
Left mouse click on tray icon on Linux shows context menu instead of showing the window

### ISSUE THREAD

**Issue by dantalian-pv** [mattermost/desktop#950] opened 2019-03-18 12:54 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
In Mattermost Desktop 4.1.2 and previous versions left mouse click on the tray icon showed a main window, and starting from version 4.2.0 left and right mouse clicks have the same behavior and shows context menu, which is inconvenient in case I have to make two clicks now instead of one to open the window. Furthermore, when I had a message and clicked on the tray icon, it showed the main window and opened a dialog with a new message.

**Environment**
- Operating System: Linux (4.12.14-lp150.12.48-default x64) openSUSE Leap 15.1 with KDE 5.12.5
- Mattermost Desktop App version: 4.2.0 
- Mattermost Server version: 5.8.0 

**Steps to reproduce**

1. Run application with "Show icon in the notification area" and "Leave app running in notification area when application window is closed" setting on KDE. 
2. Close a main window
2. Left mouse click on the tray icon.

**Expected behavior**
Left mouse click on tray icon should show the main windows with opened dialog where new massage is arrived.

**Observed behavior**
Left mouse click shows context menu as well as right mouse click on the tray icon.

**Comment by amyblais** [comment] 2019-03-20 16:42
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14674

**Comment by marcoesposito1988** [comment] 2020-04-05 09:26
This seems to be due to a limitation of electron between versions 3 and 8. The click event is not handled on Linux for these versions.

I opened a PR for the same problem for Rambox [here](https://github.com/ramboxapp/community-edition/pull/2661). In their case, the fix consists in simply bumping the electron version to 8 and properly handling the click event.

Please consider doing the same when you will reach that version of electron 😊

**Comment by devinbinnie** [comment] 2021-12-09 19:58
This is working correctly for me on Kubuntu 20.04 using KDE Plasma and Desktop App v5.0.2.
Closing unless this issue is still relevant.

**Comment by 2019-05-10** [comment] 2021-12-10 08:35
Debian/Sid, MM Desktop 5.0.2 and the original issue still persists.
Please reopen.

**Comment by marcoesposito1988** [comment] 2021-12-10 08:51
Same here on Kubuntu 20.04 with Plasma (fully up to date as of today, Dec. 10th) and 5.0.2. The issue still persists. Already deleted `~/.config/Mattermost`.

**Comment by devinbinnie** [comment] 2021-12-10 14:31
@2019-05-10 @marcoesposito1988 How did you install Mattermost on your machines? I used the .deb and had no trouble.

**Comment by marcoesposito1988** [comment] 2021-12-10 14:34
Thanks for reopening the issue @devinbinnie! I also used the deb. I already tried deleting the config, but if I can try something else (deleting some cache) or you need some logs or more information about my system, just please let me know.

In the weekend I may manage to test it in a fresh VM with a live Kubuntu

**Comment by devinbinnie** [comment] 2021-12-10 14:39
@marcoesposito1988 That's what I used, a fresh Kubuntu VM and it works fine for me. Let me know what your findings are :)

**Comment by marcoesposito1988** [comment] 2021-12-12 23:10
The issue doesn't appear indeed in a fresh instance. I will try to find the root cause of the issue.

**Comment by 2019-05-10** [comment] 2022-02-02 08:42
Why has this been closed?
Unless the issue is solved for existing installations, it certainly cannot be considered solved.
The MS Windows way ("reinstall everything") is definitely not a solution.

**Comment by devinbinnie** [comment] 2022-02-02 15:09
> Why has this been closed? Unless the issue is solved for existing installations, it certainly cannot be considered solved. The MS Windows way ("reinstall everything") is definitely not a solution.

This issue is not closed, we are awaiting investigation. @marcoesposito1988 Did you ever end up finding anything with your investigation?

**Comment by 2019-05-10** [comment] 2022-02-03 11:09
Uh, I apologize. 
I got confused by the "Closed" label on the reference to #1937

**Comment by AKorezin** [comment] 2022-05-27 14:26
Found another case for this problem.

If you close main window before actually configuring any server, then there's no way you can bring main window back again.

### Steps to reproduce

from `master` branch
1. clean all settings
1. `npm ci`
1. `npm run watch`
1. don't configure servers
1. go to settings
1. enable *Show icon in the notification area*
1. enable *Leave app running in notification area when application window is closed*
1. close window without terminating app

### Result

In tray there are no options to bring main window back again.

### Workaround

1. make app restart

**Comment by kevfocke** [comment] 2023-01-20 09:18
I did not have this issue until I installed the [libappindicator-gtk3 package from the Arch Linux repositories](https://archlinux.org/packages/community/x86_64/libappindicator-gtk3/). After installing this, clicking on the system tray did not even register in the mattermost-desktop log in any way. Uninstalling it again fixed the problem.

**Comment by devinbinnie** [comment] 2023-05-04 17:45
This has been fixed in this PR: https://github.com/mattermost/desktop/pull/2708 (actually probably earlier since it's an Electron issue).

Note for users still using libappindicator, this is not fixed and sounds like it won't be fixed upstream. But it should be working for most users.

Closing.

**Closed by devinbinnie** 2023-05-04 17:45 UTC
Labels: Type/Bug, Help Wanted, Linux, Up For Grabs
