### ISSUE TITLE
Notification on my own messages show up if focus changes quickly

### ISSUE THREAD

**Issue by ferceg** [mattermost/desktop#125] opened 2016-05-05 14:20 UTC
To reproduce (on WIndows 10, other OSs may behave differently): 
1. Start a private conversation with somebody
2. Write something then press Enter to send the message
3. Press Alt-Tab quickly to change to another window.

The red notification icon shows up in the taskbar for my own message.
Not a fatal error but quite annoying if chatting quickly while doing something else.

v1.1.1 and Mattermost 2.1 server if that information matters.

**Comment by GhostLyrics** [comment] 2016-05-05 14:27
Seeing the same thing on OS X.

**Comment by yuya-oc** [comment] 2016-05-06 15:39
Currently, the app subscribes DOM every 1 sec. So the behavior might happens when switching focus.
It depends on its timing, so it seems that the behavior can't be fixed completely.

**Comment by johncooper18** [comment] 2016-05-09 06:44
Hi, same here. Would be nice to resolve it. Windows 8.1

**Comment by RangerRick** [comment] 2016-05-31 13:19
Still happening in 1.2 with Mattermost 3.0.2, as well, FYI.

**Comment by yuya-oc** [comment] 2016-08-23 11:49
Hi all, I could not reproduced this issue now with the app v1.3.0 and the server v3.2.0. Would you check this again?

**Comment by jasonblais** [comment] 2016-08-29 22:00
Thanks @yuya-oc, I was unable to reproduce this issue as well with desktop v1.3 / Mattermost server v3.3.

@ferceg @GhostLyrics @johncooper18 @RangerRick Are any of you able to reproduce this with 
 - Desktop app v1.3
 - Mattermost Server v3.2 or v3.3?

**Comment by ferceg** [comment] 2016-08-31 11:44
I'm stuck with v2.1 right now (planned upgrade in progress) so if the other reporters (@GhostLyrics @johncooper18 @RangerRick) could provide feedback it would be appreciated.

**Comment by jasonblais** [comment] 2016-09-04 17:47
Thanks @ferceg! No worries on it.

Removing from v1.4 milestone for now until we have more information on the potential issue,

**Comment by ferceg** [comment] 2016-09-07 10:24
We have managed to upgrade our server to 3.3 (client version is still 1.3).
The problem seems to have gone, couldn't reproduce it anymore.

**Comment by jasonblais** [comment] 2016-09-07 13:27
Great to hear, thanks for letting us know @ferceg!  Much appreciated!

Closing the issue as `cannot reproduce`, if anyone continues to experience it with Mattermost 3.2 and later, feel free to reopen the issue.

**Closed by jasonblais** 2016-09-07 13:27 UTC
Labels: all platforms, more information needed
