### ISSUE TITLE
If you set up two teams and run it, you will see a blank screen.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/desktop#1701] opened 2021-08-18 07:18 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

If you set up two teams and run it, you will see a blank screen.

**Environment**
- Operating System: macOS(Big Sur 11.2.2)
- Mattermost Desktop App version: 4.7.1 
- Mattermost Server version: 5.36.1 

**Steps to reproduce**
1. open buildconfig.js
2. set as below
![image](https://user-images.githubusercontent.com/42505950/129854764-023acd6d-8ede-47a1-a961-b217b66f9708.png)

3. build($npm run package:mac)
4. run mattermost-desktop
5. you will see a blank screen.

**Expected behavior**
The screen should be rendered normally.

**Observed behavior**

**Possible fixes**

**Comment by amyblais** [comment] 2021-08-18 14:26
@devinbinnie Would you be able to help reproduce this?

**Comment by devinbinnie** [comment] 2021-08-18 17:55
@amyblais @bitdessert I can't reproduce this myself, are you able to go into View > Developer Tools for Application Wrapper and see if there are errors in there, and if so can you post them here for me?

**Comment by bitdessert** [comment] 2021-09-08 12:23
This issue occurs when building by changing the NODE_ENV value.

* original script
"package:mac": "cross-env NODE_ENV=production npm-run-all check-build-config build-prod && electron-builder --mac --x64 --arm64 --publish=never",
* modified script
"package:devmac": "cross-env NODE_ENV=dev npm-run-all check-build-config build-prod && electron-builder --mac --x64 --arm64 --publish=never",

In the previous version, there was no problem even if the above script was changed and built.

**Comment by devinbinnie** [comment] 2021-09-08 13:42
@bitdessert Odd. With the above configuration you are packaging the application in such a way that it's expects the app is in development mode. We use different path names for a lot of our files in that mode, so the error we get is below:
```
VM4 sandbox_bundle.js:129 Unable to load preload script: /Users/devin/mm/desktop/release/mac/Mattermost.app/Contents/MacOS/dist/mainWindow.js
VM4 sandbox_bundle.js:129 Error: ENOENT: no such file or directory, open '/Users/devin/mm/desktop/release/mac/Mattermost.app/Contents/MacOS/dist/mainWindow.js'
chromewebdata/:1 Not allowed to load local resource: file:///Users/devin/mm/desktop/release/mac/Mattermost.app/Contents/MacOS/dist/renderer/index.html
```

Do you have a need to package the application in development mode?

**Comment by bitdessert** [comment] 2021-09-08 14:12
@devinbinnie  Thanks, I will solve it by adding environment variables and building.

**Comment by devinbinnie** [comment] 2021-12-09 22:31
Closing as per above.

**Closed by devinbinnie** 2021-12-09 22:31 UTC
