### ISSUE TITLE
Add update check

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1465] opened 2021-02-04 13:08 UTC
Since there's no repository to be checked together with other repos when routinely looking for updates, one has to remember to check https://github.com/mattermost/desktop/releases manually.

Unless there's a repository that integrates with common update facilities like APT or YUM, the client should be able to check for updates on its own and notify the user.

**Comment by Willyfrog** [comment] 2021-02-05 07:54
not sure if this helps, but you can check the latest version of our products in https://notices.mattermost.com/

for yum-like packages there is a community repo mentioned here: https://github.com/mattermost/desktop/issues/986

and for deb-like packages, we are considering [creating a PPA from github pages](https://github.com/mattermost/desktop/issues/1350)

I'm closing this issue, as it is basically a duplicate of those two linked, but feel free to reopen if you think I missunderstood your request

**Closed by Willyfrog** 2021-02-05 07:54 UTC

**Comment by Roy-Orbison** [comment] 2021-03-04 00:30
@Willyfrog Please re-open this issue, it's not really resolved. A client will happily chug along forever, bugs and all, without ever letting the user know there's a newer version. Mattermost should not require thousands of users to manually check a web page to get an update.

Certainly, having a yum repo helps and having deb repo will help. That doesn't solve the problem for users who choose or have to install from a tarball (e.g. no root, different package manager), and ignores users on Windows or MacOS.

Even a weekly checking of the [GitHub feed](view-source:https://github.com/mattermost/desktop/releases.atom) for non-rc versions, then a notification would be better than nothing. It could be done at the server level to reduce thrashing, i.e. server periodically checks feed (or some other source) to get latest desktop client/app version number(s), then notifies any client that connects with an old version, much like the reload prompt bar that appears after the server gets updated.

**Comment by Willyfrog** [comment] 2021-03-04 08:12
Server notifies of new desktop clients (among other things) since 5.28, you can check the full changelog in https://docs.mattermost.com/administration/changelog.html

**Comment by Roy-Orbison** [comment] 2021-03-04 09:00
Thanks, @Willyfrog.

I just installed an old version to see. It seems some users on our server have been conveniently ignoring those. I stopped using the dedicated app since before server v5.28 so had never seen that.

**Comment by Willyfrog** [comment] 2021-03-04 09:03
The update notice for the desktop only appears if the user is actually using the desktop and version doesn't match with the current one. Once the user dismisses it, it won't reappear.

**Comment by 2019-05-10** [comment] 2021-03-04 10:19
@Willyfrog I don't see how this relates to the desktop client.
As far as I can tell, server and client are not released in sync, so an updated server wouldn't necessarily imply an updated client.
OTOH the client may experience new release while the server stays at the same version.

Additionally, an update notice (in what shape ever) has the tendency to appear at the most inconvenient times, hence tends to be ignored to get on with currently more pressing tasks.

I strongly suggest to add a menu entry "Check for updates" as is good practice elsewhere.

**Comment by Willyfrog** [comment] 2021-03-04 10:50
sorry if I expressed myself wrong, the server doesn't have the desktop version built in, but checks for it and compares to the version the desktop being used.

> I strongly suggest to add a menu entry "Check for updates" as is good practice elsewhere.

that's part of a future plan of having the client to autoupdate, but not something we are working on ATM, but as always PRs to improve the client are welcome :)
