### ISSUE TITLE
[Bug]: Can't upload files with ü-Umlaut

### ISSUE THREAD

**Issue by floi** [mattermost/desktop#2806] opened 2023-08-17 12:20 UTC
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.4

### Operating System

KDE neon based on Ubuntu 20.04 x64

### Mattermost Server Version

 7.7.1

### Steps to reproduce

1. Create a file that has an [umlaut](https://en.wikipedia.org/wiki/Umlaut_(diacritic)) in it, the image file I tried had an "ü" in its name.

Variant A
2. Drag the file from the file manager into the Mattermost channel.

or

Variant B
2. Use the upload file button with the paperclip icon and select the file.

### Expected behavior

The file is uploaded and I can add a message or send directly.

### Observed behavior

Variant A

I get the following error:

![image](https://github.com/mattermost/desktop/assets/33099408/9c79cd2c-0203-432a-96a3-e51db4b144b6)

Variant B

Nothing happens.

### Log Output

```shell
[2023-08-17 14:09:20.218] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:09:20.218] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:09:20.219] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:09:20.220] [debug] [ViewManager] focusCurrentView
[2023-08-17 14:09:20.222] [silly] [ServerDropdownView] handleReceivedMenuSize { width: 258, height: 203 }
[2023-08-17 14:09:20.223] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:09:20.223] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:09:20.337] [debug] [ServerDropdownView] handleClose
[2023-08-17 14:09:20.338] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:09:20.338] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:09:20.338] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:09:20.338] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:09:20.339] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:09:23.398] [debug] [App.Utils] flushCookiesStore
[2023-08-17 14:09:23.399] [debug] [ViewManager] handleSetCurrentViewBounds { x: 0, y: 24, width: 1280, height: 776 }
[2023-08-17 14:09:23.401] [debug] [ModalManager] handleResizeModal {
  bounds: { x: 0, y: 24, width: 1280, height: 776 },
  modalQueueLength: 0
}
[2023-08-17 14:09:23.402] [silly] [ServerDropdownView] updateDropdown
[2023-08-17 14:09:23.402] [debug] [ServerManager] getCurrentServer
[2023-08-17 14:09:23.403] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:09:23.404] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenu
[2023-08-17 14:09:23.405] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:09:23.405] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:09:23.406] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:09:23.407] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:09:23.410] [silly] [ServerDropdownView] handleReceivedMenuSize { width: 258, height: 203 }
[2023-08-17 14:09:23.410] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:09:23.416] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:09:57.260] [debug] [App.Initialize] UserActivityMonitor.on(status) { userIsActive: true, idleTime: 0, isSystemEvent: false }
[2023-08-17 14:10:57.320] [debug] [App.Initialize] UserActivityMonitor.on(status) { userIsActive: true, idleTime: 0, isSystemEvent: false }
[2023-08-17 14:11:53.089] [debug] [ViewManager] handleSetCurrentViewBounds { x: 0, y: 24, width: 1280, height: 776 }
[2023-08-17 14:11:53.090] [debug] [ModalManager] handleResizeModal {
  bounds: { x: 0, y: 24, width: 1280, height: 776 },
  modalQueueLength: 0
}
[2023-08-17 14:11:53.091] [silly] [ServerDropdownView] updateDropdown
[2023-08-17 14:11:53.092] [debug] [ServerManager] getCurrentServer
[2023-08-17 14:11:53.092] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:11:53.093] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenu
[2023-08-17 14:11:53.094] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:11:53.095] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:11:53.096] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:11:53.096] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:11:53.097] [debug] [ViewManager] focusCurrentView
[2023-08-17 14:11:53.098] [silly] [ServerDropdownView] handleReceivedMenuSize { width: 258, height: 203 }
[2023-08-17 14:11:53.099] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:11:53.100] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:11:56.083] [debug] [App.Intercom] handleOpenAppMenu
[2023-08-17 14:11:56.092] [debug] [ViewManager] focusCurrentView
[2023-08-17 14:11:56.096] [debug] [ServerDropdownView] handleClose
[2023-08-17 14:11:56.097] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:11:56.098] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:11:56.099] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:11:56.100] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:11:56.101] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:11:56.102] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:11:56.102] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:11:56.103] [debug] [ServerDropdownView] handleClose
[2023-08-17 14:11:56.104] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:11:56.105] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:11:56.106] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:11:56.106] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:11:56.107] [debug] [DownloadsDropdown...] handleClose
[2023-08-17 14:11:56.108] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:11:56.109] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:11:56.110] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:11:56.111] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:11:56.112] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:11:56.113] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:11:57.380] [debug] [App.Initialize] UserActivityMonitor.on(status) { userIsActive: true, idleTime: 0, isSystemEvent: false }
[2023-08-17 14:12:01.167] [debug] [ViewManager] focusCurrentView
[2023-08-17 14:12:01.167] [debug] Diagnostics.run
[2023-08-17 14:12:01.168] [debug] Diagnostics.initializeValues
[2023-08-17 14:12:01.168] [debug] Diagnostics.getStepCount { stepsCount: 12 }
[2023-08-17 14:12:01.168] [debug] Diagnostics sendNotification DiagnosticsStarted
[2023-08-17 14:12:01.169] [info]  Diagnostics.executeSteps Started
[2023-08-17 14:12:01.682] [debug] [App.Utils] flushCookiesStore
[2023-08-17 14:12:01.683] [debug] [ViewManager] handleSetCurrentViewBounds { x: 0, y: 24, width: 1280, height: 776 }
[2023-08-17 14:12:01.684] [debug] [ModalManager] handleResizeModal {
  bounds: { x: 0, y: 24, width: 1280, height: 776 },
  modalQueueLength: 0
}
[2023-08-17 14:12:01.684] [silly] [ServerDropdownView] updateDropdown
[2023-08-17 14:12:01.684] [debug] [ServerManager] getCurrentServer
[2023-08-17 14:12:01.684] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:12:01.684] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenu
[2023-08-17 14:12:01.685] [debug] [DownloadsDropdown...] updateDownloadsDropdownMenuItem {}
[2023-08-17 14:12:01.685] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:12:01.685] [debug] [DownloadsDropdown...] updateWindowBounds
[2023-08-17 14:12:01.685] [debug] [DownloadsDropdown...] updateDownloadsDropdown
[2023-08-17 14:12:01.689] [silly] [ServerDropdownView] handleReceivedMenuSize { width: 258, height: 203 }
[2023-08-17 14:12:01.690] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:12:01.690] [silly] [DownloadsDropdown...] handleReceivedDownloadsDropdownSize { width: 328, height: 144 }
[2023-08-17 14:12:05.745] [verbose] [MainWindow] main window closed
```

### Additional Information

I observed the same issue in the flatpak version 5.4.4 and the tar-ball version 5.1.1.

**Comment by devinbinnie** [comment] 2023-08-28 18:18
@floi I'm not able to reproduce this on macOS or Linux. I'm using Ubuntu 22.04 with GNOME, so a slightly different environment, but it is the one we support.

I'd have to guess there's some strange interaction between your file manager (I'm assuming Dolphin) and our app, as it should be working otherwise. Does this reproduce in the web browser for you? Are you able to try a different WM/file manager?

**Comment by floi** [comment] 2023-08-29 08:17
@devinbinnie Correct, my main filemanager is Dolphin. I've just quickly tried thunar from XFCE and it shows the exact same behavior. I can do more testing some other time.

**Comment by devinbinnie** [comment] 2023-08-29 11:19
@floi Thanks for testing, at this point I'd recommend trying Nautilus if you can, or upgrading your Ubuntu installation.

**Comment by devinbinnie** [comment] 2024-01-03 19:42
Closing as this is more than likely a file manager issue.

**Closed by devinbinnie** 2024-01-03 19:42 UTC
Labels: Type/Bug, More Information Needed, Cannot Reproduce
