### ISSUE TITLE
Add option to hide menu bar

### ISSUE THREAD

**Issue by Yures** [mattermost/desktop#630] opened 2017-10-18 07:54 UTC

**Comment by jasonblais** [comment] 2017-10-18 13:15
Thanks @Yures! Duplicate of https://github.com/mattermost/desktop/issues/457

Which operating system do you use (Windows / Linux / ...)

**Closed by jasonblais** 2017-10-18 13:15 UTC
Labels: Duplicate, Feature

**Comment by Yures** [comment] 2017-10-18 13:37
Windows

2017-10-18 16:16 GMT+03:00 Jason Blais <notifications@github.com>:

**Comment by jasonblais** [comment] 2017-10-18 13:44
Thanks! Attached is what we had in mind on Windows, which is integrating the menu bar into the UI itself on Windows.

![image](https://user-images.githubusercontent.com/13119842/31722025-efa1e710-b3e8-11e7-8942-09dc8927ce1d.png)

**Comment by Yures** [comment] 2017-10-18 17:11
looks good

**Comment by UnwantedTachyon** [comment] 2019-02-03 15:13
What about linux?
