### ISSUE TITLE
When "start app on login" is enabled, the app starts as a blank page, only way to fix is to restart the app.

### ISSUE THREAD

**Issue by nickolasdeluca** [mattermost/desktop#1095] opened 2019-10-28 10:58 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Whenever I boot up my computer, the app starts as a blank page, forcing me to restart the app to use it.

**Environment**
- Operating System: Windows 10 64 Bits [build 1903]
- Mattermost Desktop App version: 4.3.0
- Mattermost Server version: 5.16.0 

**Steps to reproduce**
It is reproduceable, just restart the computer and it'll start as a blank page.

**Expected behavior**
To load completely.

**Observed behavior**

No error messages what so ever, it is just a blank panel.

**Possible fixes**

If you can, link to the line of code that might be responsible for the problem.

**Comment by svelle** [comment] 2019-10-28 10:59
Hi @nickolasdeluca we have this tracked on our Jira here: https://mattermost.atlassian.net/projects/MM/issues/MM-19649

if you like you can subscribe to the issue there to get updates on the status of this.

**Comment by nickolasdeluca** [comment] 2019-10-28 11:21
Ah ok, good to know it is not just us, I was starting to wonder if I had made any mistakes when setting up the server. Thanks!

**Comment by cbrand-ludlums** [comment] 2019-10-29 22:13
I'm seeing this too on v4.3 and v4.3.1 on multiple computers.  I've found that I can resize the window and it will display correctly.  I was about to post this same issue here.

**Comment by jberent** [comment] 2019-11-18 17:03
View | Reload - or Clear Cache and Reload don't help, but opening Settings and closing has rendered the page without restarting. I am trying w/ GPU-acceleration disabled to see if that helps like it did in 2018 when that option was added.

**Comment by nickolasdeluca** [comment] 2019-11-18 17:09
> View | Reload - or Clear Cache and Reload don't help, but opening Settings and closing has rendered the page without restarting. I am trying w/ GPU-acceleration disabled to see if that helps like it did in 2018 when that option was added.

It's currently being fixed already, you can check the status here: [MM-19649](https://mattermost.atlassian.net/browse/MM-19649?atlOrigin=eyJpIjoiYzg3MTMwZjA4ZGEyNDVmOGJlZTIwYjAyNzVhZWE4NjgiLCJwIjoiaiJ9)

**Comment by amyblais** [comment] 2019-11-29 21:51
We just released 4.3.2 dot release that fixes this issue, please upgrade and let us know if the issue is fixed,

**Comment by cbrand-ludlums** [comment] 2019-11-30 15:29
The issue is fixed.  It's working perfectly now.  On windows restart the app starts minimized in the system tray and double clicking on the icon, it shows the application screen as expected.  No white/blank screen on startup now.  Thanks!

**Comment by nickolasdeluca** [comment] 2019-12-01 03:45
Agreed, issue appears to be fixed.
But about the app starting minimized... it this intended? We don't have a saying on this? I liked it better when it launched just how I left it. Now I have to manually click on the taskbar to bring it back up...

**Comment by trch15** [comment] 2019-12-11 01:23
Confirming the issue is resolved on 4.3.2.

**Comment by adduc** [comment] 2020-01-20 14:56
I'm not sure this is fixed on all desktop apps.

I'm currently running 4.3.2 on Ubuntu 19.10, and the application starts blank on login, and requires the restart to begin working.

**Comment by cguess** [comment] 2020-07-10 21:46
Running 5.24.0 on MacOS and seeing this in Firefox, Safari, Chrome and desktop app.

**Comment by amyblais** [comment] 2020-07-13 12:09
What desktop app version are you on?

**Comment by amyblais** [comment] 2021-09-08 18:43
Closing as this was addressed, but feel free to re-open this as needed,

**Closed by amyblais** 2021-09-08 18:43 UTC
