### ISSUE TITLE
Notifications in team tabs duplicated

### ISSUE THREAD

**Issue by hamishgraham** [mattermost/desktop#336] opened 2016-10-06 08:44 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

If you receive a Direct Message all team tabs show the unread message count.

#### Steps to reproduce

Environment
- OS X 10.12
- Mattermost Desktop App version: 3.4.1
- Mattermost Server version: v3.3.0 
- Clear steps to reproduce the issue

1) Have multiple team tabs visible.
2) Receive a direct message from a contact.
3) Both tabs show the unread message count (see http://imgur.com/a/ndyhi).
4) You need to read the same message in both teams for both unread counts to be removed.

#### Expected behavior

It would be better if the unread notification was shown only on the *active* team and not on all teams.

**Comment by Razzeee** [comment] 2016-10-06 10:18
Are both teams on the same server by any chance?

**Comment by hamishgraham** [comment] 2016-10-06 10:37
Yes they are.

**Comment by yuya-oc** [comment] 2016-10-06 12:57
Duplicate of #160.

**Closed by yuya-oc** 2016-10-06 12:57 UTC
