### ISSUE TITLE
GitLab SSO (using a Kerberos-backed SAML IdP) doesn't work on Mac

### ISSUE THREAD

**Issue by jcmcken** [mattermost/desktop#855] opened 2018-08-30 13:33 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14175

**Summary**

There's seemingly no way to configure delegated authentication via Kerberos for Mattermost's Chromium instance using the macOS desktop app.

**Environment**
- Operating System: macOS Sierra (10.12.6)
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 5.0.2

**Steps to reproduce**

* Setup GitLab to perform SAML single sign-on, with Microsoft ADFS as the IdP (i.e. users are authenticated with a Kerberos ticket).
* Setup GitLab as the authentication mechanism for Mattermost.
* Launch Mattermost desktop on Mac.
* Click "GitLab" button.
* IdP presents a basic authentication window rather than using Kerberos credentials and the user can't log in.

**Expected behavior**

Using the browser app, using regular Chrome, you can run the following to set the delegation configuration:

```
defaults write com.google.Chrome AuthServerWhitelist "*.example.com"
defaults write com.google.Chrome AuthNegotiateDelegateWhitelist "*.example.com" 
```

With this configuration, Chrome is allowed to Kerberos authenticate with "*.example.com". The GitLab SSO proceeds normally and the user is able to log in to Mattermost using Kerberos credentials.

On Windows, Chromium inherits certain settings from IE, so the Kerberos auth works out of the box with the desktop app.

It doesn't appear that there's any way to configure these same settings for Mattermost's Chromium instance on Mac.

**Comment by yuya-oc** [comment] 2018-08-31 12:12
Sadly I'm not really sure about SAML and Kerberos though, did you try the command with `com.mattermost.desktop`? It's the bundle identifier for the desktop app.

```
defaults write com.mattermost.desktop AuthServerWhitelist "*.example.com"
defaults write com.mattermost.desktop AuthNegotiateDelegateWhitelist "*.example.com" 
```

**Comment by jcmcken** [comment] 2018-08-31 13:54
Yes, that was tried as well. Just throwing darts, we also tried the commands for ``com.mattermost.desktop.helper``

Just as another point of comparison (not sure if this helps): In Firefox, you can navigate to ``about:config`` and set similar parameters, e.g. ``network.negotiate-auth.trusted-uris``

**Comment by jcmcken** [comment] 2018-08-31 13:56
Apparently there are Chrome CLI options associated with each of the options:

```
       --auth-server-whitelist
       --auth-negotiate-delegatewhitelist
```

We tried passing these too, but no luck

**Comment by yuya-oc** [comment] 2018-09-03 11:39
Well, it seems that those args are also supported on Electron. So I think they should be enabled by passing args.

https://github.com/electron/electron/blob/v1.8.4/docs/api/chrome-command-line-switches.md#--auth-server-whitelisturl

**Comment by amyblais** [comment] 2019-02-13 19:10
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14175.

**Comment by amyblais** [comment] 2019-02-27 19:27
Closing this as a duplicate of https://github.com/mattermost/desktop/issues/920.

**Comment by jcmcken** [comment] 2019-02-28 19:31
@amyblais This issue duplicates an issue reported 6 months later? That seems to violate the laws of physics.

Additionally, that issue is also reporting different conditions than this one. That issue deals with version 4.2.0, not 4.1.2. That issue deals with the Windows client app failing, this one deals with macOS. 

I don't agree at all with conflating these two issues

**Comment by amyblais** [comment] 2019-02-28 19:47
@esethna ^ Maybe the wrong ticket was closed as dup?

**Comment by devinbinnie** [comment] 2021-12-09 19:28
Closing as inactive, we done some work on external auth providers and this issue may be fixed.
Happy to re-open if it is not.

**Closed by devinbinnie** 2021-12-09 19:28 UTC
Labels: MacOS

**Comment by kcrawford** [comment] 2022-01-09 22:30
Issue still exists here.  SSO login via Kerberos works in Safari and Google Chrome, but not Mattermost.

**Comment by devinbinnie** [comment] 2022-01-10 14:36
@kcrawford Are you able to reproduce consistently on v5.0.2?

**Comment by kcrawford** [comment] 2022-01-10 19:03
Yes I tested on 5.0.2. Is any config needed to enable use of Kerberos in the app?

**Comment by philippderdiedas** [comment] 2023-10-15 21:22
how about https://www.electronjs.org/docs/latest/api/command-line-switches#--auth-negotiate-delegate-whitelisturl
