### ISSUE TITLE
Link url not visible when maximized

### ISSUE THREAD

**Issue by baek-sang** [mattermost/desktop#1663] opened 2021-07-17 07:27 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 21H1
- Mattermost Desktop App version: 4.7.0 
- Mattermost Server version: Cloud 

**Steps to reproduce**
1. Maximize client
2. Mouse over link

**Expected behavior**
![ml](https://user-images.githubusercontent.com/69100154/126029633-ec0515e7-c577-41ae-8322-13f73bd8f172.png)
Show link url when client not maximized

**Observed behavior**
![ml2](https://user-images.githubusercontent.com/69100154/126029489-2d7ed4f1-a8a5-4e33-877f-0b1ec30b0041.png)
- Hide link url
- Color mix match ( Dark theme but white background )

Even if the taskbar is not at the bottom, same issue.

**Possible fixes**

**Comment by amyblais** [comment] 2021-07-17 22:16
This is likely a duplicate of https://github.com/mattermost/desktop/issues/1640.

**Closed** 2021-07-17 22:51 UTC
