### ISSUE TITLE
Tray icon on Ubuntu is missing

### ISSUE THREAD

**Issue by florianrusch** [mattermost/desktop#765] opened 2018-04-19 11:01 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Tray icon on Ubuntu 17.10 is not shown

**Steps to reproduce**
I've installed the mattermost client with the .deb package. Configured my server and then try to configure the client itself. But at both options, Light and Dark, the tray icon is not shown.

- Operating System: Ubuntu 17.10 - 64 Bit - Kernel 4.13.0-38-generic
- Mattermost Desktop App version: 4.0.1
- Mattermost Server version: Mattermost Team Edition 4.7.1 (4.7.3) with postgres

**Expected behavior**
Show the tray icon.

**Observed behavior**
The fields `trayIconTheme` and `showTrayIcon` in the `~/.config/Mattermost/config.json` are set correctly.

Config:
```json
{
  "teams": [
    {
      "name": "xxx",
      "url": "https://xxx"
    }
  ],
  "showTrayIcon": true,
  "trayIconTheme": "dark",
  "version": 1,
  "minimizeToTray": true,
  "notifications": {
    "flashWindow": 2,
    "bounceIcon": false,
    "bounceIconType": "informational"
  },
  "showUnreadBadge": true,
  "useSpellChecker": true,
  "spellCheckerLocale": "de-DE"
}
```

**Possible fixes**
-/-

**Comment by erik-alatest** [comment] 2018-05-03 09:09
Confirmed not working in 18.04. 
No tray icon.

**Comment by yuya-oc** [comment] 2018-05-03 13:47
Reproduced on Ubuntu 18.04. And v4.1.0 would fix the problem. You can download RC2 from https://github.com/mattermost/desktop/issues/768#issuecomment-386037913.

**Comment by Blemicek** [comment] 2018-05-11 20:29
The v4.1.0 RC2 doesn't fix the issue for all scenarios, e.g. communitheme (`XDG_CURRENT_DESKTOP=ubuntu-communitheme:ubuntu:GNOME`). The problem is in electron (see [electron/lib/browser/init.js#L166]( https://github.com/electron/electron/blob/bbba9ff906fce768b258569e84652bf1487338fa/lib/browser/init.js#L166)).

The simplest workaround is to modify `mattermost-desktop.desktop` file to use correct value in `XDG_CURRENT_DESKTOP` enviroment variable. E.g.:
```
Exec=env XDG_CURRENT_DESKTOP=Unity /opt/Mattermost/mattermost-desktop
```

**Comment by ankurloriya** [comment] 2018-08-21 12:28
Reproduced on **Ubuntu 18.04, MatterMost app 4.1.2, And MatterMost Server 4.8.0 (mysql)**
It seems like Electron issue facing in the Slack app as well.

**Comment by hozblok** [comment] 2018-12-14 13:16
That’s because Ubuntu 18.04 main repository removes ‘libgtk2-appindicator-perl’, a perl bindings for libappindicator that Mattermost requires it for showing software icon in system tray.

workaround:
`sudo apt-get install libappindicator-dev`

That works for me.

**Comment by amyblais** [comment] 2019-02-13 18:38
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14162.

**Comment by toreanderson** [comment] 2020-07-17 12:25
Same issue on Fedora 32 with GNOME desktop environment. 

Mattermost Destkop was installed using the GNOME software utility, which installs the following Flatpak under the hood:

```
[:~] $ flatpak info com.mattermost.Desktop

Mattermost - Opensource team chat

          ID: com.mattermost.Desktop
         Ref: app/com.mattermost.Desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.5.0
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 309,3 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 90aab043460424c475f810436c6e43c6c5d9d4527d2f1530c9d46effe13e2a54
      Parent: 2b060ee5b0171907e052754670d475658909abae04ce43da6b8781d76c9310e7
     Subject: Release 4.5.0 (e4508ed1)
        Date: 2020-06-17 06:15:48 +0000
```

`gnome-shell-extension-appindicator` is installed and appears to work fine, at least other apps such as Signal and Slack (both installed using Flatpak) do have their icons shown there.

There are a couple of Gtk error messages appearing when starting the application, I do not know if those are relevant in any way:

```
[:~] $ flatpak run com.mattermost.Desktop 
Gtk-Message: 14:22:16.211: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:22:16.211: Failed to load module "pk-gtk-module"
Gtk-Message: 14:22:16.211: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:22:16.211: Failed to load module "pk-gtk-module"
14:22:16.392 › Current working directory is /home/tore, changing into /app/main
config.autostart has been configured: true
```

Let me know if I can provide any other debug information.

**Comment by mhoffmeyerDC** [comment] 2020-08-20 03:17
> Same issue on Fedora 32 with GNOME desktop environment.
> 

Might be related to [this issue](https://github.com/electron/electron/issues/10427) in Electron.

I was able to get my icons for this and others working with the [KStatusNotifierItem/AppIndicator Support ](https://extensions.gnome.org/extension/615/appindicator-support/) extension.

**Comment by toreanderson** [comment] 2020-09-06 12:18
> Same issue on Fedora 32 with GNOME desktop environment.
> 
> Mattermost Destkop was installed using the GNOME software utility, which installs the following Flatpak under the hood:

I have found that this issue is specific to the Flatpak distribution, and that it can be worked around by simply reloading the AppIndicator GNOME Shell extension while Mattermost Desktop is running. Issue filed at flathub/com.mattermost.Desktop#15.

**Comment by andrsharov** [comment] 2020-09-11 10:04
On Xubuntu 20.04 I have same problem. 
```
root@Unnamed:~# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
```
root@Unnamed:~# uname -a
Linux Unnamed 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Install package **libappindicator-dev** was resolved the problem.
```
sudo apt-get install libappindicator-dev
```
@hozblok , Thanks

**Comment by vintprox** [comment] 2020-12-22 13:47
I have this issue on Ubuntu 20.04 as well.

> sudo apt-get install libappindicator-dev

Another 256 MB of disk space for tray icon? Fascinating.

**Comment by shiftgeist** [comment] 2020-12-22 14:03
> sudo apt-get install libappindicator-dev

If I am not mistaken this package is not available on Debian 10.

**Comment by xurei** [comment] 2021-01-29 11:42
I noticed that `sudo apt-get install libappindicator3-1` also fixes it (Debian Stable, GNOME 3.30)

**Comment by devinbinnie** [comment] 2021-12-09 19:14
This is working on Ubuntu 20.04 LTS, closing for now.
Happy to re-open if this is still an issue.

**Closed by devinbinnie** 2021-12-09 19:14 UTC
Labels: Type/Bug, Help Wanted, Linux, Hacktoberfest, Up For Grabs

**Comment by nteodosio** [comment] 2022-11-24 20:54
This is an issue for me on 5.2.1 (snap).

**Comment by devinbinnie** [comment] 2022-11-25 14:16
@nteodosio Do you have `libappindicator` installed? I think it might be a slightly different library for newer versions of Ubuntu as well.

**Comment by nteodosio** [comment] 2022-11-25 14:30
`libappindicator1` is installed; By the way I see `libappindicator3-1` is available, but installing it would remove several important packages in the system, such as `network-manager-gnome`.

Now, re-reading this I'm not sure my issue is the same of the reporter's. For me, the icon is missing, but the tray element is there, because I can click it and bring up the context menu. I provided additional information in the snap repository: https://github.com/snapcrafters/mattermost-desktop/issues/64.

**Comment by devinbinnie** [comment] 2022-11-25 14:38
Is it perhaps the wrong colour? If you go into Settings, under tray icon you can change the colour. It might require a restart but if you play with it then it should pop up.

**Comment by awkto** [comment] 2023-11-14 00:04
This is still an issue on Ubuntu 23.10. 

Still no tray icon for Mattermost

Tried different settings
- Start minimized at launch
- Use dark/light color icon
- Enable/disable tray icon 

Mattermost Desktop app version 5.5.1 in Snap

**Comment by gstlouisgit** [comment] 2024-02-17 21:01
I have just installed debian desktop.  Mattermost settings enabled mattermost run in background, I can see it does run in background, but no icon in system tray anywhere.  Debian cinnamon desktop
