### ISSUE TITLE
macOS client in the Dock spawns a new copy after restart

### ISSUE THREAD

**Issue by tsilcher** [mattermost/desktop#705] opened 2018-01-31 16:08 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14169

**Summary**

**Steps to reproduce**

Please include:
- Operating System: macOS 10.12.6
- Mattermost Desktop App version: Version 4.0.0 (4.0.0.43)
- Mattermost Server version: Version: 4.5.0
- Clear steps to reproduce the issue:
1. Add the Mattermost client to the Dock
2. Click on it to launch the app
3. A new copy of the client is spawned and appears on the right of the Dock
4. Move this copy to the left inside the Dock to save it as a shortcut
5. Restart OS
6. The second copy has now disappeared
7. (Loop...)

**Expected behavior**
After adding the Mattermost client to the Dock it should open the **same** app (bouncing icon like every macOS app, default behavior)

**Observed behavior**
After adding the Mattermost client to the Dock it open a **new copy** of the app displaying two Mattermost icons in the Dock.

Please include relevant error messages and/or screenshots:
![screen shot 2018-01-31 at 16 47 44](https://user-images.githubusercontent.com/17982346/35633324-39280a78-06a9-11e8-8aae-2b79e4babd12.png)
![screen shot 2018-01-31 at 16 53 08](https://user-images.githubusercontent.com/17982346/35633330-3c4820da-06a9-11e8-9d98-9196cbe10fd5.png)
![screen shot 2018-01-31 at 16 52 43](https://user-images.githubusercontent.com/17982346/35633335-4002b528-06a9-11e8-839d-8126d106a9e2.png)

**Comment by jasonblais** [comment] 2018-02-01 14:31
@tsilcher Did you see the issue previously, or is it something new with the new version (v4.0.0)?

**Comment by tsilcher** [comment] 2018-02-01 15:39
This was the same behavior on version 3.x for macOS.

**Comment by jasonblais** [comment] 2018-02-01 15:44
@tsilcher Thanks! 

@yuya-oc If we bundled the Mac app as a .dmg (https://github.com/mattermost/desktop/pull/588), would it fix the issue? Since then the Mattermost app would always be considered as an "Application" by Mac. I think right now it's not always considered as such, unless the user deliberately moves the file to the Applications folder.

**Comment by tsilcher** [comment] 2018-02-01 15:56
Looking a bit deeper I noticed that it is indeed spawning a new instance from a temporary path besides the actual path inside `/Applications`/. For example:

1. `/Applications/Mattermost.app/Contents/MacOS/Mattermost`
2. `/private/var/folders/pk/lcw3xyw97s1416f7thvvlmkht_dlhg/T/AppTranslocation/26A33EB6-428B-4DDA-8D3B-656B2644596F/d/Mattermost.app/Contents/MacOS/Mattermost`

**Comment by yuya-oc** [comment] 2018-02-05 14:42
@jasonblais Possibly .dmg might fix the issue. I have found issues which are similar to ours.

- https://github.com/electron/electron/issues/9293
- https://github.com/Microsoft/vscode/issues/13389

In the issue, a workaround is posted: https://github.com/electron/electron/issues/9293#issuecomment-331425878

**Comment by jasonblais** [comment] 2018-02-06 03:00
Does that workaround help you @tsilcher?

**Comment by tsilcher** [comment] 2018-02-06 08:37
It does **not work** for me. It seems to be a problem with the Electron framework.

**Comment by jasonblais** [comment] 2018-02-06 13:38
Yeah, seems to be a bug with Electron.

I see a note in https://github.com/electron/electron/issues/9293 that `Chrome browser for mac is a dmg file that requires user to drag its executive program to ~/Applications...` and doesn't reproduce for it. So hopefully the .dmg file would resolve this.

**Comment by amyblais** [comment] 2019-02-13 18:48
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14169.

**Comment by esethna** [comment] 2019-02-27 19:39
Should be fixed in v4.2. Please comment if not and we can reopen

**Closed by esethna** 2019-02-27 19:39 UTC
Labels: Bug, Electron, MacOS
