### ISSUE TITLE
Crash during upgrade of Mattermost to version 5.5.1 (signature issue)

### ISSUE THREAD

**Issue by e-guerin** [mattermost/desktop#2888] opened 2023-10-18 07:52 UTC
Hello,

Mattermost desktop app crashes during upgrade to version 5.5.1

I currently have Mattermost desktop app version 5.4.0 running on windows 10 Professional.
A pop-up window regularly suggests me to upgrade Mattermost desktop app to version 5.5.1. When I follow the link provided, the new version is downloaded and then the app crashes.

The attached error message is displayed following this crash.

[uncaughtException-1697612097593.txt](https://github.com/mattermost/mattermost/files/12998719/uncaughtException-1697612097593.txt)

Best regards,
E.Guerin

**Comment by devinbinnie** [comment] 2023-10-18 14:03
This is a duplicate of https://github.com/mattermost/desktop/issues/2855 I believe.

This is likely to do with some restrictions in your local environment that are not allowing for a different signer than the ones currently allowed by your system.

I'd recommend doing an update to Windows if you have administrator control of your system, or contact your system administrator if you don't.

**Comment by devinbinnie** [comment] 2024-01-03 19:38
Closing as duplicate as per above.

**Closed by devinbinnie** 2024-01-03 19:38 UTC
Labels: Type/Crash Report
