### ISSUE TITLE
MM with apache2 Proxy / Windows Client / Links to another path of subdomain not working

### ISSUE THREAD

**Issue by sonsofabraxas** [mattermost/desktop#1336] opened 2020-07-02 13:46 UTC
- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Links to other URL-Paths of the same domain as Mattermost not working in the Windows Desktop App

**Environment**
- Operating System: Windows 10 Pro, Version 1909, Build 18363.900
- Mattermost Desktop App version: v4.5.0
- Mattermost Server version: 5.24.1
Database Schema Version: 5.24.0
Database: mysql

Apache2 Proxy Config on Linux Debian:
[apache2_config_mydomain.txt](https://github.com/mattermost/desktop/files/4864648/apache2_config_mydomain.txt)

**Steps to reproduce**
    1. As any user, post a link to a path, that is on the same as Mattermost site url. (For example:   https://mysubdomain.mydomain.ch/AnyOtherServiceOrSite whilst having Mattermost site url on https://mysubdomain.mydomain.ch/Mattermost)
    2. Try to klick the Link in the Windwos Client.

**Expected behavior**
The link to another path of the same subdomain should open in a new tab in the browser.

**Observed behavior**
Nothing happens. No new Browsertab is opened, nothing in the logfiles.
The same link on the same machine works from the browser-client of Mattermost.
Any other link with other domains works.

**Possible fixes**
--

**Comment by Willyfrog** [comment] 2020-07-27 14:11
there is a future trusted resources feature for next version that would help alleviate this, as it is exactly the case you are describing. But in order for it to work you would have to add the path to buildconfig.js and recompile the sources.

you can find the future documentation about it in this other PR: https://github.com/mattermost/docs/pull/3720/files

**Comment by dasty** [comment] 2021-07-20 20:08
We have exactly the same issue on Mattermost Desktop App version: v4.7.0. I noticed, that this bug was already once reported as https://mattermost.atlassian.net/browse/MM-14446 and even fixed in the past by https://github.com/mattermost/desktop/pull/946 so if there could again be a solution, which does not involve modifying buildconfig.js and recompiling desktop app as suggested in trusted resources feature, that would be greatly appreciated.

**Comment by Willyfrog** [comment] 2021-07-21 08:19
the reason for it being in buildconfig is so it is admin enforced, for windows we could probably use a gpo policy to get similar results, but on macos and linux it would be a config file that could be modified and with that have a user open links to servers that might not be safe for them.

**Comment by dasty** [comment] 2021-07-21 09:37
@Willyfrog - thank you for your comment. I am sorry, I did not read carefully enough original report. In Mattermost version 4.7 the observed behavior is slightly different. The link opens inside the mattermost app, which is clearly strange - please see attached screenshot, which I used to teach my colleagues to get out of the situation :)

![image](https://user-images.githubusercontent.com/411158/126466758-4d629a54-4fe3-4791-8df4-9270d4c620f2.png)

I know, this is clearly something what is not easy to get right. One thing which I should mention is, that we are also using feature "sign in with gitlab" and our internal gitlab instance runs on the same domain as the mattermost, our jira, etc.

**Comment by Willyfrog** [comment] 2021-07-21 12:38
Hello @dasty , can you provide a made up example that mimics your setup?

**Comment by dasty** [comment] 2021-07-21 13:51
@Willyfrog - uff installing completely such example somewhere may be quite difficult :( I can at least describe setup for you in detail:

https://company.com/mattermost
https://company.com/jira
https://company.com/gitlab

In mattermost configuration
=> ENVIRONMENT / site URL points to  https://company.com/mattermost
=> GitLabSettings / AuthEndpoint, TokenEndpoint, UserApiEndpoint all points to https://company.com/gitlab/...

I also tried to reproduce the bug on community instance by sending myself a link https://community.mattermost.com/does-not-exist, but there I believe such a link should be followed, as it is within the server URL and since the community instance runs in / it may not be reproducible there.

**Comment by dasty** [comment] 2021-07-22 07:26
@Willyfrog - one more idea, for possible solution: It always work correctly in the web browser as the server generates following HTML code for the links in the chat:

`<a class="theme markdown__link" href="https://company.com/jira/" rel="noreferrer" target="_blank">https://company.com/jira/</a>`

would it make sense to modify the mattermost app, in the way that links which specify target="_blank" are always open in the browser? I would honestly believe, that would be logical as that is exactly what _blank target is for [1], isn't it?

[1] https://www.w3schools.com/tags/att_a_target.asp

**Comment by Willyfrog** [comment] 2021-07-22 08:52
i'm afraid the problem is a bit more complex as the desktop is making the decision but it is failing in your case as it can't detect if the mattermost server is at <domain>/mattermost or just <domain>, the reason for that is that some people use subpath to install mattermost and some people don't add the base server url and we try to make them both work, so when faced with <domain>/jira it doesn't know if it is a different server or a different mattermost team so it shows in the main window.

this is a problem we are well aware and we talk about it frecuently, but the problem is that we will end up breaking someone's setup, so it is hard to choose.

**Comment by dasty** [comment] 2021-07-22 09:01
@Willyfrog - thank you for answer. We only have one team, so I was not aware that links to other teams may also contain 'target="_blank"' - at least that is how I understand your answer. Than it is really not easy solve :( You would have to send list of URL's which are internal from server to app probably even before login, to be able to do the gitlab sign.

**Comment by Willyfrog** [comment] 2021-07-22 09:17
it shouldn't contain `target="_blank"` the problem is that when something tries to navigate to a new window we have to figure out if it was actually within the server.
the code to manage the `target="_blank"`can be found in this function: https://github.com/mattermost/desktop/blob/master/src/main/views/webContentEvents.ts#L85

**Comment by dasty** [comment] 2021-07-22 12:02
Thank you very much for sending this link. I was not aware of all the special corner cases you need to handle, for example I was up to now not aware of plugins, as we are not using them. So my limited understanding of that function is as follow:

1) check for various special cases when it should be open in external browser (help, outside server link, image proxy case, ...)
2) check if it is admin url, which should not be open in new window even it has `target="_blank"`
3) check for plugin cases when it should be open in popup windows
4) otherwise do no nothing and open it in the current window (regardless of `target="_blank"`)

Maybe this logic could be inverted / simplified into

1) check if it is admin url, which should not be open in new window even it has `target="_blank"`
2) check for plugin cases when it should be open in popup windows
3) open in the external browser.

It just sounds wrong me, that default action in function for `target="_blank"`, when no condition is met, is to use the same window.

**Comment by Willyfrog** [comment] 2021-07-26 07:42
> It just sounds wrong me, that default action in function for target="_blank", when no condition is met, is to use the same window.

The default action is to not do anything, there is a preventdefault that will prevent any navigation on the main window. The reason for being this restrictive is because it is not a full browser and shouldn't be used as that (it is also an older version of chromium and it might be insecure)

**Comment by dasty** [comment] 2021-07-26 07:53
thank you for the explanation - sorry I am not very strong in JavaScript / TypeScript, so I missed the default :( Still opening in external browser as default action would not compromise the security, but that would not solve our problem as obviously the same window opening has to be executed in some other condition I did not noticed. Anyway thank you for all the time you spend explaining to me. It is highly appreciated and I am unfortunately getting a feeling that there is no easy way how to resolve this :(

**Comment by devinbinnie** [comment] 2021-12-09 21:07
Closing as per the above conversation. We can re-open if anyone else has further information/suggestions.

**Closed by devinbinnie** 2021-12-09 21:07 UTC
