### ISSUE TITLE
session expired on relaunch

### ISSUE THREAD

**Issue by bitdessert** [mattermost/desktop#1039] opened 2019-09-20 05:10 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [ ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

After terminate from the tray icon on window 7, 10 and macOS, restart the app, then the session is expired.

**Environment**
- Operating System:windows 10, windows 7, macOS
- Mattermost Desktop App version: 4.2.3 
- Mattermost Server version: 5.14.2

**Steps to reproduce**
1. login the app(mattermost desktop, login succeed)
2. terminate completely(on trayicon in window 10 and macOS)
3. relaunch app
4. session expired

This is not true in all operating environments, but occurs on some PC.
Even if the PC's operating system is the same, the session expires on some PC.(session alive some PC)

**Expected behavior**
The session must be alive.

**Observed behavior**

**Possible fixes**

**Comment by 7-plus-t** [comment] 2019-09-24 08:10
I can confirm the issue on macOS.

**Environment**
- Operating System: macOS 10.14.6
- Mattermost Desktop App version: 4.2.3
- Mattermost Server version: 5.14.2

It works in Chrome, but not in the App. Same behaviour with the Mattermost community server.

**Comment by amyblais** [comment] 2019-09-25 13:44
Can you help with more details on your session settings: https://docs.mattermost.com/administration/config-settings.html#session-lengths?

Can you also help try these troubleshooting steps: https://docs.mattermost.com/install/desktop.html#desktop-app-constantly-asks-to-log-in-to-mattermost-server?

**Comment by 7-plus-t** [comment] 2019-09-25 14:04
Following the troubleshooting steps worked for me 👍 Can no longer reproduce the issue.

**Comment by amyblais** [comment] 2019-10-22 14:45
I'll close this for now as the issue seems to be fixed, but please re-open this issue with relevant additional information if the problem persists,

**Closed by amyblais** 2019-10-22 14:45 UTC

**Comment by altyne** [comment] 2021-12-27 07:31
" Your session has expired. Please log in again."
Same issue version 5.0.2

**Comment by altyne** [comment] 2021-12-28 03:55
> " Your session has expired. Please log in again." Same issue version Mattermost Windows client 5.0.2
> 
> logs from the server: {"timestamp":"2021-12-27 11:04:21.849 +04:00","level":"warn","msg":"Error while creating session for user access token","caller":"app/session.go:89","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=7hjwcgjx97yzxe6ydpbp1raaaa"}
> 
> {"timestamp":"2021-12-27 11:04:21.849 +04:00","level":"info","msg":"Invalid session","caller":"web/handlers.go:253","error":"GetSession: Invalid session token=7hjwcgjx97yzxe6ydpbp1raaa, err=, "}

I tried right now, its working fine.

**Comment by ucola** [comment] 2021-12-29 22:15
Same issue with MacBook, any ideas how to solve it?

**Comment by amyblais** [comment] 2021-12-30 16:04
Please see https://github.com/mattermost/desktop/issues/1935#issuecomment-1000492394.

**Comment by ucola** [comment] 2021-12-30 22:10
Thank you @amyblais I can confirm, that this solution works. Click on X and login again...  if it were always that easy, thank you!
