### ISSUE TITLE
Desktop client never finish loading on macOS

### ISSUE THREAD

**Issue by cmer** [mattermost/desktop#725] opened 2018-03-12 01:57 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
macOS desktop application never finishes loading.

**Steps to reproduce**

macOS High Sierra. MMDA: 4.0.0.

Starting the application never fully loads. The "loading bubbles" never go away. In the Javascript console, I see the following errors, which are likely related:

```
index_bundle.js:47110 [cryptobot] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' cdn.segment.com/analytics.js/ 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-/fduGTteQ63r3X8fy/etywwc4NR3dG0ObNIINeHWGy8='), or a nonce ('nonce-...') is required to enable inline execution.

webview.addEventListener.e @ index_bundle.js:47110
dispatchEvent @ /Applications/Mattermost.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:175
dispatchEvent @ /Applications/Mattermost.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal…:55
(anonymous) @ /Applications/Mattermost.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal…:72
emitMany @ events.js:127
emit @ events.js:204
index_bundle.js:47110 [cryptobot] Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/935cb224/cloudflare-static/rocket.min.js' because it violates the following Content Security Policy directive: "script-src 'self' cdn.segment.com/analytics.js/ 'unsafe-eval'".
```

**Expected behavior**

Should take me to the chat server

**Observed behavior**

It shows the loading indicator forever.

**Comment by amyblais** [comment] 2018-03-12 13:56
@yuya-oc Thoughts on the Javascript console errors?

@cmer Are you still able to reproduce this throughout the day? (I tested this and I wasn't able to repro now)

**Comment by yuya-oc** [comment] 2018-03-12 15:41
I believe the error message is not related to the problem because the error is happening inside the guest webview. Anyway the loading image should finish after 30 seconds timeout.

@cmer Would you tell us the server version? The feature is related to it.

**Comment by yuya-oc** [comment] 2018-03-20 12:06
@jasonblais Is `rocket.min.js` used in webapp? I could not find it in the repository. Just because I feel that the guest server "cryptobot" is not mattermost though.

**Comment by jasonblais** [comment] 2018-03-20 12:11
@yuya-oc Not sure but Joram or Harrison would be good people to ask about it

**Comment by jasonblais** [comment] 2018-04-13 13:16
@cmer Do you know which Mattermost server version is used by your team? This is different from the desktop app version, and helps us with the investigation.

**Comment by cmer** [comment] 2018-04-14 14:12
I was just testing it out and ended up not using Mattermost. I have deleted our server instance so unfortunately I can’t help. Sorry.

**Comment by jasonblais** [comment] 2018-04-14 15:26
@cmer Not to worry, thanks you for following up. I'd be curious to hear why you ended using another service instead, if you were open to sharing?

@yuya-oc should we close this issue, or is there enough information to look into it?

**Comment by yuya-oc** [comment] 2018-04-17 11:25
For now, we close this.

**Closed by yuya-oc** 2018-04-17 11:25 UTC
Labels: Bug, MacOS, More Information Needed, Priority 1
