### ISSUE TITLE
App can't cope with "mandatory ASLR" in Windows 10 1803

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/desktop#852] opened 2018-08-24 08:27 UTC
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14174

**Environment**
- Mattermost Desktop App version: 4.1.2

**Steps to reproduce**
* Toggle Mandatory ASLR -> ON
![aslr](https://user-images.githubusercontent.com/2282799/44573482-6fa44a80-a78f-11e8-99da-c35e963560f4.png)
* Reboot
* Try to install or use the app

**Expected behavior**
App runs

**Observed behavior**
Crash of the app/installer: “Aplication Error 0xc0000005"
Eg. https://forum.mattermost.org/t/windows-10-client-not-starting-on-windows-1803-version/5028

**Possible fixes**
Toggle it to the default (for now?!) OFF

**Comment by yuya-oc** [comment] 2018-08-24 16:09
Reproduced also for me. And not reproduced when the app is not code-signed. So it seems that the problem occurs when Windows apps are code-signed on Linux or Mac.
https://github.com/electron-userland/electron-builder/issues/3188

@esethna @jasonblais Perhaps we might need to build Windows apps on Windows machine. Currently we are using Linux.

**Comment by yuya-oc** [comment] 2018-08-24 16:25
I'll take a look whether I can test with self-signed certificates.

**Comment by jasonblais** [comment] 2018-08-24 17:53
Thanks Yuya (and @licaon-kter!)

@cpanato Thoughts on this issue from dev ops perspective? Should we build the Windows apps on a Windows machine? Do we have one available if we wanted to?

**Comment by yuya-oc** [comment] 2018-08-25 14:39
Not reproduced the build which is built on CircleCI (Linux) with my self-signed certificates. Perhaps our jenkins' wine env might lead this issue because it might be related to wine version. https://github.com/electron-userland/electron-builder/issues/3188#issuecomment-412773642

I'll continue to research.

**Comment by licaon-kter** [comment] 2018-10-17 08:47
Also can repro on Windows 8.1 + [EMET 5.51](https://support.microsoft.com/en-us/help/2458544/the-enhanced-mitigation-experience-toolkit):

**Steps:**
* setup all protections on the highest level
* go to Apps
* Add application -> Mattermost (all toggles are ON)
* press OK
* restart computer
* try to start Mattermost

Pic:
![mattermostemet 5 51 6024 23768_maslr](https://user-images.githubusercontent.com/2282799/47073754-804dcb80-d1e8-11e8-9411-c14737494d67.PNG)

**Possible fixes**
Toggle only this setting to OFF

**Comment by amyblais** [comment] 2019-02-13 19:08
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14174

**Comment by h-h-h-h** [comment] 2019-02-18 14:54
For it was error 0xc000007b on Windows (#927) with Mandadory ASLR enabled.

**Comment by devinbinnie** [comment] 2021-12-09 19:24
Closing as this seems to work now, on Windows 10 with Mattermost Desktop v5.0.2

**Closed** 2021-12-09 19:34 UTC
Labels: Help Wanted, Windows, Hacktoberfest, Up For Grabs
