### ISSUE TITLE
You have to click twice when a window is out of focus to have actions performed

### ISSUE THREAD

**Issue by cetra3** [mattermost/desktop#534] opened 2017-05-12 00:13 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

When the Mattermost window is not in focus, you have to click twice on any UI element to have that action performed.

For instance, change the channel or selecting a direct message.

**Steps to reproduce**

* Operating system is Mac OS X
* Server version is Version: 3.7.0  (3.7.3)
* Desktop Version is 3.6.0

This is a simple one to reproduce:

* Open another window on your desktop, such as a web browser and make sure it has focus
* Click on a different channel, such as Town Square, or a direct message

**Expected behavior**

The click will perform the action to change the channel or direct message

**Observed behavior**

The desktop app is in focus, but the click is not registered, and you have to click again

**Possible fixes**

Not sure, might be an Electron related issue

**Comment by jasonblais** [comment] 2017-05-12 00:21
Thanks @cetra3 for the report!

We fixed a similar issue with https://github.com/mattermost/desktop/pull/262 but that was a while ago. I also tried reproducing on Windows 10, and it seemed to be working for me.

Would you like to download our newest release (desktop app v3.7) from our downloads page (https://about.mattermost.com/downloads) to confirm the latest release doesn't fix the issue?

**Comment by cetra3** [comment] 2017-05-12 00:37
@jasonblais,

I've just given the new version a download. Same issue in `3.7.0`.  It might be a Mac OS X specific thing.  The other thing to note is that the mouse cursor is still the default pointer rather than the click before focus is given.

**Comment by jasonblais** [comment] 2017-05-12 00:50
True, it could be Mac specific.

Just one more test case: when you click on the window, do keyboard shortcuts work for you (for instance, after clicking inside the app window, does CMD+K bring up channel switcher, or do you have to click inside the app twice before the shortcut works)?

**Comment by cetra3** [comment] 2017-05-12 04:10
Yep, the channel switcher works fine after clicking into the window

**Comment by jasonblais** [comment] 2017-05-12 04:40
Thanks! That's helpful to know. We should have enough information to investigate the cause and whether it's something we can fix or if it's an Electron-related bug.

**Comment by yuya-oc** [comment] 2017-07-21 15:06
Sorry for late. I think it's expected behavior in Electron. On macOS, Chrome also requires click

**Comment by jasonblais** [comment] 2017-08-25 12:43
@yuya-oc forgot to come back to this. Thanks for the response.

@cetra3 sounds like this is consistent behaviour with browsers on macOS. Would you like to help try if you see the same behaviour on the Chrome browser?

**Comment by cetra3** [comment] 2017-08-29 04:23
@jasonblais It's the same behaviour.  Can this be switched off via some electron flag or something?

**Comment by jasonblais** [comment] 2017-08-29 12:03
Thanks @cetra3, doesn't look like it: https://github.com/electron/electron/issues/5900

@yuya-oc There seems to be a potential workaround for it, but it wasn't working for everyone: https://github.com/electron/electron/issues/5900#issuecomment-224174095

If the above workaround doesn't work, then there isn't much we can do.

**Comment by yuya-oc** [comment] 2017-08-29 14:06
@jasonblais The workaround is already applied to our app.

The issue is a little different from this. The point is that Electron's BrowserWindow requires a click before handling mouse events on macOS. And I think it looks consistent compared to Chrome.

**Comment by jasonblais** [comment] 2017-08-29 14:14
Thanks @yuya-oc I see.

@cetra3 Unfortunately I don't think there's much we can do at this point. I'll leave the issue open for now with the `Electron` label.

**Comment by jasonblais** [comment] 2018-02-15 04:11
@cetra3 The Electron issue was closed without a fix.

We don't have control to change this behaviour at the moment, given this is how it works on Chrome as well. So I'll regretfully have to close this issue as a Won't Fix.

**Closed by jasonblais** 2018-02-15 04:11 UTC
Labels: Bug, Electron, MacOS, Wontfix
