### ISSUE TITLE
Balloon notification is not shown

### ISSUE THREAD

**Issue by mehmetkemalbayer** [mattermost/desktop#395] opened 2016-12-14 11:05 UTC
In our team some of users can see notification pop-up over tray icon but some of them can not.
On the other hand we tried to figure out the problem by debugging in Visual Studio Code. If you explain how to debug the app we can give you a better information about the reason of the problem.
Thank you.

**Comment by yuya-oc** [comment] 2016-12-14 11:21
Ah, I'm not using debugger in the main process, so I can't say any definite advises. In development mode, `npm start` merely executes `electron` command, so you would be able to refer [Electron's document](https://github.com/mattermost/desktop/releases/tag/v3.5.0).

Wondering if you write about the application version and operating system? I can't even imagine what's happening.

**Comment by mehmetkemalbayer** [comment] 2016-12-14 14:20
Sorry for missing information. App version is 3.5.0 and we all use windows 7. Moreover when I set event from debug console I can see the notification on the tray.

**Comment by prakashprabhakar** [comment] 2016-12-16 06:24
We are running it on Ubuntu 14.04 and 16.04. In both versions when we upgraded the mattermost desktop app from v3.4.0 to v3.5.1 the tray icon is not being shown. Will there be a fix soon?

**Comment by jasonblais** [comment] 2016-12-16 08:01
Hmm @yuya-oc @jnugh wondering if the tray icon is missing in Desktop App 3.5?

**Comment by jnugh** [comment] 2016-12-16 08:20
@prakashprabhakar could you please paste your ~/.config/mattermost/config.json file? I guess the tray icon theme might be missing. 

Workaround would be in this case to open the settings and change the theme to dark/light (depends on what it was before), save the change, go back to settings, change it back, save again and restart the app.

I'm not sure what is causing this, I had the same problem but thought it was due to prior development in this area.

@yuya-oc are we running config upgrade scrips for 3.5 that might delete the theme information?

**Comment by prakashprabhakar** [comment] 2016-12-16 11:46
@jnugh It's working now... Don't ask me how :) ... I restarted my machine twice and it came ... One more person had the same problem, but he is not in today. I will check once he comes and provide you with the inputs you have asked for.

One thing I observed is that the parameter **Icon** was set to Mattermost and not **/home/prakashp/mattermost/icon.png**. The other 2 parameters were correct.

Path=/home/prakashp/mattermost
Exec=/home/prakashp/mattermost/mattermost-desktop

Setting this right made brought the **Launcher Icon** back.

I also copied this mattermost-desktop.desktop which was under ~/.local/share/applications/ to /usr/share/applications/. This needed **_sudo_** and if I am right allowed me to search the application in Ubuntu using 'Windows Key'.

**Comment by yuya-oc** [comment] 2016-12-16 13:23
@prakashprabhakar @jnugh It seems that the original problem of this issue is applicable only for Windows 7 and 8. Please create another issue.

**Comment by yuya-oc** [comment] 2016-12-16 13:26
> Moreover when I set event from debug console I can see the notification on the tray.

@mehmetkemalbayer How did you set the event? There are some consoles in this app, so "how" is very helpful and actual test code would be appropriate.

**Comment by mehmetkemalbayer** [comment] 2016-12-17 07:55
@yuya-oc I send you 3 pictures. 
First one shows my problem, there is no balloon. 
Second one is the answer of your question. I open dev console of the desktop app. I run the command to send the event. 
Last one is the picture showing that it works. 
In short I think that my problem is not about balloon itself. My problem is app cannot get same event normally. By the way I can't understand how other friends can see the balloon. As you may guess they don't send it via console :)
![no_balloon](https://cloud.githubusercontent.com/assets/7826969/21285357/bb0720e6-c43e-11e6-947c-0310a9d1f242.PNG)
![console_command](https://cloud.githubusercontent.com/assets/7826969/21285358/c06b8cfc-c43e-11e6-904f-a799f6f556cb.PNG)
![voila](https://cloud.githubusercontent.com/assets/7826969/21285360/c90aba36-c43e-11e6-8f5b-f0e318160865.PNG)

**Comment by mehmetkemalbayer** [comment] 2016-12-31 20:37
@yuya-oc any updates?

**Comment by yuya-oc** [comment] 2016-12-31 23:19
@mehmetkemalbayer Sorry to not respond. The issue didn't reproduce for me. To make sure, would you check wheather you can get desktop notifications in Chrome?

**Comment by jasonblais** [comment] 2017-01-17 15:15
Hey @mehmetkemalbayer, are you able to reproduce the issue on a browser as well?

**Comment by mehmetkemalbayer** [comment] 2017-01-18 08:51
Hi, @jasonblais, @yuya-oc 
Sorry for delay. It is the same. I can see little asterisk beside favicon but no notification is shown.
I think the problem is about my companies network rules. The problem is why some of my colleagues can see the notification.

**Comment by jasonblais** [comment] 2017-01-19 14:03
Thanks @mehmetkemalbayer for the reply,

Since it doesn't seem to be a defect with the desktop app itself, would you like to create a forum post in [Mattermost Troubleshooting forums](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum)? There are more visitors on that page and you'll get a faster response.

[Here are a few tips on how to use the forum](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum/150.

**Comment by jasonblais** [comment] 2017-03-22 21:19
I'll close the issue for now since it's not specific to the desktop app

If you're still experiencing the same issue, I encourage you to post in our [Mattermost Troubleshooting forums](https://forum.mattermost.org/t/how-to-use-the-troubleshooting-forum) which has more visitors that can better help you with it

**Closed by jasonblais** 2017-03-22 21:19 UTC
Labels: More Information Needed, Server Side

**Comment by mehmetkemalbayer** [comment] 2017-03-29 07:19
@jasonblais I solved the issue. The problem was corporate firewall. It was blocking some of the websocket packages. In short, there is no problem about application.

**Comment by jasonblais** [comment] 2017-03-29 11:51
@mehmetkemalbayer I'm glad to hear your issue got resolved!
