### ISSUE TITLE
After upgrade to version 5.1.0: emoji embedded in text are blurred, singleton emoji are sharp.

### ISSUE THREAD

**Issue by oGkgN** [mattermost/desktop#2145] opened 2022-06-01 09:58 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
After upgrade to version 5.1.0: emoji embedded in text are blurred, singleton emoji are sharp.

**Environment**
- Operating System: Ubuntu 20.04
- Mattermost Desktop App version: 5.1.0 
- Mattermost Server version: 6.5.0 

**Steps to reproduce**
Simply use the desktop client and read/write a message containing emoji.

**Expected behavior**
All emoji (especially emoji embedded in text) should render sharp, as they did before the upgrade to 5.1 (from some version 4.?).

**Observed behavior**
Only singleton emoji are rendered sharp. See: ![emoji](https://user-images.githubusercontent.com/7106555/171378833-974fa63b-2f96-4a99-966b-50ebd17f4a54.png)

**Possible fixes**
Unknown.

**Comment by devinbinnie** [comment] 2022-06-13 13:56
This is likely an issue with the Chromium render on Linux with Electron, will have to investigate to see if we can do anything about it ourselves.

**Comment by devinbinnie** [comment] 2022-07-08 13:55
Opening this up to anyone who can reproduce it and might be able to fix it.

@oGkgN One more thing we could try: the latest nightly build from [here](https://community.mattermost.com/core/channels/desktop-builds), it's using Electron v19.

**Comment by boobiq** [comment] 2022-07-12 15:58
I confirm this happening on 5.1.1 macOS desktop app, at first I thought I just don't see that good anymore :)

![image](https://user-images.githubusercontent.com/429225/178537372-b6786830-1b18-4eef-a5bd-5c13096d7950.png)

Also it looks like links previews are blurry too, I can't be sure because have nothing to compare it with but I don't remember it that way before.

![image](https://user-images.githubusercontent.com/429225/178537774-5429a8ce-6048-4c47-a03f-47565743ae3e.png)

**Comment by devinbinnie** [comment] 2022-07-25 13:38
@MHeymann @oGkgN Can you try the latest nightly build from [here](https://community.mattermost.com/core/channels/desktop-builds)? It might be fixed in an Electron upgrade.

**Comment by Elnora** [comment] 2022-08-22 13:53
I have this issue too, only in the client, not in the browser.

**Comment by j-schultz** [comment] 2022-10-21 14:43
This is also still happening for me on the Windows desktop client, version 5.1.1.

![image](https://user-images.githubusercontent.com/46443117/197223166-de35f970-8d15-456a-a897-0a82b319ed2f.png)

**Comment by j-schultz** [comment] 2022-11-02 08:18
Appears to be fixed in 5.2.0 desktop client for me.

**Comment by oGkgN** [comment] 2022-11-03 10:59
> Appears to be fixed in 5.2.0 desktop client for me.

Same for me! After upgrading to 5.2.0 desktop client on ubuntu, embedded emoji are sharp again (singletons too).

**Closed** 2022-11-03 12:54 UTC
Labels: Type/Bug, Help Wanted, Linux, Up For Grabs
