### ISSUE TITLE
Notifications do not stay in notification center

### ISSUE THREAD

**Issue by esethna** [mattermost/desktop#539] opened 2017-05-23 17:39 UTC
*Updated May 23, 2018:*

Jira ticket: https://mattermost.atlassian.net/browse/MM-14096

1 - MAC:

See GIF. Desktop notifications appear in the notification center only for the duration of the desktop notification.

Expected:
Notification stays in notification center until the notification is read.

![may-16-2017 17-05-06](https://cloud.githubusercontent.com/assets/14333569/26367599/6a16ffb4-3fac-11e7-823c-b6f5eeb6dc7a.gif)

2 - LINUX GNOME SHELL: See further discussion at https://github.com/mattermost/desktop/issues/810

**Summary**
When a Mattermost desktop app notifications comes through while Mattermost is in the background, no dot or notification is added to the Gnome notifications area (i.e. the pop-up when you click the date/time at the top of the screen).

**Steps to reproduce**
- Pop!_OS (`$ uname`: `Linux pop-os 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)
- Mattermost Desktop App version `4.0.1`
- Mattermost Server version `4.0.0 (4.0.1)`

- Open Mattermost and login to a server.
- Focus some other program to put Mattermost in the background.
- Receive a notification from Mattermost.

**Expected behavior**
There should be a dot next to the date/time and, when clicked, the notifications popup should have a notification.

**Observed behavior**
There is not dot nor notifications in the pop-up.

![screenshot from 2018-05-21 12-25-30](https://user-images.githubusercontent.com/133786/40320815-8728af9e-5cf2-11e8-82ab-2e3c50d4f2cc.png)

**Comment by jasonblais** [comment] 2017-05-23 17:44
Reproduce on Windows as well

**Comment by yuya-oc** [comment] 2017-05-24 10:31
Related: #304

**Comment by jasonblais** [comment] 2017-05-24 12:23
Is it an issue on Electron side then?

The app notifications stay in the notification center in Slack though.

**Comment by yuya-oc** [comment] 2017-05-24 12:44
Not issue for electron. The problem is caused by Electron's implementation (not bug) and mattermost's notification duration.

Slack uses alternative native modules, [electron-windows-notifications](https://github.com/felixrieseberg/electron-windows-notifications) and [node-mac-notifier](https://github.com/charliehess/node-mac-notifier). Of course we can use it, but need to ignore duration setting to prevent disappearing.

**Comment by Steinblock** [comment] 2017-07-20 06:18
First of all, the current documentation for `Account settings > Notifications > Notification duration` could be modified to include `Notifications in the mattermost app can only stay on screen for a maximum of 10 seconds`

![image](https://user-images.githubusercontent.com/6850324/28403070-4cf33016-6d23-11e7-8fd7-cfbda1252f10.png)

I would like to see the mattermost app to use `electron-windows-notification` as @yuya-oc suggested.
Event the electron team suggests it: https://electron.atom.io/docs/tutorial/notifications/

> Advanced Notifications
> Later versions of Windows allow for advanced notifications, with custom templates, images, and other flexible elements. To send those notifications (from either the main process or the renderer process), use the userland module electron-windows-notifications, which uses native Node addons to send ToastNotification and TileNotification objects.

The dissapearing notifications are the main reason I still use mattermost as a desktop app inside chrome.

**Comment by kayzee** [comment] 2018-07-20 14:37
I'm still seeing this issue on MacOS. Has it lost all priority?

**Comment by cpanato** [comment] 2018-08-30 09:18
@yuya-oc @jasonblais there any plans to use  node-mac-notifier and the other notifiers to other platforms?
asking that because will be good to add the close button and/or the reply in the notification message.

**Comment by akdj** [comment] 2019-01-03 14:21
issue stiil present on GNOME 3

**Comment by amyblais** [comment] 2019-02-11 16:16
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14096

**Comment by mismeniet** [comment] 2019-03-07 09:58
Yeah, having the notifications stay longer (or customizable) and in the notification center seems to be key for not missing messages.

**Comment by jannnik** [comment] 2019-03-07 13:02
My team is also displeased with the disappearing notifications. Are there any plans when this will be fixed?

**Comment by mmuth** [comment] 2019-03-07 14:36
Same here

**Comment by foxylion** [comment] 2019-03-07 14:58
I've also problems with this. I often miss messages because the notification disapears to quickly.

**Comment by devdev-dev** [comment] 2019-03-07 15:40
🔔 Please make them more persistent in the notification centre.

**Comment by benugel** [comment] 2019-03-07 17:10
> My team is also displeased with the disappearing notifications. Are there any plans when this will be fixed?

Also I don't like it, I often miss messages.

**Comment by johnnyasantoss** [comment] 2019-08-23 09:49
I didn't check the code but from the GIFs I can guess that the expiration time is being set on Linux/Mac and that's why the notifications are dismissed. If you want to show the notifications for a small period and still be able to keep them in the notification deck, it needs to use expiration `-1` and set some hints that are described [here](https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html#hints) (I have no idea how this is implemented in electron)

**Comment by anassahmed** [comment] 2019-11-07 08:03
Can we disable withdrawing notifications all together?

**Comment by devinbinnie** [comment] 2021-12-09 19:03
No longer valid, works correctly on macOS

**Closed by devinbinnie** 2021-12-09 19:03 UTC
Labels: Help Wanted, All Platforms, Feature, Hacktoberfest, Up For Grabs
