### ISSUE TITLE
Unable to choose spelling languages in 4.7

### ISSUE THREAD

**Issue by tmu-sprd** [mattermost/desktop#1636] opened 2021-06-24 14:56 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
With spell checking enabled, only the system language is being checked for spelling. Other languages can't be checked anymore, even when dictionaries for other languages are installed and working. The context menu "Spelling Languages" available in 4.6.2 isn't there in 4.7.0 anymore. The environment variable DICTIONARY consumed by hunspell isn't evaluated.

**Environment**
- Operating System: Gentoo Linux
- Mattermost Desktop App version: 4.7.0 
- Mattermost Server version: 5.35.1 

**Steps to reproduce**
Use mattermost-desktop in version 4.7.0. Write a message in a language other than system language.

**Expected behavior**
Correctly spelled words in languages different from system language are not marked as misspelled.

**Observed behavior**
Correctly spelled words in languages different from system language are marked as misspelled.

In 4.6.2:
![image](https://user-images.githubusercontent.com/33454479/123283768-fbc0b880-d50b-11eb-86ca-409c3743c8c9.png)

In 4.7.0:
![image](https://user-images.githubusercontent.com/33454479/123284673-ba7cd880-d50c-11eb-9107-e26f581edc87.png)

```
~ $ echo $DICTIONARY    
en_US,de_DE

~ $ echo "Hallo Hello" | hunspell
Hunspell 1.7.0
*
*

~ $ locale
LANG=en_US.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Possible fixes**
Either re-introduce the possibility to change spelling languages per context menu as in versions <4.7 or respect the environment variable DICTIONARY for enabled dictionaries of hunspell or provide a different way to select available spelling languages.

**Comment by amyblais** [comment] 2021-06-24 15:02
@Willyfrog @jgilliam17 Does this repro for you?

**Comment by Willyfrog** [comment] 2021-06-24 15:07
with 4.7 we default to system language as we are now using the system's dictionary.

we want to add the option to select different languages in the future (see [MM-33112](https://mattermost.atlassian.net/browse/MM-33112) ) althought that will only be possible in windows and linux due to electron limitations. The plan for that ticket is to be made help wanted (which will happen next week)

**Comment by stefangr** [comment] 2021-06-30 06:33
This is a major loss of functionality for users in a multi-lingual environment.

In our (Dutch) company with English speaking colleagues for example, we have conversations in Dutch and English channels.
Before 4.7, I could switch the spelling for the text area when needed.

Now I must change the system language to have the correct spelling check??

**Comment by Jajcus** [comment] 2021-07-01 06:37
Yes, this change is a serious regression. People do use multiple languages on regular basis, often at work. Having spell checking available only for one, arbitrary selected in the OS is just wrong.
If anything was to be changed is to preserve language setting for a specific channel – that would be useful.

**Comment by facundobatista** [comment] 2021-07-09 11:30
> with 4.7 we default to system language as we are now using the system's dictionary.

How are you detecting the "system language"? Which env var are you using for this? IOW, what we need to change for the mattermost process for it to select the language we want? (as a workaround).

Thanks!!

**Comment by Willyfrog** [comment] 2021-07-09 13:26
From [electron's docs](https://www.electronjs.org/docs/tutorial/spellchecker#how-to-set-the-languages-the-spellchecker-uses):

> By default the spellchecker will enable the language matching the current OS locale.

**Comment by facundobatista** [comment] 2021-07-09 13:40
But "the locale" is a complex thing:

```
$ locale
LANG=es_AR.UTF-8
LANGUAGE=es_AR:es
LC_CTYPE="es_AR.UTF-8"
LC_NUMERIC="es_AR.UTF-8"
LC_TIME="es_AR.UTF-8"
LC_COLLATE="es_AR.UTF-8"
LC_MONETARY="es_AR.UTF-8"
LC_MESSAGES="es_AR.UTF-8"
LC_PAPER="es_AR.UTF-8"
LC_NAME="es_AR.UTF-8"
LC_ADDRESS="es_AR.UTF-8"
LC_TELEPHONE="es_AR.UTF-8"
LC_MEASUREMENT="es_AR.UTF-8"
LC_IDENTIFICATION="es_AR.UTF-8"
LC_ALL=
```

So, it considers `LC_ALL`? `LANG`? `LANGUAGE`? Etc...

**Comment by jrueb** [comment] 2021-08-09 11:50
> with 4.7 we default to system language as we are now using the system's dictionary.
> 
> we want to add the option to select different languages in the future (see [MM-33112](https://mattermost.atlassian.net/browse/MM-33112) ) althought that will only be possible in windows and linux due to electron limitations. The plan for that ticket is to be made help wanted (which will happen next week)

It looks like MM-33112 is proposing to reimplement this as an item in the preferences. This is a really bad idea, because changing the language is normally done constantly in case you aren't a single-language user. It was correct to implement this as a context menu item in the past.
Anyway, this issue breaks the entire spell checking feature. As a hotfix can the spell checking be reverted to the 4.6 state until there is a fix?

**Comment by gabrielebndn** [comment] 2021-09-15 20:25
I confirm this is a huge regression for me. In a multilingual environment such as mine, I am constantly switching between English French and Italian. Without spell check (worse, with spell check stuck to English) it become very difficult. So difficult I reverted to 4.6.2

**Comment by facundobatista** [comment] 2021-09-16 09:24
Hello @Willyfrog , thanks for the info. Do you have info about how it will be handled? Thanks!

**Comment by Willyfrog** [comment] 2021-09-16 09:25
Same as chrome does, you specify a list of languages and it will try to figure out the right one

**Comment by gabrielebndn** [comment] 2021-12-02 20:20
Hi @Willyfrog, thanks for your kind answer, the planned solution does look nice indeed, I'll follow this closely

**Comment by devinbinnie** [comment] 2021-12-09 22:12
Closing as this feature is now present in v5.0.2 in the Settings modal.

**Closed by devinbinnie** 2021-12-09 22:12 UTC
