### ISSUE TITLE
Desktop notifications don't show up, if the window has been minimized when it was INACTIVE.

### ISSUE THREAD

**Issue by lip-d** [mattermost/desktop#522] opened 2017-04-30 10:18 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Notification balloon doesn't show up, if the window has been minimized when it was INACTIVE.

**Steps to reproduce**
1. Select any channel for this test (We call it "channel A" for simplicity)
2. Make the app window inactive (ex. by clicking on the other window)
3. Click on the "minimize" button on the title bar of Mattermost window.
4. Send a message to the channel A from the other account.
  -> Notification balloon does not show up.

Note: The same issue occurs when you click on "close" button instead of "minimize". 

Tested on:
- Windows 7 32bit
- Mattermost Desktop 3.6.0 
- Mattermost Server 3.8.0

**Expected behavior**
Notification balloon shows up at the task tray.

**Observed behavior**
Notification balloon does not show up.

**Possible fixes**
This might be related to:
desktop/src/main/mainWindow.js: line 88
" window.blur()" works well when the window is active, but not when the window is inactive.
I'm just guessing...

**Comment by yuya-oc** [comment] 2017-04-30 13:11
Reproduced for me on Windows 10. And not on Mac. The step looks exact.

I believe the line 88 is not related because only closing calls the line.

@jasonblais Please let me confirm. On v3.8.0 server, does a new message show a desktop notification when the window is active and the message arrives to the current channel?

**Comment by jasonblais** [comment] 2017-04-30 23:18
Thanks for the report @lip-d! Also able to reproduce on Windows 10 Home.

@yuya-oc In Mattermost server v3.6.0 and later , if the window is active (e.g. if you're viewing channel A), then no desktop notification is sent. 

So it sounds like the webview might become active after clicking on the minimize/close buttons as you say.

**Comment by yuya-oc** [comment] 2017-06-06 14:20
Closed via #545

**Closed by yuya-oc** 2017-06-06 14:20 UTC
Labels: Bug, Help Wanted, Windows

**Comment by lip-d** [comment] 2017-06-07 11:27
@yuya-oc and @jasonblais.
Thanks a lot! Really appreciated.
