### ISSUE TITLE
"Failed to load the URL" "error code -324"

### ISSUE THREAD

**Issue by RainFlying** [mattermost/desktop#113] opened 2016-04-20 07:43 UTC
[After]([url](url)) added team infomation, mattermost desktop showed "Failed to load the URL", "error code -324".
The client version is 1.1.1 for Mac, the OS is OS X 10.11.4
The server is version 2.2.0 running on a CentOS 7 machine with Nginx 1.8.1.
Everything works fine in the browser.
Also tried mattermost desktop for Windows, the same error but with different error code.

<img width="802" alt="screenshot 2016-04-20 15 42 29" src="https://cloud.githubusercontent.com/assets/507678/14666917/cb7d55a0-070e-11e6-83b7-e68819afe460.png">

**Comment by yuya-oc** [comment] 2016-04-20 14:00
`-324` means "The server closed the connection without sending any data." (https://src.chromium.org/svn/trunk/src/net/base/net_error_list.h)

Could you try inserting this code at `resources/app/browser/index.js:L295`?

```
if (e.errorCode === -324) {
  // The server closed the connection without sending any data. (due to user action).
  return;
}
```

Just curious, does your nginx use any redirect? (e.g. `http://` to `https://`)

**Comment by axelrose** [comment] 2016-04-22 13:44
I get -324 from a different setup (starting with Mattermost.app/Contents/MacOS/Electron --proxy-server=127.0.0.1:8643) but the nginx server is definetely using redirects from http to https.

**Comment by yuya-oc** [comment] 2016-04-22 14:09
@axelrose Does your configuration use `http://`? If it is, please try `https://` configuration.

**Comment by axelrose** [comment] 2016-04-22 14:24
Thanks for responding. My current setting uses `https` already.
I'm building my own SOCKS proxy with `ssh -p 443 user@target -D 8643`. This works nicely in Firefox.

**Comment by yuya-oc** [comment] 2016-04-22 14:56
Reproduced with `ssh -D 9000 user@ssh-server` and `Mattermost.exe --proxy-server=127.0.0.1:9000`. Thanks.

However I'm not familiar at SOCKS proxy. The proxy probably closes connection at some condition. Possibly need to capture packets.

@axelrose BTW, did you try with Chrome?

**Comment by yuya-oc** [comment] 2016-04-22 15:03
@RainFlying Do you use any proxies?

**Comment by axelrose** [comment] 2016-04-22 15:06
Great to hear you already found it!!
I tried with Chrome and my homemade SOCKS proxy -- it works fine with it.
Please let me know if I you need more.

**Comment by yuya-oc** [comment] 2016-05-03 12:57
@axelrose Could you try the option like this: `--proxy-server=socks5://127.0.0.1:8643`?

**Comment by axelrose** [comment] 2016-05-03 14:47
This works well! Thanks for your help.
I'm starting the client now with ```mattermost-desktop-1.1.1-osx/Mattermost.app/Contents/MacOS/Electron --proxy-server=socks5://127.0.0.1:864```

**Comment by jasonblais** [comment] 2016-06-23 16:42
Is any further work needed here @yuya-oc?

**Comment by yuya-oc** [comment] 2016-06-23 23:23
No. But I'm not sure about the original problem of this issue.

**Comment by jasonblais** [comment] 2016-06-27 01:10
Thanks - closing for now, since the original reporter hasn't come back. 

We can open a new issue if the issue reappears

**Closed by jasonblais** 2016-06-27 01:10 UTC
Labels: more information needed
