### ISSUE TITLE
Desktop app on Mac plays notification sound even when disabled

### ISSUE THREAD

**Issue by vasimi** [mattermost/desktop#2090] opened 2022-05-09 10:30 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues). – **not applicable**
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Desktop app plays notification sounds on Mac even if notification sounds are disabled system-wide or for the Mattermost app.

**Environment**
- Operating System: macOS 
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: 6.6.1

**Steps to reproduce**
receive a notification

**Expected behavior**
if do not disturb is turned on or notification sounds are turned off for Mattermost, no sound is played

**Observed behavior**
sound plays even if notification sounds are turned off in the system

**Comment by devinbinnie** [comment] 2022-05-09 13:40
Thanks for the report, this unfortunately requires a native Node module to work correctly, which we do not support in our build process currently.

We will be supporting this in the near future however!

**Comment by RichieB2B** [comment] 2022-09-13 13:17
This is a really annoying bug. How near in the future can this be fixed?

**Comment by devinbinnie** [comment] 2022-09-13 13:22
This might now be fixed with the addition of the `macos-notification-state` module. However, it will only work outside of the MAS build due to Apple's App Sandbox restrictions. You can try it for yourself in the nightly buillds available here: https://community.mattermost.com/core/channels/desktop-builds

**Comment by RichieB2B** [comment] 2022-09-13 14:32
Wow, that was fast! I can confirm that `mattermost-desktop-5.2.0-nightly.20220912-mac-m1` fixes this issue.

**Comment by RichieB2B** [comment] 2022-09-13 14:44
For the MAS issue, looks like this can be fixed: https://github.com/felixrieseberg/macos-notification-state/pull/27

**Comment by devinbinnie** [comment] 2024-09-27 15:33
This is fixed here: https://github.com/mattermost/desktop/pull/2972
Forgot to close this issue.

**Closed by devinbinnie** 2024-09-27 15:33 UTC
Labels: Type/Bug, MacOS, Blocked
