### ISSUE TITLE
Client constantly hangs in random moments

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [mattermost/desktop#494] opened 2017-03-27 08:14 UTC
It is not possible to predict when it will hang next time. But look like mattermost client have dead thread lock somewhere . Have same behavior at least on 3 Different computers (1 PC Windows 10 PRO and 2 PC Windows 10 home). Possible fix only over kill mattermost client processes in Task Mananger and restart. In most cases it happens in moment click trey icon during conversation.

**Comment by jasonblais** [comment] 2017-03-27 13:36
Thanks @jpVm5jYYRE1VIKL for the report, few questions that come to mind,

1. Which Mattermost server version are you using?
2. Which Mattermost desktop version are you using?
3. Does it reproduce after accessing a particular channel/team?
4. Do you see a CPU spike during this time?

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-03-27 14:38
Sorry that forced to ask extra questions. 
1. Server was 3.6.2
2. Client was 3.5.0 
3. Nope completely random. Sometimes i just click on window and understand that it hanged. 
4. It is hard to detect because all issues happens on powerfull computers (core i7) i not feel cpu spike. 
Now i upgraded server to version 3.7.3 and client to version 3.6.0 to see that happens.

**Comment by jasonblais** [comment] 2017-03-27 14:45
Awesome, thanks! Let us know if the issue reproduces on the latest server/client version

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-03-29 18:30
Small update to issue. Just now happened again. Issue is not real hanging. It is freeze for 1 - 2 minutes. During this time application GUI completely not respond. Cpu not have any spikes.  In task manager application not marked as not responding and not eat CPU. 
After 1 - 2 minutes application unfreeze itself and continue to work. Detected such behavior because started to search debugger to attach and suddenly found that application not hang anymore.  Issue happened with 3.7.3 server and 3.6.0 client.

**Comment by jasonblais** [comment] 2017-03-30 14:00
Thanks @jpVm5jYYRE1VIKL - how did you set up your Mattermost environment? 

Are you using any proxies?

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-03-30 14:05
Yes using. https://nginx -> http://mattermost:8065

**Comment by jasonblais** [comment] 2017-04-03 14:38
@yuya-oc is there any debugging available for the desktop app?

Someone else has the client freezing in Windows 10: https://github.com/mattermost/desktop/issues/347#issuecomment-291153639

**Comment by yuya-oc** [comment] 2017-04-03 15:38
> It is freeze for 1 - 2 minutes.

As far as reading the behavior, it sounds like a performance issue. (but it's also weird because CPU doesn't have spike...) The application consists of many processes like Chrome, so the process which @jpVm5jYYRE1VIKL had attached might not be appropriate.

I feel "Timeline" and "Profiles" tabs of developer tools (`Ctrl+Shift+I`) might make sense to measure the problem.
By executing `document.getElementById('mattermostView0').openDevTools()` in the console, it opens another console which is attached to a webview. It can inspect the inside of the webview.

If the problem happened in the main process, we need to follow [Electron's instruction](https://electron.atom.io/docs/tutorial/debugging-main-process/) for debugging.

**Comment by jasonblais** [comment] 2017-04-03 16:39
Thanks @yuya-oc 

@jpVm5jYYRE1VIKL Thank you for all your reports thus far, it's really helpful. Would you be open to help provide the information described above next time the issue occurs?

I'm wondering if it could be a memory issue on the app

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-04 17:10
Yes of course when next time it happen all try to provide as more as possible information. 
it is really hard to catch because of random nature.

**Comment by jasonblais** [comment] 2017-04-04 22:35
Thank  you @jpVm5jYYRE1VIKL, really appreciate it. Would getting the logs for 1-2 minutes after the app is accessible again be helpful @yuya-oc?

**Comment by yuya-oc** [comment] 2017-04-06 15:12
> mattermost window completely not respond

Does "window" include the title bar? Or only content area (webview) of the window? Once I had met a case webview freezes on Mac, but its window frame could respond.

> Would getting the logs for 1-2 minutes after the app is accessible again be helpful @yuya-oc?

Yeah, for now I'm not sure what's actually happening in the app. So need to know what appears.

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-10 07:42
Basically exist 2 different types of freeze. One person complained that she see black mattermost window . I personally seen just simple freeze with title bar. But not responsible title bar. I cannot use any controls on it during time of freeze.  Last week was without freezes. I continue monitoring.

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-10 20:52
Update: Hm look like nothing to copy from console log because look like it empty. 
Added extra sympthom. 
Application freezed this time in following conditions. 
Application was in tray. Appeared pop up incoming message , I clicked immediately on pop up . Appeared application window which and it freeze. After some time application unfreeze i immedeately started developers tools and looked on console last messages i see was 2 hours ago .

**Comment by jasonblais** [comment] 2017-04-11 20:53
Thanks @jpVm5jYYRE1VIKL for the continued follow-up. Really appreciate all the information. 

For the "black screen" issue, there are a few troubleshooting steps in our docs: https://docs.mattermost.com/install/desktop.html#troubleshooting. In particular,
 - First try to clear cache and reload the app from View > Clear Cache and Reload or by pressing CTRL/CMD+SHIFT+R.
 - Next, quit the app and restart it to see if the issue clears.

For the client freeze issue --> I just tried clicking on a desktop notification while the app was minimized to the tray, but I wasn't able to reproduce it so far. I was on a light load though (not much else on my machine)

Did the post you receive contain any attachments (files, GIFs) or link previews? Does the channel itself have mostly text-based messages, or does it have GIFs / link previews to generate? We've heard performance issues before about channels containing lots of GIFs (see https://github.com/mattermost/desktop/issues/215 for an example).

anything else @yuya-oc that could come to mind?

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-14 13:55
channel not have attachd files at all. Have some link and pictures links (i guess they cached) in channel line. 
Channels mostly text . 98 % text , 1.5 % links on pictures and 0.5 % just web links .

**Comment by yuya-oc** [comment] 2017-04-15 11:08
While a window is closed into the tray icon, CPU usage is limited to reduce power. But I'm not sure whether it impacts to app's stability.

> Can it be binded with Meteor itself ? O may be collaboration meteor and windows internals ? may be embedded browser ?

Sorry, I'm not sure what you mean. The application is build with Electron, and its webview is used to load webapp of Mattermost server. So it works like embedded web browser.

**Comment by yuya-oc** [comment] 2017-04-15 11:15
On Windows, "not responding" means that the native message loop is blocked due to some reason (like too heavy load). So I feel the matter is not webapp. But...I'm not sure the reason. I feel such a heavy load is not existing excepting GC.

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-16 18:01
Sorry my mistake. Of course i meant Electron.

**Comment by yuya-oc** [comment] 2017-04-17 15:07
Please use [`--disable-renderer-backgrounding`](https://electron.atom.io/docs/api/chrome-command-line-switches/#disable-renderer-backgrounding) from command line. Otherwise, need to use [`webPreferences.backgroundThrottling: false`](https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions) by modifying source code.

**Comment by jasonblais** [comment] 2017-04-23 18:53
@jpVm5jYYRE1VIKL  @yuya-oc 

We got a couple of reports about the app crashing due to high memory usage.

Could this be the reason why the app is constantly crashing for you @jpVm5jYYRE1VIKL? 

Anything we can do to reduce the issue @yuya-oc?

**Comment by jasonblais** [comment] 2017-04-23 18:53
^@jnugh also pinging you in case you had any thoughts about the high memory usage, I think we discussed earlier about it a little.

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-24 07:45
@jasonblais 
Nope not think so. All affected PCs have a lot of RAM. Pc which most affected have 32G ram , 
For now i starting to think that issue connected with usage same credentials on 2 or more workplaces.
@yuya-oc  
for sure --disable-renderer-backgrounding not solved issue. But feels freeze time bit decreased. Not 100 % sure. Still testing.

**Comment by yuya-oc** [comment] 2017-04-24 13:29
@jpVm5jYYRE1VIKL Thanks! Assuming that, I feel there are two possible cases.

A. When fetching latest messages after PC is woken from sleep.
B. When there are two clients and they have too different states.

I didn't notice the checklist doesn't exist in your first post. To make sure, did you also test the problem with Chrome?

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-24 13:33
@yuya-oc 
Nope of course i not tested with browsers. I only use standalone desktop clients everywhere.

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-26 21:28
Update: I tested with opened Chrome and loggen on from Chrome to mattermost server and Mattermost desktop client on same PC . Messaging in Chrome working fine , messagin in mattermost freeze as usual.

**Comment by jasonblais** [comment] 2017-04-26 21:55
Thanks @jpVm5jYYRE1VIKL, looks like there's something in the desktop app causing it

Even though it was mentioned that memory usage shouldn't be an issue, I've been following both CPU and memory usage of the app in the last couple of days and have noticed the following (recorded via Task Manager):

 - when starting the desktop app, the memory usage is generally low: 25MB for the app, < 200MB if you add all the background processes from the Task Manager that are related to the Mattermost app (it's kind of high in my opinion, but it shouldn't be causing issues)
 - after a few days of usage: 37MB for the app (still okay), almost 1GB if you add all the background processes

So the memory usage does accumulate quite significantly over time, and that could cause general slowness, perhaps even a potential freeze if an action spikes up the memory usage a lot. For instance, I'm seeing large swings in memory usage (up to 300MB) when I switch a channel or perform other simple actions.

With regards to system info: Running Windows 10 on two Mattermost instances, where only one of them is active (the other has a few messages per day)

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-04-27 17:16
Extra update. I started sysinternals process monitor and found one strange issue 
```
19:05:06.8628355	Mattermost.exe	8596	UnlockFileSingle	C:\Users\user1\AppData\Roaming\Mattermost\Cookies	SUCCESS	Offset: 1,073,741,826, Length: 510
19:05:06.8629183	Mattermost.exe	8596	LockFile	C:\Users\user1\AppData\Roaming\Mattermost\Cookies	SUCCESS	Exclusive: False, Offset: 1,073,741,826, Length: 510, Fail Immediately: True
19:05:06.8629834	Mattermost.exe	8596	UnlockFileSingle	C:\Users\user1\AppData\Roaming\Mattermost\Cookies	SUCCESS	Offset: 1,073,741,825, Length: 1
19:05:06.8630391	Mattermost.exe	8596	UnlockFileSingle	C:\Users\user1\AppData\Roaming\Mattermost\Cookies	SUCCESS	Offset: 1,073,741,824, Length: 1
19:05:06.8630974	Mattermost.exe	8596	UnlockFileSingle	C:\Users\user1\AppData\Roaming\Mattermost\Cookies	SUCCESS	Offset: 1,073,741,826, Length: 510

```
Offset: 1,073,741,824 looks bit strange

**Comment by jasonblais** [comment] 2017-04-28 12:10
@yuya-oc @jpVm5jYYRE1VIKL 

there's a report where a user is able to consistently reproduce the issue when the application is minimized and they receive notifications

https://github.com/mattermost/desktop/issues/520

The issue no longer occurs after disabling desktop notifications.

**Comment by jnugh** [comment] 2017-05-02 16:41
Something similar occurred to me, I'm not sure if it is 100% related but it kinda looks like it is.
I have an STRACE showing a deadlock. I'm building electron right now to get some debug symbols (and maybe a better stack to identify the root cause...)
[mattermost-strace.txt](https://github.com/mattermost/desktop/files/971134/mattermost-strace.txt)

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-05-09 16:28
I think issue can be merged. For now disable notifications solved issue.

**Comment by jasonblais** [comment] 2017-05-09 16:59
@yuya-oc is there anything we can do about the notifications issue? It appears to be the root cause for freezing the Windows 10 client in #494 and #520

**Comment by yuya-oc** [comment] 2017-05-10 13:57
Assuming that, we need to know what part is wrong in the notifications. i.e. Electron itself or our injection code for notifications. So I prepared two versions to check that. But unfortunately I can't reproduce the problem yet.

- Plain Electron's notification: https://circleci.com/gh/yuya-oc/desktop/247#artifacts
    - Note: When clicking notifications, the window is not activated due to Electron's spec.
- Refactoring with class syntax: https://circleci.com/gh/yuya-oc/desktop/246#artifacts

@jpVm5jYYRE1VIKL @mdementev Wondering if you could test with these builds. You can download them from CircleCI by expanding `circle-artifacts.xxxxxxx/`.

<img width="799" alt="circleci_artifacts" src="https://cloud.githubusercontent.com/assets/1412057/25902090/7dfcfbce-35d3-11e7-9a22-8a5c43a79303.png">

**Comment by jasonblais** [comment] 2017-05-19 12:53
@jpVm5jYYRE1VIKL @mdementev Would either of you like to try if the app keeps freezing on the above test builds linked by @yuya-oc above?

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-05-22 07:28
For now i use workaround "disable notifications at all". Test build cannot test because as for me it look like complex. If you add this change to next release of course i ll report is change fixed or not.

**Comment by yuya-oc** [comment] 2017-05-22 13:30
I see. The installer was not code-signed and downloaded from internet, so Windows defender would prevent it at the first time. It's understandable.

@jasonblais To get @jpVm5jYYRE1VIKL's feedback and refactoring, I will create a PR. Would you check it?

**Comment by jasonblais** [comment] 2017-05-22 13:33
@yuya-oc I'm happy to test it, but I haven't been able to reproduce it either.. I actually downloaded the test build from https://circleci.com/gh/yuya-oc/desktop/246#artifacts and haven't hit any issues.

**Comment by yuya-oc** [comment] 2017-05-22 13:34
Okay, so may I push to master to add to next release?

**Comment by jasonblais** [comment] 2017-05-22 13:36
Yeah, I'm okay with that.

How confident are you about the fix @yuya-oc? If we have to cut a 3.7.1 dot release for https://github.com/mattermost/desktop/issues/537 before Mattermost 3.10 (depends if it's a bug on the platform repo or desktop repo), we could consider including this fix in the dot release as well.

**Comment by yuya-oc** [comment] 2017-05-22 13:40
Hmm...I'm not too confidence... But if there is 3.7.1, I agree to include it.

**Comment by yuya-oc** [comment] 2017-05-31 13:51
@jasonblais For now, we don't release v3.7.1, so I would like to merge https://circleci.com/gh/yuya-oc/desktop/246#artifacts (Refactoring with class syntax) into master. Any thoughts?

**Comment by yuya-oc** [comment] 2017-05-31 14:08
Merged at 0839e71

**Comment by jasonblais** [comment] 2017-06-02 21:30
@yuya-oc My machine has been slower after the most recent Windows update and I've noticed the app freezing for a few seconds when I get a desktop notification (only sometimes).

Is this still the most recent artifact to test the fix you merged? If so, I'll give it a try and see if it helps. https://circleci.com/gh/yuya-oc/desktop/246#artifacts

**Comment by yuya-oc** [comment] 2017-06-03 05:28
@jasonblais Yes, please use it. The master branch updated electron though, I think it's not related to this issue.

**Comment by jasonblais** [comment] 2017-06-03 19:58
Sounds good, I'll test it out next week to see if I see a difference.

**Comment by jasonblais** [comment] 2017-06-27 21:10
@yuya-oc FYI, I don't think the fix helped too much, unfortunately... I still experienced slowness with the test build but when I disabled desktop notifications today, I haven't had any issues. The freezing was worse on v3.7 though (I think, at least when I tested this morning).

I'm able to reproduce it after using the app for a few hours, and it starts to happen around mid-day during my working hours. 

When you're back, I'd be happy to provide any info if needed..haven't really noticed any patterns and the console shows no errors.

**Comment by jasonblais** [comment] 2017-06-29 14:54
^update on this: It doesn't seem to be related to desktop notifications for me.

It seems to be happening while I'm receiving an unread -- or it's something else. Will investigate further..

**Comment by jasonblais** [comment] 2017-08-18 15:32
Closed via #563

**Closed by jasonblais** 2017-08-18 15:32 UTC
Labels: More Information Needed

**Comment by jasonblais** [comment] 2017-10-20 15:04
@jpVm5jYYRE1VIKL We released v3.7.1 of the desktop app which included a fix for this issue.

It would be great if you could help download the app and let us know if you're still experiencing problems with the client freezing https://about.mattermost.com/download/#mattermostApps

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-10-23 18:41
Problem Gone for me.

**Comment by jasonblais** [comment] 2017-10-23 19:24
Sweet, glad to hear :)
