### ISSUE TITLE
Jumping window location

### ISSUE THREAD

**Issue by jshackatpair** [mattermost/desktop#1225] opened 2020-03-04 21:34 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

IF: I move the application window, and subsequently minimize it
THEN: when I restore the application window, it shows up in the top left corner of my workspace desktop and not at the location where I put it.

**Environment**
- Operating System: Ubuntu Linux 18.04
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.19.1

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

**Possible fixes**

**Comment by SoerenHenning** [comment] 2020-03-11 09:32
Observing the same issue on my setup:

* Operating System: Ubuntu Linux 18.04.04
* Mattermost Desktop App version: 4.4.0
* Mattermost Server version: 5.20.1

**Comment by amyblais** [comment] 2020-03-11 13:38
Ticket created here: https://mattermost.atlassian.net/browse/MM-23195.

**Comment by heckert-epost** [comment] 2020-03-13 11:44
![Screenshot_20200313_115127](https://user-images.githubusercontent.com/51078317/76617981-bc917280-6527-11ea-9fae-52d362617094.png)
For me it jumps to the top-left corner of the combined screens, which is (as shown in the screenshot) above the visible area of my laptop's screen. This is severely annoying as moving the window somewhere else requires a complex interaction with the desktop environment (KDE in my case).

**Comment by Stypox** [comment] 2020-03-18 14:18
This seems to be duplicate of #1209

**Comment by amyblais** [comment] 2020-04-22 17:16
This is now fixed in v4.4.1 dot release,

**Closed by amyblais** 2020-04-22 17:16 UTC
