### ISSUE TITLE
Windows 10: window minimized on Monitor2, restores on Monitor1

### ISSUE THREAD

**Issue by ferceg** [mattermost/desktop#1209] opened 2020-02-25 14:17 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [*] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [*] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [*] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
After minimizing and restoring the window on secondary monitor, it jumps to primary monitor.

**Environment**
- Operating System: Window 10
- Mattermost Desktop App version: 4.4.0 
- Mattermost Server version: 5.17.1 

**Steps to reproduce**
Move MM window to secondary monitor. Minimize. Restore.

**Expected behavior**
It should restore where I left it.

**Observed behavior**
It restores on the primary monitor.

Multimonitor screen recording:
https://ibb.co/T2QT4Gn

**Possible fixes**

**Comment by amyblais** [comment] 2020-02-28 16:29
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22771.

**Comment by vectr0n** [comment] 2020-02-29 03:32
This is also a problem on Linux

**Comment by heckert-epost** [comment] 2020-03-13 10:58
I have additionally the issue that the restored window jumps to the location +0+0 (left top corner) of alle screens, and the screen height is calculated as the combined height of both screens (internal laptop screen is FHD (1920x1080) and external monitor has 1920x1200) and the laptop is aligned as seen in the screenshot, which means the position +0+0 is outside the laptop's screen. The client's title bar is inaccessible and moving the window requires a complicated interaction with the desktop environment (context menu in task bar, select sub-menu, select 'move window').
![Screenshot_20200313_115127](https://user-images.githubusercontent.com/51078317/76614631-c2378a00-6520-11ea-8cd3-e8445e4eac96.png)

(I can see that fixing this issue is likely more complicated than just keeping the window position at the time it gets minimized and applying these values to the restored window, as the geometry may have changed in the meantime (external display of laptop disconnected and so on...))

**Comment by pcornelissen** [comment] 2020-03-13 12:09
Happens on Mac as well

**Comment by amyblais** [comment] 2020-03-31 14:14
Closing as a duplicate of https://github.com/mattermost/desktop/issues/1225 as the Jira ticket for this issue was closed as a duplicate of the other Jira ticket opened for #1225.

**Closed by amyblais** 2020-03-31 14:14 UTC
