### ISSUE TITLE
Direct messages cause notification icons to appear on each team

### ISSUE THREAD

**Issue by jfperusse-bhvr** [mattermost/desktop#250] opened 2016-08-16 19:28 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

When receiving a direct message, a red notification icon is added to all tabs and can only be cleared by opening the message on each team.

#### Steps to reproduce

This is for the Windows Desktop Application version 1.3.0.

- Open the Windows Desktop Application and make sure you have joined more than one team (you should have multiple tabs in the application).
- Ask someone to send you a direct message.

#### Expected behavior

The direct message notification icon should be displayed on one team only (e.g. the main team on the server, or make this a user preference), or at least be cleared for all tabs when read on one of the teams.

#### Observed behavior

The direct message notification icon is displayed on all the teams. The user must open the message in each team for all notification icons to be cleared.

**Comment by yuya-oc** [comment] 2016-08-17 13:41
Duplicate of #160.

**Closed by yuya-oc** 2016-08-17 13:41 UTC
