### ISSUE TITLE
mac client throws exception when upload files 

### ISSUE THREAD

**Issue by brucewinger** [mattermost/desktop#87] opened 2016-03-18 08:07 UTC
When I try to upload files from mac client, it throws 'We received an unexpected status code from the server. (500)'.

**Comment by yuya-oc** [comment] 2016-03-20 15:44
Not reproduced on my Mac.
* OS X 10.11.3
* electron-mattermost 1.0.7
* Mattermost server 2.0.0


Please tell me about your environment. (see also [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md))

**Comment by jasonblais** [comment] 2016-07-13 00:58
Thanks @brucewinger for the report - I am closing this issue as 'cannot reproduce' for now. 

If you or someone else in the community is able to reproduce this issue, please let us know.

**Closed by jasonblais** 2016-07-13 00:58 UTC
Labels: more information needed
