### ISSUE TITLE
Merge request #1379 removes ability to start hidden to tray.

### ISSUE THREAD

**Issue by AKorezin** [mattermost/desktop#1408] opened 2020-11-05 02:24 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Merge request #1379 removes ability to autostart desktop app hidden by default.
Also flag `--hidden` doesn't work.

**Environment**
- Operating System: Archlinux
- Mattermost Desktop App version: 4.6.1
- Mattermost Server version: 5.27.0

**Steps to reproduce**
Update from 4.5.3 to 4.6.*

**Expected behavior**
Application will launch collapsed into tray.

**Observed behavior**
Application show window by default.

**Possible fixes**

Revert #1379 or revert command line flag to preserve old behavior.

**Comment by Willyfrog** [comment] 2020-11-05 10:13
hello and thanks for reporting, but that was the actual expected behaviour of that PR, it was decided that starting minimized was a confusing experience for most people.

**Comment by AKorezin** [comment] 2020-11-05 13:03
Maybe you can revert `--hidden` flag for people who want app to start minimized?

**Comment by esethna** [comment] 2020-11-06 17:05
@AKorezin thanks for the feedback. I've opened a ticket to make the behaviour on launch configurable. Let us know if you're interested in taking it! https://mattermost.atlassian.net/browse/MM-30336

**Comment by AKorezin** [comment] 2020-11-06 17:32
@esethna it'll be a nice feature.

As for me I autolaunch the app at boot time and autoclose it on shutdown. So most of time it runs in the background.
Most of my apps have this feature.
Some apps like steam has console flag to start minimized.
Some apps like thunderbird has no tray support, but have mods or hacks like birdtray.

**Comment by AKorezin** [comment] 2021-02-03 16:28
Update: used PKGBUILD from aur with reverted patch #1379.
`wget https://patch-diff.githubusercontent.com/raw/mattermost/desktop/pull/1379.diff -O 1379_hide_on_startup.patch`

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 8bac9df..b5fdd71 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -16,14 +16,18 @@ makedepends=('git' 'jq' 'npm')
 #optdepends=('hunspell: spell checking')
 source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz"
         "$pkgname.sh"
-        "${pkgname/-/.}")
+        "${pkgname/-/.}"
+        "1379_hide_on_startup.patch")
 sha256sums=('620ff64ec2c04bfe1005c25988a5d4cb20e376bc9dca9e3ce3e11dbd59ad0b47'
             '0f18f87764465f1fc5a9fdfb6ef2834af4623c13bc95fce58da6cb0d8d39a75e'
-            'e628268d3393aac0d5b7237c6b8818d2e362c373f99874a19171bf96a25e4ffa')
+            'e628268d3393aac0d5b7237c6b8818d2e362c373f99874a19171bf96a25e4ffa'
+            '43ed02e97adfa8b667c7f77b82a8ec1041e8855768a8c965332655fe057f5e2d')
 
 prepare() {
     cd "desktop-$pkgver"
 
+    patch --reverse --strip=1 --input="${srcdir}/1379_hide_on_startup.patch"
+
     # Depending on the architecture, in order to accelerate the build process,
     # removes the compilation of ia32 or x64 build.
     if [[ "$CARCH" == x86_64 ]];then
```

Works ok for me.

**Comment by nmatt** [comment] 2021-07-04 17:24
Please make `--hidden` work again. It can be really annoying to have the Mattermost window in your face on every login. The normal workaround for Windows applications of creating a shortcut with "Run: Minimized" also doesn't work with Mattermost.

**Comment by ventra007** [comment] 2021-09-17 05:50
Hi. Would be nice to have the option to have it open normal or minimized to try. Just because some find it confusing doesn't mean all do.

**Comment by Willyfrog** [comment] 2021-10-19 08:18
thanks for commenting!
We currently have a [ticket](https://mattermost.atlassian.net/browse/MM-30336) for making it optional which would make everyone happy. It is a [Help Wanted Issue](https://github.com/mattermost/mattermost-server/issues/18353) so hopefully someone can pick it up and contribute the needed change, I'll be happy to help anyone taking the issue :)

**Comment by devinbinnie** [comment] 2021-12-09 21:21
Closing in favour of https://github.com/mattermost/desktop/issues/1918

**Closed by devinbinnie** 2021-12-09 21:21 UTC
