### ISSUE TITLE
Bleed through of Mattermost over a file explorer

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#753] opened 2018-04-06 13:59 UTC
**Steps to reproduce**
Make a switch from Mattermost to file-explorer.

Reporter sees this on a test VDI (in a zero client environment 100 % virtualized) with no graphics card.

"For some strange reason alt-tab works just fine ( i believe that it is because the screen HAS to be redrawn due to the graphic it shows). I have read that this is an issue with the version of electron that is used to draw your iFrame and that a newer version of it fixes it."

The reporter mentioned it might be related to an Electron issue fixed with this PR: electron/libchromiumcontent#503. Once the fix is released, we could prepare a test build for the reporter to see if indeed resolves it for them.

<img width="1147" alt="screenshot at apr 06 09-59-50" src="https://user-images.githubusercontent.com/29708087/38425220-489994e4-3981-11e8-8a00-a52f0d5dc716.png">

**Comment by yuya-oc** [comment] 2018-06-22 14:13
Electron v3 would fix this.

**Comment by yuya-oc** [comment] 2018-08-28 12:50
@amyblais I could not reproduce the issue on my PC even when DWM is disabled. Would you contact the reporter to test #847?

**Comment by weekscharlie** [comment] 2018-08-29 20:11
I can reproduce this issue in a VMware virtual desktop (Windows 7 guest) with the current Mattermost desktop release.  Let me know if you have an updated version for me to test and I'll gladly confirm whether the problem is fixed.

**Comment by yuya-oc** [comment] 2018-09-03 12:16
Closed via #847.

**Closed by yuya-oc** 2018-09-03 12:16 UTC
Labels: Bug, Electron, Priority 1, Windows
