### ISSUE TITLE
Crash on app launch

### ISSUE THREAD

**Issue by batonPiotr** [mattermost/desktop#2006] opened 2022-02-18 08:54 UTC
#### Summary
Crash directly upon opening the app

#### Steps to reproduce
1. Open the app, v 5.0.4
2. App crashes

Observed on macOS 12.1 on intel CPU

#### Expected behavior
The app runs

#### Observed behavior (that appears unintentional) 
The app crashes without even drawing the GUI

#### Possible fixes
Found none, temporarily using web mattermost.

[Crashlog](https://github.com/mattermost/mattermost-server/files/8095623/Mattermost.crash.txt)

**Comment by devinbinnie** [comment] 2022-02-18 14:37
@batonPiotr Is this consistently reproducible for you?

**Comment by batonPiotr** [comment] 2022-02-18 14:46
@devinbinnie yes, I deleted and reinstalled the app multiple times with no success.

**Comment by batonPiotr** [comment] 2022-02-21 09:40
@devinbinnie I have more information: it happens, when I start mattermost through shortcuts. It's a macOS app where you can automatise some actions. If I try to open mattermost through it, it will crash. To fix it, I have to restart the system and then launch the app (through finder).

**Comment by devinbinnie** [comment] 2022-02-23 23:27
Created a ticket to investigate: https://mattermost.atlassian.net/browse/MM-42067

**Comment by devinbinnie** [comment] 2022-02-24 21:01
@batonPiotr Did some investigation and was able to reproduce. The app seems to be crashing while calling `app.requestSingleInstanceLock()`, without any logs being reported (and isn't catchable), so it must have been a bug in Electron or Node.

This seems to be resolved in v17.0.1, so we will resolve this issue when we do our Electron upgrade for v5.1

**Comment by batonPiotr** [comment] 2022-02-24 21:21
@devinbinnie Interesting, thanks for taking care of it. Is there any ETA on the upgrade of Electron?

**Comment by devinbinnie** [comment] 2022-02-24 21:24
> @devinbinnie Interesting, thanks for taking care of it. Is there any ETA on the upgrade of Electron?

It will happen for v5.1, which is the next version planned, but doesn't currently have a release date.

In the meantime, I would suggest avoiding Shortcuts for now and just launching the app from the Finder or from the Dock. It may have issues after trying to launch from Shortcuts, so just restart the machine and it should work correctly from there.

**Comment by batonPiotr** [comment] 2022-02-24 21:33
@devinbinnie I removed it from the shortcuts already.

I'll wait for the update then, thanks.

**Closed** 2022-03-14 14:19 UTC
Labels: Type/Bug, MacOS
