### ISSUE TITLE
Desktop client ignores scrolling

### ISSUE THREAD

**Issue by divinebovine** [mattermost/desktop#925] opened 2019-01-30 22:17 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14181

**Summary**
Desktop client ignores scrolling

**Steps to reproduce**
The behavior is intermittent and is hard to nail down a repeatable process to reproduce, though I use the desktop app 99.9% of the time it happens multiple times a day. Whenever I focus to the app, often times the sidebar and main chat area do not scroll when i use my mouse's scroll wheel. Usually it seemingly ignores it for 3-5 seconds and eventually starts scrolling.

- Operating System: Windows 10.0.17134 Build 17134
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 5.6.2

**Expected behavior**
Client should scroll windows when the mouse wheel is rotated.

**Observed behavior**
No scrolling.

**Comment by HarriLuxus** [comment] 2019-02-04 10:46
Happens to me too.
Scrolling can be disabled on any of the views. (channel list, channel or thread view)
Sometimes the scrolling does not continue until I choose another channel or do some other selection.

**Comment by creffett** [comment] 2019-02-11 16:23
I can replicate (4.2.0, Win 10, 64-bit app). For me, the issue appears to be related to multiple monitors - it happens when the Mattermost app is on a secondary monitor but not when it's on my primary monitor. May be related to DPI differences, I can't remember if my main monitor is 4k but my secondaries definitely aren't.

**Comment by amyblais** [comment] 2019-02-13 19:45
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14181

**Comment by esethna** [comment] 2019-02-27 19:16
Trying to narrow this down.

1. Are there certain channels that this occurs in more often?
2. Can you check your CPU and memory usage when this happens?
3. Does it also occur when using the webapp or is it desktop app specific?

**Comment by creffett** [comment] 2019-02-27 19:21
@esethna 
1. No, seems to happen regardless of channel.
2. Nothing out of the ordinary in either CPU or mem usage
3. Only happens with the desktop app

Please also take note of my earlier comment - I can reliably trigger this by putting the Mattermost desktop app onto one of my secondary monitors. I have yet to trigger it with the primary monitor.

**Comment by divinebovine** [comment] 2019-02-28 19:51
Since trying 4.2.0 I haven't seen the issue anymore.

**Comment by divinebovine** [comment] 2019-03-13 19:36
Now that I've said that I haven't seen it, I'm proven wrong. It's happened twice to me today, once within the channel sidebar and once within the conversation pane.

**Comment by ziggurattt** [comment] 2019-04-17 16:28
I have been able to recreate this, as well, and here's some other scenario information:
When I am using my laptop undocked, the scrolling behaves as expected in the desktop client (version 4.2.0). 
When I am using my laptop docked, lid closed, with dual monitors (different resolutions), then the scrolling by mouse-wheel behaves unexpectedly. Primary monitor resolution (where Mattermost Desktop client window resides: 1680 x 1050). Secondary monitor resolution (Mattermost typically NOT residing on this display) is 1920 x 1080. It does not matter which display I have the desktop client on, the scrolling behavior is consistent (in that it does not function as expected). 

Here is how the vertical scrolling by mouse-wheel behaves, and how I have to work around it.
1. If the mouse cursor is in the bottom two-thirds of the main window, or the bottom two-thirds of the list of channels pane, then scrolling behavior is inconsistent. It may or may not scroll up or down. More often than not it will not scroll up or down when using the scroll-wheel. 
2. If the mouse cursor is in the top one-third of the main window, or the top one-third of the list of channels pane, then the scrolling behavior functions as expected, and scrolls vertically every time. 

In either case, it the unexpected behavior occurs whether the desktop client is maximized or not maximized. 

I have the mouse setting "Scroll inactive windows when I hover over them" enabled. But disabling this does not seem to affect my scrolling behavior in the desktop client.

**Comment by amyblais** [comment] 2019-06-07 22:40
Our devs haven't been able to reproduce but they said that this could be due the Operating system managing memory, for example, moving Mattermost to virtual memory, and when the Mattermost windows get the focus it starts to restore the data from the virtual memory leaving the application unresponsive for some seconds.

**Comment by creffett** [comment] 2019-06-07 22:51
With due respect, that answer does not match the problem. It doesn't explain why a) the issue only happens on secondary monitors, and b) scrolling works, but in specific areas of the screen. The problem (at least the one I've seen) is not lag, it's the scrolling not matching the mouse position. Did your devs try using multiple monitors (preferably of varying resolutions)?

**Comment by priyamusale** [comment] 2019-07-08 18:24
@creffett We tried plugging in a mouse and it resolved the issue about scrolling not matching the mouse position.

**Comment by dunham** [comment] 2019-07-17 17:42
I believe I'm experiencing this problem as well (in v4.2.1).  When running the desktop client on either of my two vertical screens (both at 1080x1920), the scrolling only works in a small area in the upper left of the window, and even then does not completely correspond to the correct pane the mouse is hovering in. 

On either of my horizontal screens (both at 3840x2160) the scrolling is fine.

**Comment by hwmatthewa** [comment] 2019-08-29 18:07
Update, this is a bit strange, but it seems like the scrolling stops working when my mouse is below a certain pixel on the Y axis. Above that point it will scroll fine, but if I move my mouse down the screen scrolling will stop functioning.

**Comment by wsuranga** [comment] 2020-01-01 19:13
Can echo @dunham finding above albeit on a slightly different screen set up.

**Comment by amyblais** [comment] 2020-02-27 17:07
Hey all, are you still able to reproduce this on v4.4.0?

**Comment by dunham** [comment] 2020-02-27 19:15
I am unable to reproduce this on v4.4.0 with the same setup and procedures I described above.. seems to be fixed!

**Comment by esethna** [comment] 2020-03-03 17:23
Thanks @dunham, closing this issue

**Closed by esethna** 2020-03-03 17:23 UTC
Labels: Help Wanted, Up For Grabs

**Comment by alolis** [comment] 2022-06-10 06:27
Why is this closed? My team and I we are all experiencing the same issue with Version 5.1.0 (19937)
