### ISSUE TITLE
reply opens sidebar with the cursor in search box

### ISSUE THREAD

**Issue by evils** [mattermost/desktop#1141] opened 2019-12-25 07:59 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Replying defaults to text entry in the `Search` field.

**Environment**
- Operating System: NixOS (linux)
- Mattermost Desktop App version: 4.3.1 - 4.3.2
- Mattermost Server version: 5.18.0

**Steps to reproduce**
Press the reply icon on a message (without the sidebar open)

**Expected behavior**
Cursor for text entry in the `Add a comment...` field.

**Observed behavior**
Cursor for text entry in the `Search` field.

**Notes**
This behaviour was introduced with the update from 5.17.1 to 5.18.0.
(5.17.1 does not display this behaviour, 5.18.0 does)

**Comment by jasonblais** [comment] 2019-12-26 18:29
Thank you @Evils-Devils for the report! We had previously an open bug report for it but closed as cannot reproduce https://mattermost.atlassian.net/browse/MM-21081

@Evils-Devils does this reproduce for other members on your team?

@jgilliam17 @Willyfrog wondering if there is any other information that would help our QA team to pinpoint reproduction steps.

**Comment by Willyfrog** [comment] 2019-12-26 19:30
I can only think of a few questions:

- Can you reproduce the problem consistently? I could for a session, but when I went to look for it again several times acted that one, couldn't.
- can you repro on any browser?
- was the window maximized, full screen, partial? Or any other related state that you could remember?

**Comment by Evils-Devils** [comment] 2019-12-27 11:00
* @Willyfrog, the size of the the window DOES seem to have an effect!
  * as far as i can tell, the issue occurs from 1021 to 1140px width (inclusive)
  * this seems reproducible on another machine
  * and even in firefox!

Side note: if the window is narrow enough to make the channels bar go away, the search box's background is white (this is with the "Mattermost Dark" theme).

**Comment by Willyfrog** [comment] 2019-12-27 23:32
great! I had a hunch on that, but when I tried never got the size right! thanks for reporting it 🙌

**Comment by Evils-Devils** [comment] 2020-01-10 15:52
@Willyfrog, should this be moved to mattermost-server?

as a workaround for anyone else stuck with this, keeping a search term in the search box seems to help

**Comment by Willyfrog** [comment] 2020-01-10 16:02
as you mention it is reproducible on firefox, I'd say yes. but it is already covered by one of [our jira tickets](https://mattermost.atlassian.net/browse/MM-21081), so I guess it is ok to leave it here.

**Comment by ztrayner** [comment] 2020-01-31 15:50
@Willyfrog - It looks like the JIRA ticket was marked as resolved again when it is still an issue.

This bug happens to me on the desktop app.  As mentioned, only at specific window sizes.  I like to keep my MM window just over half of my macbook pro's display size for an optimal line reading length and it happens consistently.  Let me know if you need more information to reproduce apart from what is already here.

**Comment by Willyfrog** [comment] 2020-01-31 15:52
that's because there is already a patch merged into next release: https://github.com/mattermost/mattermost-webapp/pull/4677

**Comment by moollaza** [comment] 2020-02-07 15:35
Just wanted to mention this has been affecting me for about a week, so I'm hoping the fix works.

I'm using the native Mac app, and no one else on my team seems to be affected, but it's consistently happening for me every time I try to reply to a message.

**Comment by amyblais** [comment] 2021-09-08 18:40
Closing, this was fixed in server version v5.20,

**Closed by amyblais** 2021-09-08 18:40 UTC
Labels: Type/Bug
