### ISSUE TITLE
Application Error 0xc000007b on Windows

### ISSUE THREAD

**Issue by h-h-h-h** [mattermost/desktop#927] opened 2019-02-08 21:54 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System:
  - Edition: Windows 10 Home (64-bit on 64-bit machine)
  - Version: 1803
  - OS Build: 17134.407
- Mattermost Desktop App version: 4.2.0 
- ~~Mattermost Server version: X.X.X~~ 

**Steps to reproduce**

Download [64-bit Windows executable](https://mattermost.com/download/#mattermostApps) and try to run it.

**Expected behavior**

Working installation.

**Observed behavior**

Original error dialog directly after trying to run the executable (German):

![Original German error dialog](https://user-images.githubusercontent.com/13482553/52507998-7450a400-2bf3-11e9-8606-8fc98aed2129.png)

Text:

    ---------------------------
    mattermost-setup-4.2.0-win64.exe - Anwendungsfehler
    ---------------------------
    Die Anwendung konnte nicht korrekt gestartet werden (0xc000007b). Klicken Sie auf "OK", um die Anwendung zu schließen. 
    ---------------------------
    OK   
    ---------------------------

This is the corresponding English error dialog, found via [Google image search](https://www.google.com/search?tbm=isch&q=%220xc000007b%22):

![English error dialog](https://msoos.files.wordpress.com/2010/09/0xc000007berror_thumb.jpg?w=490&h=171)

---

The same error dialog appears when trying to run the 32-bit installer (`mattermost-setup-4.2.0-win32.exe`).

~~**Possible fixes**~~

**Comment by JtheBAB** [comment] 2019-02-11 11:54
Is it possible to test on another system? I have the impression your windows has a problem. Can you start the app when you use the zip? https://releases.mattermost.com/desktop/4.2.0/mattermost-desktop-4.2.0-win64.zip

**Comment by wget** [comment] 2019-02-11 12:00
I cannpot reproduce either even on my dev machine where I'm stressing the Mattermost desktop application. Unfortunately with so little info, we will likely close this bug if we cannot get more debug info.

**Comment by h-h-h-h** [comment] 2019-02-12 01:35
- I have no other non-VM machine.
- The .zip file also doesn't work.
- The installation *works* inside a virtual machine with an unactivated Windows 10 setup on the same computer.
- x64dbg terminates Mattermost.exe (from .zip file) shortly after a few very quick actions, though Notepad.exe halts at a default breakpoint
- CFF Explorer on my regular machine says in a table on Mattermost.exe:
  - `File Info | Error: invalid PE file.`
- I searched Mattermost.exe on my regular machine with a hex editor HxD for "bitcoin". 2 occurences:

```
Ä.rC....È.rC....
Ð.rC....Ø.rC....
bitcoin.geo.im..   <--
irc.ircs....magn
et..mms.news....
nntp....openpgp4
fpr.sip.smsto...
ssh.urn.webcal..
wtai....xmpp....
%s......') does 
not contain '%s'

...

r.......Digital 
IXUS....QuickCam
 Express....DC-2
20......Linksys 
(?).....Energy F
ull Corp........
Longshine Electr
onics Corp......
Bitcoin Wallet [   <--
TREZOR].ME-8100B
................
Conceptronic C30
0RU v1 802.11bgn
 Wireless Adapte
r [Ralink RT2870
].......Gigabyte
 U6000 DVB-T tun
er [em2863].....
Foot Switch.....
```

- That *seemed* bad, but I did download Mattermost in the VM freshly and sent Mattermost.exe from my regular machine into the VM; the hex editor says, both Mattermost.exe files are identical. Do you also have occurences of "bitcoin" in your files?
- Putting the extracted Mattermost .zip directory onto the exceptions list of Windows Defender didn't do anything.
- BTW: I don't have the problem with this error dialog with any other software.

**Comment by yuya-oc** [comment] 2019-02-18 12:35
Hi @h-h-h-h, is the Mandatory ASLR enabled on your PC? (https://github.com/mattermost/desktop/issues/852) That causes similar issue on installation/launching. 

For "bitcoin" data, we can't say in detail soon. The installer contains a compressed app, and the string might be just written on plain text files in `mode_modules` dependencies. If possible, would you inspect more in detail?

**Comment by h-h-h-h** [comment] 2019-02-18 14:51
@yuya-oc:

Yes, I have Mandatory ASLR enabled. Disabling it let me install the app. However, on re-enabling the setting, Mattermost won't successfully perform its regular start on system start-up; the old dialog appears again.

I would like to keep this security measure going.

**Comment by servomekanism** [comment] 2019-05-30 13:14
I am facing this issue as well, at the installer that I download from the website:
https://releases.mattermost.com/desktop/4.2.1/mattermost-setup-4.2.1-win64.exe

Allowing the mattermost-setup to not have Mandatory ASLR can start the setup but it gets blocked again, probably at some other path and the error pops during the setup.

The program either doesn't get installed successfully due to the above errors during the installation, or probably requires another white-list that I don't know.

**Comment by devinbinnie** [comment] 2021-12-09 19:32
Duplicate of other ASLR issue which is resolved as well. Closing

**Closed by devinbinnie** 2021-12-09 19:32 UTC
Labels: More Information Needed
