### ISSUE TITLE
Not possible to open URLs in MM linux client

### ISSUE THREAD

**Issue by levigo-systems** [mattermost/desktop#1131] opened 2019-12-13 11:10 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
It is not possible to open URLs in mm linux client.

**Environment**
- Operating System: Linux Mint
- Mattermost Desktop App version: 4.3.0
- Mattermost Server version: 5.17.0

**Steps to reproduce**
Install the mm client on a linux client and try to click on a URL

**Expected behavior**
URL opens in webbrowser

**Observed behavior**
Nothing happens

**Comment by Willyfrog** [comment] 2019-12-13 11:27
Hi there! Can you test on 4.3.2 as it should be fixed there?

**Comment by levigo-systems** [comment] 2019-12-13 12:09
No change **but** i saw something while launching mm via shell.
`Untrusted popup window blocked`

Where i can change this behavior?

**Comment by svelle** [comment] 2019-12-13 13:58
Weird, I use Fedora as a daily driver and have no issues. Maybe it's something Mint specific?

We should test this and see if it's different when using Mint. @levigo-systems what Mint version are you running?

**Comment by levigo-systems** [comment] 2019-12-13 14:31
I am using LMDE 3 (cindy) based on Debian Stretch.

**Comment by svelle** [comment] 2019-12-13 15:35
> I am using LMDE 3 (cindy) based on Debian Stretch.

Great I'll see if I can repro this next week as I'm out for the weekend now. But if anybody else comes first they're more than welcome to do so.

**Comment by levigo-systems** [comment] 2019-12-20 12:09
Hey @svelle did repro the problem?

**Comment by navalnichnik** [comment] 2019-12-21 19:46
I confirm I face the same issue on Debian 10 with Gnome 3.30.2
I moved from Fedora 30 with the same Gnome and MM has been working correctly there.

Clicking on any link in MM generates the following records in the syslog:
`Dec 21 21:44:20 siarzhuk-pc mattermost-desktop.desktop[2418]: [21:44:20.235] [info] Untrusted popup window blocked: https://blablabla.com
Dec 21 21:44:20 siarzhuk-pc mattermost-desktop.desktop[2418]: The setuid sandbox is not running as root. Common causes:
Dec 21 21:44:20 siarzhuk-pc mattermost-desktop.desktop[2418]:   * An unprivileged process using ptrace on it, like a debugger.
Dec 21 21:44:20 siarzhuk-pc mattermost-desktop.desktop[2418]:   * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Dec 21 21:44:20 siarzhuk-pc mattermost-desktop.desktop[2418]: Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Dec 21 21:44:20 siarzhuk-pc kernel: [  911.467450] traps: chrome[25671] trap int3 ip:56444e11dff7 sp:7ffc24e03900 error:0 in chrome[564449f62000+7170000]
`

**Comment by cielavenir** [comment] 2019-12-24 04:26
dupe of #1101, which can be fixed permanently using https://github.com/mattermost/desktop/issues/1101#issuecomment-560137871.

**Closed** 2020-01-07 14:11 UTC
