### ISSUE TITLE
Windows --hidden parameter missing >=4.6.0

### ISSUE THREAD

**Issue by CoOpCouch** [mattermost/desktop#1480] opened 2021-02-17 09:44 UTC
Hello, 

we noticed that the desktop app does not start to system tray anymore and also the parameter "--hidden" seems to be gone

Is this intended? We couldn't find anything about it in the changelog.

4.5.4
![grafik](https://user-images.githubusercontent.com/79195436/108185428-93e90400-710c-11eb-8746-11f3cba16e88.png)

4.6.2
![grafik](https://user-images.githubusercontent.com/79195436/108185556-b7ac4a00-710c-11eb-9547-02f9513529e1.png)

**Comment by Willyfrog** [comment] 2021-02-17 09:49
It was intended as some users were finding the behaviour confusing. You can see the PR here: https://github.com/mattermost/desktop/pull/1379

@amyblais maybe we missed adding that to the changelog?

**Comment by Sandalas** [comment] 2021-02-17 10:34
Is there a possibility to get the hidden feature as an extra option next to the "Start app on login"?

**Comment by amyblais** [comment] 2021-02-17 13:13
It is in the changelog here https://docs.mattermost.com/help/apps/desktop-changelog.html#id1, but I can clarify the text,

**Comment by dlecina** [comment] 2021-02-18 09:28
In my case, I first installed it yesterday, and it was showing up in the tray. Today, it started in a window, and when I close it, it does not minimize to the tray. Strangely, the process seems to be running still, according to the task manager, but I need to reopen the app from a shortcut, as if I had closed it.

I would also keep the feature, even if it must be enabled as a setting.

**Comment by Willyfrog** [comment] 2021-02-18 09:59
I'll bring the topic to the team and see if we can get some sort of compromise solution :)

**Comment by AKorezin** [comment] 2021-02-21 20:59
Possibly dupe of #1408

**Comment by Profesor08** [comment] 2021-05-17 07:13
Every messanger has this feature. And only mattermost starts as an open widow. Please add an config option.

**Comment by nmatt** [comment] 2021-07-04 17:20
Please restore this feature. It can be really annoying to have the Mattermost window in your face on every login; this should at least be configurable.

**Comment by Profesor08** [comment] 2021-08-29 14:19
> Please restore this feature. It can be really annoying to have the Mattermost window in your face on every login; this should at least be configurable.

You can edit it localy))

**Comment by devinbinnie** [comment] 2021-12-09 21:35
Closing in favour of https://github.com/mattermost/desktop/issues/1918

**Closed by devinbinnie** 2021-12-09 21:35 UTC
