### ISSUE TITLE
Bar at the top when part of multiple servers stays white whatever you try

### ISSUE THREAD

**Issue by ArchangeGabriel** [mattermost/desktop#844] opened 2018-08-06 12:20 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Ticket: https://mattermost.atlassian.net/browse/MM-16546

**Summary**

When being part of multiple servers, there is a selection bar at the top. This bar is white whatever I’ve tried, while my desktop theme is dark and so are my Mattermost ones.

**Environment**
- Operating System: Arch Linux
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 5.1.0 for both servers

**Steps to reproduce**

Join two different servers.

**Expected behavior**

The selection bar picks desktop theme.

**Observed behavior**

Selection bar remains white.
![screenshot](https://user-images.githubusercontent.com/490531/43716242-ff9648da-9972-11e8-86af-7acacea74821.png)

**Possible fixes**

Use desktop theme colors? If not possible, allow to choose at least.

**Comment by esethna** [comment] 2018-08-07 19:03
@yuya-oc @asaadmahmood thoughts on this? I would prefer not to have a separate setting for this if we can have something compatible with the Mattermost theme or windows theme?

**Comment by asaadmahmood** [comment] 2018-08-08 07:01
@yuya-oc Can't we detect if a person has set the windows theme dark or Mattermost theme? If we can just pick any of those colors, or even a boolean for a dark variable, we can customise our app accordingly.

Different apps change their behaviour based on the windows theme, so I'm guessing there might be a way for us to atleast detect the Windows theme option.

**Comment by wget** [comment] 2018-08-09 15:43
@ArchangeGabriel 
![b2d6d0dd480ba174fbc2a4cbc4e6fe95](https://user-images.githubusercontent.com/2997662/43909691-42a0ec04-9bfb-11e8-8eae-4dba7b87c79f.jpg)
Can reproduce as well and this is even more annoying on Qt based interfaces. I'm a KDE guy myself.

As you can see the situation for KDE/LXQt, etc. based users is quite even more annoying in the sense of even our theme is not respected. There is nothing Mattermost could do in this context and this needs to be hacked in the libchromiumcontent viewer directly in the chromium repos. :-/
![screenshot_20180809_173709](https://user-images.githubusercontent.com/2997662/43909726-546af4c0-9bfb-11e8-9132-9f56041749e5.png)
But for your problem more specifically  with the bar, there are high chances to get it fixed here.

**Comment by ArchangeGabriel** [comment] 2018-08-09 16:27
Nope, I’m on KDE Plasma. ;) I think your GTK theme does not change the color of the top bar. Most don’t, as I realized y-day when updating Thunderbird (the Inbox view stays black on white on most dark themes that I know of).

**Comment by wget** [comment] 2018-08-09 16:31
@ArchangeGabriel Yes you might be right. I'm using Plasma Breeze for GTK. Which theme are you using for Plasma and for GTK?

**Comment by ArchangeGabriel** [comment] 2018-08-09 16:37
It depends what we’re talking about. I’m using Materia-dark-compact for GTK, but regarding Qt it’s a bit more complicated. I’m using Kvantum’s MateriaDark as Qt style, Materia-Dark for window decorations and Arc-Color for Plasma theme. Not sure which one is responsible for the dark menu bar, but I would say the GTK theme.

**Comment by wget** [comment] 2018-08-09 21:16
For having digged a bit in the electronjs/chromium code base for another Mattermost dekstop bug I still need to fix, I can confirm this is due to GTK. The Aria UI interface of Chromium is managed by an old version of GTK 3.x with a bunch of legacy things.

**Comment by yuya-oc** [comment] 2018-08-10 12:36
@ArchangeGabriel @wget Please let me confirm. Which is "the top bar" you called? As far as reading the first summary, I understood there is the issue on "tab bar".

![where_is_issue](https://user-images.githubusercontent.com/1412057/43957532-1cc45294-9ce3-11e8-86b8-cec5654f5e3a.png)

However, in discussion, I felt you are talking about "menu bar" because you are talking about desktop environment such as KDE and GTK. Which is correct? If it is "tab bar", we might be able to control its color in application code via css.

----

@asaadmahmood @esethna We can't detect desktop theme color on Linux due to electron API. We can do:
- Windows: Get [accent color](https://electronjs.org/docs/api/system-preferences#systempreferencesgetaccentcolor-windows) and [system color](https://electronjs.org/docs/api/system-preferences#systempreferencesgetcolorcolor-windows)
- Mac: [Detect whether it's dark mode](https://electronjs.org/docs/api/system-preferences#systempreferencesisdarkmode-macos)
- Pick up webapp theme color (Can we get it via Mattermost API?)

**Comment by ArchangeGabriel** [comment] 2018-08-10 12:49
@yuya-oc Yes, issue is on the “tab bar”. @wget is the one having issue with the menu bar, I don’t (as you can see on my screenshot it is properly dark).

**Comment by asaadmahmood** [comment] 2018-08-10 13:07
@yuya-oc if we can get the webapp theme color, then that would be great. Not sure if the theme color is forwarded in the API, maybe @hmhealey would know.

**Comment by wget** [comment] 2018-08-14 09:30
For the record, I got the menu bar fixed from my side. Just had to check an additional checkbox in my settings.
![screenshot_20180814_112844](https://user-images.githubusercontent.com/2997662/44083815-5402718a-9fb5-11e8-92cb-3e97a136a522.png)

So this confirms the menu bar problem was on my side.

There is still the tab bar issue left that still needs to be fixed then :)

**Comment by asaadmahmood** [comment] 2018-08-14 09:34
@wget Cool, thanks for the update on that.

**Comment by ArchangeGabriel** [comment] 2018-08-16 13:25
@hmhealey That’s a good point, I was hesitant to mention it and decided I wouldn’t bother your people about that and just use the same theme in each tab. But yes indeed, being the same colors as the menu bar makes probably much more sense.

**Comment by amyblais** [comment] 2019-06-24 13:50
Ticket for reference: https://mattermost.atlassian.net/browse/MM-16546.

**Comment by devinbinnie** [comment] 2021-12-09 19:19
Closing as we now support dark mode integration with Windows/Mac and a toggle for Linux users.

**Closed by devinbinnie** 2021-12-09 19:19 UTC
Labels: Help Wanted, Hacktoberfest, Up For Grabs

**Comment by Saky013** [comment] 2022-03-03 08:51
@devinbinnie 
I have a suggestion for this old closed case - would it be possible to add checkbox to settings, that would close the tab-bar (in case you have only one server you dont need it), or that can automatically hide the tab-bar?
