### ISSUE TITLE
Impossible to update the attached image of a post with API

### ISSUE THREAD

**Issue by gandroz** [mattermost/desktop#1007] opened 2019-07-29 21:41 UTC
**Summary**
Using the API, I add an image with its file_ids to the options when updating a post but the image does not show up

**Steps to reproduce**
- Create a new post
- Create and upload a file (an image)
- Retrieve its file_id
- Update the post with the files_ids options

**Expected behavior**
I expected the image to show up in the updated post

**Observed behavior**
The image is not present in the updated post

**Comment by enahum** [comment] 2019-07-29 22:03
@gandroz your flow is incorrect, it should be:
* Upload files and get the ids in the reponse
* Create a post with the file_ids

cheers.

**Comment by gandroz** [comment] 2019-07-30 12:41
I know how to create a post with the file_ids option, but that's not the point here.

In the API documentation, it is possible to add file_ids as an option :+1: 
![image](https://user-images.githubusercontent.com/38106881/62129850-afc85300-b2a5-11e9-98b6-8c18d10ff2d6.png)
I expected to be able to add an image when updating a post ?

**Comment by hmhealey** [comment] 2019-07-30 14:11
Looks like our documentation is incorrect there. You shouldn't be able to update the files attached to a post at this time. We've discussed adding something like that in the future, but it changes a lot of assumptions we made when designing the system, so there's a lot of work to be done to support that. I'll submit a PR to fix that in the docs.

Is this something you absolutely need for what you're wanting to do? Perhaps we could come up with another way of doing something similar.

**Comment by hmhealey** [comment] 2019-07-30 14:15
I see what the cause of this was. You used to be able to update that field using the previous version of the API, but it wasn't fully implemented, so it would break some stuff. API v4 removed that option since it didn't work correctly

https://github.com/mattermost/mattermost-server/pull/5950

**Comment by hmhealey** [comment] 2019-07-30 14:37
Actually, there seems to be some confusion in the logic here. We used to technically support doing this, but since it was only partially implemented, it would be very buggy. We were supposed to have removed support for it, but that actually made it so that updating a post with file attachments with that API would remove any existing file attachments as well as preventing new ones from being added.

I filed a ticket to fix that as well. In the mean time, you'll want to use the `PUT /api/v4/posts/<ID>/patch` endpoint if you are wanting to make other changes to a post

https://mattermost.atlassian.net/browse/MM-17412

**Comment by gandroz** [comment] 2019-07-30 15:43
Thanks !
My usecase is the following: I am performing a very long lasting task which regularly sends an update (experience results) to a channel. I currently update a post to group my experience results in the same post. I would have liked to add/update an image to this post to visualize the experience results at each update of the task.

**Comment by hmhealey** [comment] 2019-07-31 18:01
What type of image is it? Is it something like a progress bar that's the same for each post, or does each post have its own image?

If the image can be hosted somewhere else, you could use Markdown to render an image as part of the post text (using text like `![alt text](https://example.com/image.png)` and just update the image link each time it changes

**Comment by gandroz** [comment] 2019-07-31 18:11
> If the image can be hosted somewhere else, you could use Markdown to render an image as part of the post text (using text like `![alt text](https://example.com/image.png)` and just update the image link each time it changes

Hmmm nice workaround, thanks

**Comment by devinbinnie** [comment] 2021-12-09 20:07
Closing as this is a webapp issue.

**Closed by devinbinnie** 2021-12-09 20:07 UTC
