### ISSUE TITLE
Mattermost 4.7 window steals focus on StumpWM desktop switch

### ISSUE THREAD

**Issue by runejuhl** [mattermost/desktop#1644] opened 2021-07-01 17:45 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Under StumpWM Mattermost desktop seems to steal focus when losing it, making it impossible to switch desktop when Mattermost is focused.

**Environment**
- Operating System: Ubuntu 20.10
- Mattermost Desktop App version: >=4.7.0, including betas and RCs 
- Mattermost Server version: 5.33.3 
- Window manager: StumpWM

**Steps to reproduce**
+ install Mattermost >=4.7.0
+ open Mattermost
+ while having focus on Mattermost try to switch to another desktop (*group* in StumpWM parlance), either through key binding or by listing groups using `C-t g "` and selecting another group
+ desktop switches to other group and immediately jumps back to original desktop with Mattermost focused

**Expected behavior**
+ Mattermost should not try to steal focus

**Observed behavior**
+ Mattermost steals focus on unfocus if focused when switching desktops (*groups*)

I really have no idea what's at fault here -- it could very well be a bug in [StumpWM](https://github.com/stumpwm/stumpwm), but I haven't seen this issue with any other apps, and I haven't been able to find any reports of similar issues. I don't even know the details of what's going on here, but the behavior resembles any other application that grabs focus.

Attached are 2 debug logs:

+ [`stumpwm-firefox-focus-debug.log`](https://github.com/mattermost/desktop/files/6749904/stumpwm-firefox-focus-debug.log) is a StumpWM debug log of Firefox getting focus, which is done by clicking a link from inside Mattermost. This causes a desktop (*group*) change and Firefox is focused.
+ [`stumpwm-mattermost-debug2.log`](https://github.com/mattermost/desktop/files/6749903/stumpwm-mattermost-debug2.log) is a log of trying to switch desktop (*group*) while Mattermost is focused

Comparing the two logs it seems that Mattermost repeatedly sends a `_NET_ACTIVE_WINDOW` message, which causes StumpWM to focus Mattermost:

~~~
$ grep -nE 'client message|focus-window' /tmp/stumpwm-mattermost-debug2.log 
10:19:33:08  3 focus-window: #S(TILE-WINDOW "emacs" #x2E0001F)
172:19:33:08  2 client message: :_NET_ACTIVE_WINDOW #(1 281948287 0 0 0)
173:19:33:08  3 focus-window: #S(TILE-WINDOW "Mattermost Desktop App" #xC800005)
177:19:33:08  3 focus-window: #S(TILE-WINDOW "Mattermost Desktop App" #xC800005)
182:19:33:08  2 client message: :_NET_ACTIVE_WINDOW #(1 281948288 0 0 0)
183:19:33:08  3 focus-window: #S(TILE-WINDOW "Mattermost Desktop App" #xC800005)
188:19:33:08  2 client message: :_NET_ACTIVE_WINDOW #(1 281948289 0 0 0)
189:19:33:08  3 focus-window: #S(TILE-WINDOW "Mattermost Desktop App" #xC800005)
311:19:33:08  2 client message: :_NET_ACTIVE_WINDOW #(1 281948312 0 0 0)
312:19:33:08  3 focus-window: #S(TILE-WINDOW "Mattermost Desktop App" #xC800005)
317:19:33:08  2 client message: :_NET_ACTIVE_WINDOW #(1 281948315 0 0 0)
318:19:33:08  3 focus-window: #S(TILE-WINDOW "Mattermost Desktop App" #xC800005)
$ grep -nE 'client message|focus-window' /tmp/stumpwm-firefox-focus-debug.log 
65:19:14:42  3 focus-window: #S(TILE-WINDOW "Town Square - Mattermost" #x1C00001)
96:19:14:43  2 client message: :_NET_ACTIVE_WINDOW #(1 280843374 0 0 0)
97:19:14:43  3 focus-window: #S(TILE-WINDOW "New Issue ? mattermost/desktop ? Mozilla Firefox" #xA200003)
101:19:14:43  3 focus-window: #S(TILE-WINDOW "New Issue ? mattermost/desktop ? Mozilla Firefox" #xA200003)
~~~

As far as I can see from the [freedesktop.org documentation on `_NET_ACTIVE_WINDOW`](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46291029838688) this message is used by clients to request another window getting focus, which matches the symptoms.

**Possible fixes**
+ create a hook in StumpWM to ignore Mattermost grabbing focus

**Comment by lkraav** [comment] 2021-07-02 09:52
On Gnome, I've noticed that 4.7 window started eagerly grabbing focus on hover. No other app does this. Someting is definitely off here.

**Comment by runejuhl** [comment] 2021-07-02 09:56
> On Gnome, I've noticed that already since early builds, 4.7 window started eagerly grabbing focus on hover, even if in background. No other app does this. Someting is definitely off here.

That's probably exactly what happens here. If the cursor is above the Mattermost window when I switch groups the Mattermost window probably sees the cursor hover the window immediately after I hit the keys for changing groups, but before StumpWM has a chance to change groups.

If Mattermost grabs focus on hover I can easily see StumpWM first switching groups and the hover event getting processed by Mattermost afterwards, causing StumpWM to switch focus back to Mattermost.

**Comment by lkraav** [comment] 2021-07-02 11:56
> That's probably exactly what happens here.

Yarr, I've been a bit lazy with filing this issue earlier. Thanks for getting the fire started.

**Comment by Willyfrog** [comment] 2021-07-09 16:27
ticket created for further investigation, feel free to add any details and repro steps if possible with gnome/kde environment (if not, that's ok and I'll try to figure out but I'm not used to stumpwm)

[MM-36937](https://mattermost.atlassian.net/browse/MM-36937)

**Comment by einarjh** [comment] 2021-07-26 08:28
No need to test with stumpwm, I have a variant of the same issue on Fedora 34, using GNOME 40. Same issue probably exists on all versions of GNOME when using "Sloppy Focus". Steps to reproduce:

* Activate "sloppy focus" by using GNOME Tweaks and going to "Windows" -> select "Focus on Hover" under "Window Focus". Make sure that "Raise Windows When Focused" is switched off.
* Place any window overlapping the Mattermost Desktop App
* Observe that Mattermost Desktop App immediately jumps to foreground when the mouse hovers over it, obscuring the window that should still be above it.
* It is also impossible to alt-tab to any other window while the mouse is still hovering over Mattermost Desktop App.

Note that Mattermost Desktop App does not steal focus or misbehave if "Window Focus" is set to "Click to Focus".

**Comment by Willyfrog** [comment] 2021-07-26 08:46
thanks for the repro steps, that helps a lot :D

**Comment by kristianronningen** [comment] 2021-07-28 08:43
I see the same behaviour (as described by @einarjh) on Ubuntu 20.10 with XFCE, using Mattermost 4.7.0 commit b757742. Settings for "Window Manager" are:

```
Focus model
[  ] Click to focus      [X] Focus follows mouse

New window focus
[X] Automatically give focus to newly created windows

Raise on focus
[  ] Automatically raise windows when they receive focus

Raise on click
[X] Raise window when clicking inside application window
```

The Mattermost window is the only one that behaves this way. If changing to "Click to focus", it does not steal focus and jump to the foreground.

**Comment by bmerry** [comment] 2021-09-21 07:04
I'm also experiencing this with Xfce, since upgrading from 4.6.something to 4.7.2. My focus setting is "Focus follows mouse".

**Comment by lkraav** [comment] 2021-09-21 11:52
Still same broken behavior in 5.0.0-rc1.

**Comment by Willyfrog** [comment] 2021-10-11 09:24
It is currently scheduled for 5.1, but that might be delayed depending on priorities.

If anyone wants to help with the issue I can mark it as part of hacktoberfest if needed. Otherwise, I'm afraid it will have to wait until we can stabilize the new codebase (on 5.0 we did another major rework moving to typescript)

**Comment by devinbinnie** [comment] 2021-12-02 21:52
Sorry for the slow response.

Was able to reproduce, however I don’t think this is something we can fix.
Currently in order to make sure that focus returns back to whatever BrowserView we were last using (either one of the MattermostViews or a modal), we have to manually focus() the BrowserView, which is what causes this issue on Sloppy Focus, because calling that method seems to raise the window, and there doesn’t seem to be anyway to stop it.

There's an electron issue [here](https://github.com/electron/electron/issues/28163) to fix the issue where the BrowserView doesn't automatically get focus back when the window does, but it doesn't seem to have any attention at this time.

**Comment by devinbinnie** [comment] 2021-12-02 21:53
See my response here, I do believe these two issues are caused by the same thing: https://github.com/mattermost/desktop/issues/1827#issuecomment-985030561

**Comment by devinbinnie** [comment] 2021-12-09 22:15
Closing this issue in favour of #1827

**Closed by devinbinnie** 2021-12-09 22:15 UTC
