### ISSUE TITLE
Away from keyboard is not treated correctly on desktop

### ISSUE THREAD

**Issue by Alexander-Serov** [mattermost/desktop#1285] opened 2020-05-06 14:19 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This does not apply to Chrome. This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.4.0 
- Mattermost Server version: 5.18.1 

**Steps to reproduce**
Open any chat in the desktop client. Minimize the window by clicking minimize.

**Expected behavior**
Notifications arrive normally on the phone (they are correctly set in the settings. this is not the problem) and *stay* there until read.

**Observed behavior**
Notifications arrive on the phone for a brief moment, but then disappear, because the message is apparently marked as read by the minimized desktop client. If I choose a different chat in the desktop app, and then minimize, the notifications arrive correctly on the phone.

**Possible fixes**
Do not mark chat messages as read when the chat is minimized on desktop.

**Comment by savegame** [comment] 2020-05-06 15:35
this is  duplicate of #1282

**Comment by amyblais** [comment] 2020-05-11 15:49
This is now fixed in v4.4.2 https://github.com/mattermost/desktop/releases/tag/v4.4.2.

**Closed by amyblais** 2020-05-11 15:49 UTC
