### ISSUE TITLE
[Crash]: 5.3.1 crashes when trying to share the screen on Linux

### ISSUE THREAD

**Issue by apollo13** [mattermost/desktop#2694] opened 2023-04-28 08:35 UTC
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.2.3

### Operating System

Fedora 38

### Mattermost Server Version

7.8.2

### What type of crash did you experience?

System crash (The application quit unexpectedly with no warning, or the operating system reported a crash)

### Crash report details

```shell
GDB doesn't have any useful information since the cores are to small (not sure why). But the issue occurs reliably on Fedora 38 with Wayland at least.
```

### Log Output

```shell
10:26:51.232 › DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
10:26:51.235 › DownloadsManager.saveAll
10:26:51.236 › DownloadsManager.checkForDeletedFiles
10:26:51.346 › Autoupgrade disabled: false
10:26:51.398 › couldn't show XXX___TAB_MESSAGING, not ready
10:26:51.401 › Failed to set new language en-US
10:26:51.402 › Failed to set new language DE
10:26:51.438 › config.autostart has been configured: true
10:26:51.439 › config.autostart has been configured: true
[24662:0428/102704.097676:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[24662:0428/102704.106735:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[24662:0428/102710.336218:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[1]    24623 segmentation fault (core dumped)  ./mattermost-desktop
```

**Comment by apollo13** [comment] 2023-04-28 08:38
The crash does not occur on X11

**Comment by devinbinnie** [comment] 2023-05-01 13:20
@apollo13 To clarify, are you using the Calls plugin and widget?

**Comment by devinbinnie** [comment] 2023-05-01 14:36
@apollo13 Can you upgrade to version v5.3.1? Also can you make sure you're using the latest version of the Calls plugin?

cc @cpoile @streamer45

**Comment by apollo13** [comment] 2023-05-01 15:45
Sorry, I miss-clicked when filing the issue. 5.3.1 is the one broken. 5.2.3 still works!

**Comment by streamer45** [comment] 2023-05-02 08:58
I would be very surprised if upgrading the plugin fixed this. Sounds like an Electron v23 issue playing with Wayland. I can try to reproduce on Ubuntu and see if it happens there as well.

**Comment by streamer45** [comment] 2023-05-02 09:00
Likely related to https://github.com/electron/electron/issues/37463

**Comment by devinbinnie** [comment] 2023-05-02 12:44
Thanks @streamer45, looks like they tried to fix it in v23.1.3 (we're on 23.3.0 now) but it didn't work so we'll likely need to wait for a final fix.

**Comment by apollo13** [comment] 2023-05-17 09:32
Wouldn't it make sense to downgrade electron in the meantime to get a working app?

**Comment by apollo13** [comment] 2023-07-15 15:25
@devinbinnie This should now be fixable by upgrading electron :)

**Comment by apollo13** [comment] 2023-07-16 10:53
https://github.com/electron/electron/issues/39043 will need to get included as well as soon as it hits a electron release.

**Comment by apollo13** [comment] 2023-07-18 06:21
@devinbinnie is there a way to test a nightly build of mattermost or so to report back? I fear https://github.com/electron/electron/issues/39043 might still be pretty much a showstopper and preferably mattermost should not even show it's own window/screen chooser but solely trigger the desktop portal on wayland (the mattermost built chooser doesn't appear when I use mattermost as a web app either)

**Comment by devinbinnie** [comment] 2023-07-18 13:56
@apollo13 Yep! You can find the latest nightly build here: https://community.mattermost.com/core/pl/tgyjc81sypb3xk1t4b6yoaqwuo

**Comment by devinbinnie** [comment] 2023-07-18 16:45
> Mhm that seems to be the online app and not the desktop app build (which would be relevant here?)

There are links to the nightly build there.

**Comment by apollo13** [comment] 2023-07-19 17:03
I must be clicking the wrong ones -- can't seem to find them 😔

**Comment by apollo13** [comment] 2023-08-24 08:16
Hi @devinbinnie, I have built mattermost locally and updated electron to 26.1.0 to include https://github.com/electron/electron/issues/39043 -- this makes it behave properly now. Can I submit a PR to raise electron, or do you need to do more before raising the electron version?

**Comment by devinbinnie** [comment] 2023-08-28 15:23
> Hi @devinbinnie, I have built mattermost locally and updated electron to 26.1.0 to include [electron/electron#39043](https://github.com/electron/electron/issues/39043) -- this makes it behave properly now. Can I submit a PR to raise electron, or do you need to do more before raising the electron version?

Hey, yes I've re-opened your PR to upgrade Electron. Sorry I closed it before I saw this (just got back from vacation). In the future please link the PR to the ticket :)

**Closed** 2023-08-29 13:19 UTC
Labels: Linux, Electron, Type/Crash Report
