### ISSUE TITLE
[Bug]: Focus on mouse raises window on Ubuntu 22.04.LTS with XFCE

### ISSUE THREAD

**Issue by joho1968** [mattermost/desktop#2797] opened 2023-07-24 07:23 UTC
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0 commit 420c63d

### Operating System

Ubuntu Linux 22.04 LTS x64 with XFCE

### Mattermost Server Version

7.10.2

### Steps to reproduce

- Start Mattermost Desktop client
- Move mouse pointer to give focus to another window
- Click on that window to raise it
- Move mouse pointer back to Mattermost Desktop client window

### Expected behavior

Focus should **not** raise window, it should _follow whatever the operating system is set to_. In my case, that setting is "focus follows mouse" but does not raise the focus window.

### Observed behavior

Mattermost Desktop client window receives focus **and** is raised. This has been an issue since many versions AFAIK.

### Log Output

```shell
[2023-07-24 08:17:10.436] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-07-24 08:17:10.442] [debug] DownloadsManager.saveAll
[2023-07-24 08:17:10.442] [debug] DownloadsManager.checkForDeletedFiles
[2023-07-24 08:17:10.485] [warn]  Current working directory is /home/username, changing into /home/username/mattermost-desktop
[2023-07-24 09:08:48.668] [warn]  main window closed
[2023-07-24 09:09:05.520] [debug] [DownloadsManager] init { 'this.json': {}, validatedJSON: {} }
[2023-07-24 09:09:05.524] [debug] [DownloadsManager] saveAll
[2023-07-24 09:09:05.525] [debug] [MainWindow] Can't send update-downloads-dropdown, will retry
[2023-07-24 09:09:05.526] [debug] [DownloadsManager] checkForDeletedFiles
[2023-07-24 09:09:05.556] [error] Logger Log level set to: info
[2023-07-24 09:09:05.564] [warn]  [App.Initialize] Current working directory is /home/username, changing into /home/username/mattermost-desktop
[2023-07-24 09:09:05.672] [info]  [App.Config] config.autostart has been configured: true
[2023-07-24 09:09:05.683] [info]  [App.Initialize] Autoupgrade disabled: false
[2023-07-24 09:09:05.845] [info]  [ServerDropdownView] init
[2023-07-24 09:09:05.875] [warn]  [i18nManager] Failed to set new language en-US
[2023-07-24 09:09:05.876] [warn]  [i18nManager] Failed to set new language SE
[2023-07-24 09:09:06.015] [info]  [App.Config] config.autostart has been configured: true
[2023-07-24 09:09:06.820] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2023-07-24 09:09:08.555] [info]  [App.Config] config.autostart has been configured: true
[2023-07-24 09:09:59.712] [info]  [App.Config] config.autostart has been configured: true
[2023-07-24 09:10:18.963] [info]  [App.Config] config.autostart has been configured: true
[2023-07-24 09:10:26.226] [error] Logger Log level set to: warn
[2023-07-24 09:10:38.835] [debug] [DownloadsManager] init { 'this.json': {}, validatedJSON: {} }
[2023-07-24 09:10:38.840] [debug] [DownloadsManager] saveAll
[2023-07-24 09:10:38.841] [debug] [MainWindow] Can't send update-downloads-dropdown, will retry
[2023-07-24 09:10:38.841] [debug] [DownloadsManager] checkForDeletedFiles
[2023-07-24 09:10:38.873] [error] Logger Log level set to: warn
[2023-07-24 09:10:38.880] [warn]  [App.Initialize] Current working directory is /home/username, changing into /home/username/mattermost-desktop
[2023-07-24 09:11:21.563] [debug] [DownloadsManager] init { 'this.json': {}, validatedJSON: {} }
[2023-07-24 09:11:21.566] [debug] [DownloadsManager] saveAll
[2023-07-24 09:11:21.567] [debug] [MainWindow] Can't send update-downloads-dropdown, will retry
[2023-07-24 09:11:21.567] [debug] [DownloadsManager] checkForDeletedFiles
[2023-07-24 09:11:21.603] [error] Logger Log level set to: warn
[2023-07-24 09:11:21.613] [warn]  [App.Initialize] Current working directory is /home/username, changing into /home/username/mattermost-desktop
[2023-07-24 09:11:35.290] [debug] [DownloadsManager] init { 'this.json': {}, validatedJSON: {} }
[2023-07-24 09:11:35.296] [debug] [DownloadsManager] saveAll
[2023-07-24 09:11:35.297] [debug] [MainWindow] Can't send update-downloads-dropdown, will retry
[2023-07-24 09:11:35.298] [debug] [DownloadsManager] checkForDeletedFiles
[2023-07-24 09:11:35.337] [error] Logger Log level set to: warn
[2023-07-24 09:11:35.351] [warn]  [App.Initialize] Current working directory is /home/username, changing into /home/username/mattermost-desktop
```

**Comment by devinbinnie** [comment] 2023-07-24 19:17
This is a duplicate of this issue: https://github.com/mattermost/desktop/issues/1827
Closing in favour of that one.

**Closed by devinbinnie** 2023-07-24 19:17 UTC
Labels: Type/Bug
