### ISSUE TITLE
Java error at launch Windows 10 desktop version

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [mattermost/desktop#2419] opened 2022-11-25 08:36 UTC
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 family 21H2 build 19044.2251
- Mattermost Desktop App version: X.X.X  5.2.1
- Mattermost Server version: X.X.X 
Mattermost Version: 7.4.0
Database Schema Version: 93
Database: postgres

**Steps to reproduce**
Launching the desktop app

**Observed behavior**

![image](https://user-images.githubusercontent.com/19731340/203934674-ce86bed7-88ec-4b9a-8421-092b2d38a42c.png)

**Possible fixes**

**Comment by Jacques-Olivier-Farcy** [comment] 2022-11-25 08:55
I have re-installed the desktop app
I have the same error when launching it after that.

**Comment by gavol** [comment] 2022-11-25 09:25
The same for me on Win 10, version 5.2.1.

**Comment by cforce** [comment] 2022-11-25 10:20
same here

**Comment by devinbinnie** [comment] 2022-11-25 14:22
Duplicate of https://github.com/mattermost/desktop/issues/2400. It will be fixed in v5.2.2.

You can download the release candidate here: https://github.com/mattermost/desktop/releases/tag/v5.2.2-rc.1

**Closed by devinbinnie** 2022-11-25 14:22 UTC
