### ISSUE TITLE
[Crash]: Attempting to update crashes Mattermost Desktop

### ISSUE THREAD

**Issue by njnatale-lm** [mattermost/desktop#2855] opened 2023-09-20 11:26 UTC
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.1-rc.1

### Operating System

Windows 11 x64

### Mattermost Server Version

8.0.1

### What type of crash did you experience?

Uncaught exception (I saw a dialog pop up that said "The Mattermost app quit unexpectedly")

### Crash report details

```shell
Application: Mattermost 5.5.1-rc.1 [commit: d05bde5
]
Platform: Windows_NT 10.0.22621 x64
Error: New version 5.5.1-rc.2 is not signed by the application owner: publisherNames: CN="Mattermost, Inc.", O="Mattermost, Inc.", L=Palo Alto, S=California, C=US, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=SSL.com Code Signing Intermediate CA RSA R1, O=SSL Corp, L=Houston, S=Texas, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1767639213000)/",
    "NotBefore": "/Date(1673031213000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "1B72276B863BEFB61B5FD6863102078D",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "BFB8675F448C54BB15B89DB08901CD16A291D670",
    "Version": 3,
    "Issuer": "CN=SSL.com Code Signing Intermediate CA RSA R1, O=SSL Corp, L=Houston, S=Texas, C=US",
    "Subject": "CN=\"Mattermost, Inc.\", O=\"Mattermost, Inc.\", L=Palo Alto, S=California, C=US"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(2044396799000)/",
    "NotBefore": "/Date(1689292800000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0544AFF3949D0839A6BFDB3F5FE56116",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp 2023, O=\"DigiCert, Inc.\", C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "66F02B32C2C2C90F825DCEAA8AC9C64F199CCF40",
    "Version": 3,
    "Handle": 2246002551728,
    "Issuer": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US",
    "Subject": "CN=DigiCert Timestamp 2023, O=\"DigiCert, Inc.\", C=US"
  },
  "Status": 1,
  "StatusMessage": "A certificate chain could not be built to a trusted root authority"
}
    at Object.newError (C:\Users\<redacted>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:65331:17)
    at Object.task (C:\Users\<redacted>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:82371:40)
    at async NsisUpdater.executeDownload (C:\Users\<redacted>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:70007:7)
```

### Log Output

```shell
Log contains messages that seem identical to the "Show details" output.
```

### Additional Information

* This only started happening recently; in the past, I could download updates without any issue (whether I was on stable or RC versions)
* My employer uses a special proxy service that includes a custom CA certificate for every site we visit; I'm sure this is related, but we need the ability for Mattermost to accept whatever CAs the system has, or the ability to ignore this check altogtether
  * again, this worked very recently, so I assume this "check" that the app does was only recently added

**Comment by devinbinnie** [comment] 2023-09-21 07:20
@njnatale-lm I'm not able to reproduce this myself, and I had a look at the binaries and the installer and it appears they are both signed. Is there any restrictions on your computer around certain code signing requirements? Have you tried installing on a different machine to see if the issue persists there?

<img width="566" alt="image" src="https://github.com/mattermost/desktop/assets/52460000/4cfbef43-2f52-4e32-898e-bdaf3a0b1c9d">

**Comment by njnatale-lm** [comment] 2023-09-21 10:54
@devinbinnie I believe there are restrictions, yes. I don't have access to another device, but I have had other colleagues try and they have ran into the same exact issue.

When I right click on the installer for 5.5.1 RC1, and go to the same screen as in your image, I see "The certificate in the signature cannot be verified" - when I click on "View Certificate" I see the standard Windows certificate information box, but with a yellow triangle and "Windows does not have enough information to verify this certificate".

Did something change with how the desktop installers are signed? I'd like to try to understand if our system policy changed, or if the installer was signed by a more recognized CA in the past, perhaps.

**Comment by njnatale-lm** [comment] 2023-09-21 10:57
@devinbinnie For comparison, I just re-downloaded the installer for 5.4.0; in this case, I see nothing wrong, and Windows reports that "This digital signature is OK".

This seems to point to some type of certificate or CA chain change on the compiling side of Mattermost.

**Comment by devinbinnie** [comment] 2023-10-02 13:47
@njnatale-lm So I am seeing one small difference in the signature here:

![Screenshot 2023-10-02 at 9 45 10 AM](https://github.com/mattermost/desktop/assets/52460000/801be753-80a9-4bc8-a1a1-160f31a69418)

We use a timestamp server to verify that our signature is still valid as of the installation. We did rotate our certificates last year, but that was before the release of v5.4.

I'm wondering now if your system requires a specific signer name? Or maybe there's a Windows update needed?

**Comment by njnatale-lm** [comment] 2023-10-04 11:51
I've noticed the same; since Mattermost is now using a new signer, I guess our corporation's list of trusted CA certs doesn't include this. Bummer; guess this will just have to break all of our update abilities.

**Comment by devinbinnie** [comment] 2023-10-04 13:02
> I've noticed the same; since Mattermost is now using a new signer, I guess our corporation's list of trusted CA certs doesn't include this. Bummer; guess this will just have to break all of our update abilities.

This seems like something worth escalating within your org, since DigiCert will update this semi-regularly I'd imagine.

Closing this issue for now since it seems like we've come to a conclusion. Happy to answer further questions if I can.

**Closed by devinbinnie** 2023-10-04 13:02 UTC
Labels: Type/Crash Report
