### ISSUE TITLE
Notifications on Ubuntu 16.04

### ISSUE THREAD

**Issue by DivineOmega** [mattermost/desktop#140] opened 2016-05-17 08:31 UTC
There is an issue running Mattermost Desktop on Ubuntu 16.04 which causes all notifications to appear as dialogue boxes in the centre of the screen with OK and Cancel button, rather than the more elegant fading notifications. This started occurring after I upgrade to Ubuntu 16.04.

After doing some research, I believe this is an Electron issue, see the issue linked below. Apparently the problem is fixed in Electron release 0.37.6.

https://github.com/electron/electron/issues/465#issuecomment-183527458

**Comment by yuya-oc** [comment] 2016-05-17 09:00
Duplicate of #116. Please try v1.2.0.

At the next time, please write your application version (see CONTRIBUTING.md).

**Closed by yuya-oc** 2016-05-17 09:00 UTC
Labels: duplicate, linux

**Comment by DivineOmega** [comment] 2016-05-17 09:48
Sorry, I thought I'd installed the latest version. I somehow missed the fact 1.2.0 was released.
