### ISSUE TITLE
[Bug]:  Starting from version 5.9.0 in Mattermost, there is an error when downloading .DFX files (Drawing eXchange Format).

### ISSUE THREAD

**Issue by EfimovSergeiV** [mattermost/desktop#3193] opened 2024-11-04 11:26 UTC
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

+5.9.0

### Operating System

Debian Linux 12/ Windows 10

### Mattermost Server Version

+10.0.1

### Steps to reproduce

Upload this file to Mattermost and try to download it from Mattermost Desktop.

[wikipedia about file](https://ru.wikipedia.org/wiki/DXF)
[file.zip](https://github.com/user-attachments/files/17617328/file.zip)

### Expected behavior

The file uploads without errors.

### Observed behavior

Application crashes.

![Снимок экрана (31)](https://github.com/user-attachments/assets/2fa71d6f-a8c8-4071-a789-fe0e9dd4e972)

### Log Output

```shell
`
Application: Mattermost 5.9.0
Platform: Windows_NT 10.0.19045 x64
Error: Failed to get thumbnail from local thumbnail cache reference
    at C.formatDownloadItem (C:\Users\anon\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:258206)
    at C.upsertFileToDownloads (C:\Users\anon\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:255614)
    at C.doneEventController (C:\Users\anon\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:256970)
    at DownloadItem.<anonymous> (C:\Users\anon\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:254776)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)
`
```

**Comment by devinbinnie** [comment] 2024-11-04 14:11
This is a duplicate of https://github.com/mattermost/desktop/issues/3140. Closing.

**Closed by devinbinnie** 2024-11-04 14:11 UTC
Labels: Type/Bug
