### ISSUE TITLE
HTTP link previews do not show up in Desktop App

### ISSUE THREAD

**Issue by lfbrock** [mattermost/desktop#109] opened 2016-04-11 23:28 UTC
On desktop app v1.1.0, OS X. 

Repro Steps: Post an image link starting with http://

Observed: On browsers, a preview of the image will automatically be shown below the link. In the desktop app, no image shows up.

**Comment by yuya-oc** [comment] 2016-04-13 14:04
Duplicate of #35

**Closed by yuya-oc** 2016-04-13 14:04 UTC
Labels: duplicate
