### ISSUE TITLE
Time is incorrect in OSX High Sierra

### ISSUE THREAD

**Issue by cetra3** [mattermost/desktop#679] opened 2018-01-15 03:17 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14168

**Summary**

The time of the desktop app in mattermost is incorrect in High Sierra.  This may be related to daylight savings time.  

The time is correct in the web browser, and was correct before upgrading from El Capitan.

**Steps to reproduce**

Operating System: OS X High Sierra: `10.13.2 (17C88)`
Mattermost Desktop App version: Version `3.7.1`

* Set your system timezone to a city that is currently experiencing daylight savings time, such as Melbourne - Australia
* Write a message to someone

**Expected behavior**

The time displays the correct time.

**Observed behavior**

The time is one hour out:

![time_test](https://user-images.githubusercontent.com/6415435/34925658-a217d7ae-f9fa-11e7-9298-e6add940e48b.jpg)

**Possible fixes**

No idea!

**Comment by jasonblais** [comment] 2018-01-17 18:32
Thanks @cetra3! Does this reproduce on a browser, say Chrome?

**Comment by jasonblais** [comment] 2018-01-17 18:33
@yuya-oc Would you have any thoughts on this issue?

**Comment by yuya-oc** [comment] 2018-01-18 13:14
Not reproduced for me probably because my Mac uses Sierra.

The link and the tooltip are rendered by webapp.
https://github.com/mattermost/mattermost-webapp/blob/080a80b265db029b060ae11ace8d9ddbb206b843/components/post_view/post_time.jsx#L64-L76

So I think that `title={date}` and `date.toLocaleString()` are different in the combination of High Sierra and Electron. I feel `title` should also uses `date.toLocaleString()` for now.

@cetra3 In your screenshot, which time is correct, the link or the tooltip?

**Comment by cetra3** [comment] 2018-01-18 18:29
The tooltip has the correct time

**Comment by yuya-oc** [comment] 2018-01-18 23:24
Thanks! Assuming that, `date.toLocaleString()` shows incorrect time due to some reason.

**Comment by cetra3** [comment] 2018-01-19 02:44
@yuya-oc, Yep, appears to be that function is incorrect in Electron.  Do you want me to raise an issue with them?

**Comment by paladini** [comment] 2018-01-26 16:22
My team is facing the same issue. The error doesn't happen with Mattermost using Chrome or other browser to access the chat, but occurs when using macOS High Sierra app. 

Following you can see a picture showing the problem: https://www.dropbox.com/s/xkh7pd30qox7wtx/Screenshot%202018-01-26%2014.19.27.png?dl=0

On the left you can see our macOS High Sierra desktop app, on the right you can see a Chrome browser with Mattermost chat opened.

**Comment by jasonblais** [comment] 2018-01-26 18:48
@yuya-oc If I understand correctly, looks like the issue is resolved once Electron has upgraded to Chromium 63

> In that case, it'll be resolved when we officially update to Chromium 63; please see https://github.com/electron/electron/projects/7 for progress! I'm going to go ahead and close this.

https://github.com/electron/electron/issues/11670#issuecomment-360014658

If that's the case, we may have to wait until Electron v2.0 is released https://github.com/electron/electron/pull/11459#issuecomment-352783190

**Comment by yuya-oc** [comment] 2018-01-27 02:40
@jasonblais I’m not sure whether it will be Electron v2 though, I think so, too.

**Comment by ibraimedina** [comment] 2018-02-05 16:37
+1

**Comment by abdelrahmanrifai** [comment] 2018-08-22 12:07
I had the same issue on both desktop and mobile, it just have been fixed yesterday in Android: https://github.com/mattermost/mattermost-mobile/issues/1935

Please take a look for a fix for desktop too!

**Comment by jasonblais** [comment] 2018-08-22 12:14
@yuya-oc Do you know if upgrading to Electron v2 helped resolve the issue?

**Comment by yuya-oc** [comment] 2018-08-22 14:50
Finally Electron v2 used Chrome 61, so sadly the issue would not be resolved. Electron v3 beta, Chrome 66 would help.

**Comment by abdelrahmanrifai** [comment] 2018-08-22 15:45
As you can see from the following screenshot, hovering over the text time _**6:15 PM**_ show the correct time _**5:15 PM**_ === _**17:15**_! So it's just adding an hour somehow before displaying the text.

![s](https://user-images.githubusercontent.com/4334778/44474221-72d5f400-a632-11e8-87de-5e8131f92899.png)

Please check the fix for mobile version, maybe it's the same issue: https://github.com/mattermost/mattermost-mobile/pull/1982

**Comment by yuya-oc** [comment] 2018-08-23 12:15
The way to display the time is different from mobile apps. Sadly desktop app can't do anything for this other than upgrading Electron because the UI is actually webapp as well as web browsers.

**Comment by abdelrahmanrifai** [comment] 2018-08-23 15:39
@yuya-oc by the way **tooltip is the correct time**, not the opposite.

**Comment by yuya-oc** [comment] 2018-08-24 16:41
@abdelrahmanrifai Ah, that's my mistake. However anyway the desktop app can't. In the first time, we found a bug in JavaScript API, `date.toLocaleString()`. It's a part of webapp, so the desktop app can't touch. https://github.com/mattermost/desktop/issues/679#issuecomment-358642652

To solve this, webapp would need to calculate local time by manually considering it's in DST or not.

**Comment by ThiagoCruzBr** [comment] 2018-10-24 17:36
Hello, 
Should I open an issue for Windows and Linux version?
Because we have same issue at **Windows** and **Linux** desktop **version 4.1.2**. At Mattermost web, time is correct. We are using Mattermost server version 5.1.1 and date time in OS is ok.

**Comment by amyblais** [comment] 2019-02-12 15:21
Hi all, do you have the experimental timezone setting enabled on your server? https://docs.mattermost.com/administration/config-settings.html#timezone

**Comment by cetra3** [comment] 2019-02-12 22:00
@amyblais  I don't want everyone having to manually override their timezone settings, as we do travel in different timezones on occasion.

Is there any plans to update to the latest version of electron?

**Comment by amyblais** [comment] 2019-02-13 18:46
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14168.

**Comment by thejustinporter** [comment] 2019-02-14 03:29
Also seeing this same issue on OSX Mojave, but OSX Sierra seems to be displaying correctly.

**Comment by yuya-oc** [comment] 2019-02-18 12:42
Hi there, the latest build which uses Electron v4 (Chrome 69) can be found on the following link. Does this help?

https://circleci.com/gh/mattermost/desktop/1857#artifacts
-> https://1857-43964563-gh.circle-artifacts.com/0/packages/mattermost-desktop-4.3.0-develop-mac.zip

**Comment by wget** [comment] 2019-02-20 09:05
@thejustinporter But what @yuya-oc meant is: does the aforementionned test build with the latest version of electron works on macOS Sierra as well? Does this test build fixes your problem?

**Comment by thejustinporter** [comment] 2019-02-21 04:17
@wget This is working on Sierra as well (but just to be clear the times were already correct on Sierra before - so no change here).

**Comment by wget** [comment] 2019-02-24 16:25
@thedingwing Sure, this was just to make it clear.
Since we will be cutting 4.3.0 in 15 days, and it appears this build will be solving your issue, I'm in favor of closing this issue. If you encounter an issue again after 4.3 has been cut and you upgraded to it, feel free to repost here and we will reopen the issue :)

**Closed by wget** 2019-02-24 16:25 UTC
Labels: Bug, Electron, MacOS

**Comment by caspChristian** [comment] 2019-09-05 01:15
Seeing a weird issue on Windows desktop app which is similar.
Sometimes times of messages changes to display in GMT, even tho timezone under Account Settings are auto, and detected as Stockholm, restarting the clients, times goes back to being correctly displayed, and then a few days later, shown as GMT again. This is with client version 4.1.2

The most confusing thing here is the "random" change to different time display.
