### ISSUE TITLE
Flat oak package needs update - square symbols under fedora

### ISSUE THREAD

**Issue by boistordu** [mattermost/desktop#1664] opened 2021-07-18 12:25 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Square symbols are back even in flatpack package 

All other electron app are working fine under flatpack wether it's signal element or others.
So according to my previous issue about square in snap package, your version of electron is not the up to date one. 
Thanks to update the app with the latest electron builder.

**Environment**
- Operating System: fedora 34 
- Mattermost Desktop App version: 4.7.0 commit b757742
- Mattermost Server version: X.X.X 

**Steps to reproduce**

**Expected behavior**
No more square symbol in the system sub menu in gnome-shell interaction menu right click on your icon
**Observed behavior**

Square symbol 
![image](https://user-images.githubusercontent.com/9523075/126066934-b982509d-bdc4-44e6-b2fd-76f9ecfba67b.jpeg)
**Possible fixes**
Update electron builder as suggested in the numerous threads in snapcraft forum which has basically the same problem than flatpack because of electron, and my other issues here.

**Comment by Willyfrog** [comment] 2021-07-18 14:59
Hello and thanks for the report, I'm afraid we are not the ones submitting the app to flathub, you should probably submit an issue [in the submitters repo](https://github.com/flathub/com.mattermost.Desktop) or even to flatpack itself. as you mention this affects multiple applications based on electron and either electron or flatpack should consider what is needed for keeping compatibility.

For an update on the version, I'm afraid you'll need to wait until the next major version, we don't usually upgrade the version on dot releases unless it is really critical. The reason for that is that moving to the next one usually has breaking changes and might have unexpected behaviour.

I'm closing the issue but feel free to reopen if you think there is anything we can really do to help with this without an upgrade. Although as I mentioned this should be handled by either electron or flatpack.

**Closed by Willyfrog** 2021-07-18 14:59 UTC
