### ISSUE TITLE
"Failed to load the URL" window only shows on one team

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#253] opened 2016-08-17 21:36 UTC
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

"Failed to load the URL" window only shows on one team.
#### Steps to reproduce

Please include: 
- Tested on win10 x64 but will probably affect all
- Mattermost Desktop App version 1.3.0
- Mattermost Server version (shouldn't matter as this happens offline) 
1. Make sure you have more then one team in the mattermost desktop app
2. Close it.
3. Disconnect your PC from the network.
4. Start the mattermost desktop app
#### Expected behavior

Every team should show the "Failed to load the URL" window.
#### Observed behavior

Only the first team shows the "Failed to load the URL" window. The other one for me has a grey background with three dots as loading indicator.
#### Possible fixes

Check the implementation of the error handler and see if it somehow only affects one team.

**Comment by Razzeee** [comment] 2016-08-18 18:39
Seems to be a regression created by https://github.com/mattermost/desktop/pull/219

The problem is the 300 error happening. You can easily see this if you add some url that does not exist.

1. Add a team "htttp://www.test.test" (notice the trippel t)
2. Close the app
3. Start the app again
4. Check your test tab

Expected:
It should show the error window saying invalid URL

Observed:
It just stays blank

It's caused by:
https://github.com/mattermost/desktop/pull/219/files#diff-46044d7460b0a55fc983668900dbd4cbR316
And not only affecting the error message for invalid urls, but some of my valids too. Not exacly sure why.

**Comment by jnugh** [comment] 2016-08-21 20:11
I'm not even sure why -300 is emited here (I have to admit that I didn't check the error codes meaning) but it means invalid url.
It should emit -3 or something - might be a bug in electron... 
Seems like I need to find a different way to prevent the error page while the reload happens.

**Comment by yuya-oc** [comment] 2016-09-02 13:18
Sure, the second issue is probably caused by #219, but it doesn't seem the root cause of the first issue. I tried comment-out #219, but the first issue still happens.

Just as a workaround, I tried [`app.commandLine.appendSwitch('--disable-http-cache')`](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--disable-http-cache) at the top of `main.js`. It solved the problem, but it means electron can't use caches. It it good for this purpose?

**Comment by jasonblais** [comment] 2016-09-04 17:43
@yuya-oc  What would be the side effect?

Removed from v1.4 for now, as it's not a critical bug to fix

**Comment by yuya-oc** [comment] 2016-09-06 13:11
In the application, I feel there are no side effects. But server's load might increase because the server must send html and js for each clients every time.
My team is small, so it's not important. But if a team has many members, the load might not be able to be ignored.

**Comment by jnugh** [comment] 2016-09-06 14:11
Actually it's not that much traffic... Would worry about that as it's just static content which is being delivered)

**Comment by yuya-oc** [comment] 2016-09-07 15:40
Hmm, probably I was worrying too much. Sure, static contents cause issues like #209, so I have to worry about this first.
Just for testing, I have prepared artifacts. https://circleci.com/gh/yuya-oc/desktop/8#artifacts

**Comment by jasonblais** [comment] 2016-09-07 15:57
Thanks @yuya-oc! 

In addition to testing the error reported by @Razzeee, are there other cases we should look for?

**Comment by yuya-oc** [comment] 2016-09-09 12:31
In the artifacts, I [reverted #219](https://github.com/mattermost/desktop/compare/aba5333...1585aed) because of disabled caches. So the error should not happen.

**Comment by Razzeee** [comment] 2016-09-09 15:11
I feel like this shouldn't have a changelog, as it has only been a fix in 1.4 alpha and never changed when you see the diff to 1.3
We haven't effectively changed anything, as we've reverted now.

**Comment by yuya-oc** [comment] 2016-09-09 15:28
Probably my description is not enough. In the artifacts, I added [`app.commandLine.appendSwitch('--disable-http-cache');`](https://github.com/mattermost/desktop/compare/aba5333...1585aed#diff-1c90ff38a08209f9ebd4d05d1e43358eR14) not only reverting the PR. So I modified the changelog.

**Comment by Razzeee** [comment] 2016-09-09 15:48
Do we need that if platform sends the right cache invalidation? Did I miss understand that part?

**Comment by yuya-oc** [comment] 2016-09-12 15:01
Probably no. Now the server sends cache-expiration info in http header, so we should not ignore it. For now, I feel that reverting #219 (PR #275) is enough. It should fix [the second problem](https://github.com/mattermost/desktop/issues/253#issuecomment-240816346) of this issue.

For now, I feel the original problem is not critical because the first tab correctly shows disconnection error and it's active when launching the app. If the user meets this problem in the second tab, it can be avoided by reloading.

**Comment by yuya-oc** [comment] 2017-01-16 13:04
@jasonblais I took a look this issue again. I'm not sure though why, it seems that v3.4.1 and v3.5.0 don't have this problem on both of Windows 10 and macOS 10.12. Would you confirm?

**Comment by jasonblais** [comment] 2017-01-16 13:08
Thanks @yuya-oc! I can verify the issue seems resolved for me too on Windows 10, v3.5.0.

Closing the issue,

**Closed by jasonblais** 2017-01-16 13:08 UTC
Labels: All Platforms, Bug
