### ISSUE TITLE
Blocked Gitlab Login Button

### ISSUE THREAD

**Issue by stlvc** [mattermost/desktop#1271] opened 2020-04-20 06:45 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Login via GitLab doesn't work because WebView is blocked from navigating to the GitLab login page.

**Environment**
- Operating System: MacOS 10.14.6
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.21.0

**Steps to reproduce**
- fresh installation of the Mattermost MacOS Desktop Client
- configure a server to connect to
- when presented with the login page, click the "GitLab" button

**Expected behavior**
- should lead to the GitLab authentication page, allowing authentication via GitLab

**Observed behavior**
- Client does nothing
- Developer Console prints: "Prevented desktop from navigating to: https://......"

**Possible fixes**

Sorry, I wasn't able to investigate the issue further yet. Let me know if I can provide additional context. For now, this renders the Desktop Client unusable for me.

**Comment by Willyfrog** [comment] 2020-04-20 08:00
can you provide some extra context? feel free to contact me on the community server if you feel the info is sensitive.
I've tested on one of our test servers and it does navigate correctly to the gitlab login page, but yours might be setup differently.

**Comment by stlvc** [comment] 2020-04-20 08:34
Hi @Willyfrog - thanks for the quick reply. I just checked with a colleague of mine with the same setup, works for him. So I assume that the problem is very specific to my own setup. I'll investigate further and post the solution if I can find one, but the Client doesn't seem at fault.

**Comment by stlvc** [comment] 2020-04-20 09:00
I've managed to solve the issue, but I'm not sure whether I should close it or not. It seems like my connection settings went corrupt after the update to 4.4.0. Just reinstalling the Client wasn't enough, since the settings persist after a simple deletion of the app. The following steps solved the issue for me:

- remove the Server from configuration
- remove the Client application
- install the Client
- add the Server configuration again

Feel free to close the issue, but it might be interesting to investigate this behaviour. Maybe corrupted cache files for settings (if my assumption is correct) should at least give some feedback to the user?

**Comment by Willyfrog** [comment] 2020-04-20 10:51
Glad you solved it, the thing is that unless we had a consistent behaviour, we can't figure it out as we might be chasing ghosts.

For now, I'll close the issue, it can be reopened if we get any new info or a reproducible path.

**Closed by Willyfrog** 2020-04-20 10:51 UTC

**Comment by ronin-gw** [comment] 2020-05-19 18:48
Just sharing my case, I encountered this problem in the similar environment (MacOS 10.15.4, Desktop App 4.4.1, Mattermost Server 5.12.4).

When I upgraded Client application into 4.4.2, the problem did not solved. However, when I added the same Server configuration which was in trouble, I can established a connection via the additional configuration.
Then, unexpectedly, the first configuration have been working correctly again.

**Comment by Willyfrog** [comment] 2020-05-20 13:11
I found the problem of this while working on a different issue. It'll be fixed once https://github.com/mattermost/desktop/pull/1295 is deployed

**Comment by stlvc** [comment] 2020-05-20 13:21
Thanks for resolving the issue and keeping us in the loop!

**Comment by pauloacosta** [comment] 2021-01-11 15:12
This same problem reported here happens to me on a machine using Windows 10.

**Comment by imcitius** [comment] 2022-01-17 15:30
Observed this when MM servers is configured as http://, but GitLab login screen is accessed by http`S`://.

**Comment by pedzel10** [comment] 2022-10-01 23:36
I had the same issue and adding "https" instead of "http" solved it for me

**Comment by zurKreuzigungLinks** [comment] 2023-01-17 12:33
Same thing here, on ubuntu. None of the above works for me.

**Comment by teamfighter** [comment] 2023-02-15 17:11
+1 for that issue, tham thing for latest mattermost desktop. Web interface works fine.

**Comment by hensel-f** [comment] 2023-04-04 08:34
I also have the same issue with the latest version of the mattermost desktop client installed on pop-os.
Is there any fix for this?

**Comment by NandoTheessen** [comment] 2023-04-11 05:19
Same issue here!

**Comment by ageekhere** [comment] 2023-04-26 04:26
I have the same issue, in mattermost desktop app white screen when logging in with gitlab

**Comment by gerekon** [comment] 2025-02-24 14:37
same issue on Ubuntu 24.04.
Server version: 8.1.6
Client version: 5.11.0
