### ISSUE TITLE
Introduce auto updates

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#147] opened 2016-05-21 18:06 UTC
For auto updates to work, we will need a server running 
- [ ] https://github.com/ArekSredzki/electron-release-server
or
https://github.com/Aluxian/squirrel-updates-server

- [ ] Update the application code acordingly

**Comment by Razzeee** [comment] 2016-06-22 07:09
https://github.com/mattermost/desktop/pull/162

**Comment by Razzeee** [comment] 2016-07-05 10:16
This seems to be an duplicate of #15

**Comment by jasonblais** [comment] 2016-07-05 14:01
That's correct @Razzeee, I'll close this issue as a duplicate of #15 and have carried over your initial comment there.

**Closed by jasonblais** 2016-07-05 14:01 UTC
Labels: duplicate
