### ISSUE TITLE
Tray Icon on Linux should raise/hide main window on left click and only show context menu on right click

### ISSUE THREAD

**Issue by c0deright** [mattermost/desktop#1937] opened 2021-12-30 12:18 UTC
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Tray icon on Linux doesn't distinguish between left/right click resulting in one extra mouse click in the context menu to show the application window.

**Environment**
- Operating System: Ubuntu Focal 20.04 LTS
- Mattermost Desktop App version: 5.0.2
- Mattermost Server version: 6.2.1

**Steps to reproduce**
- Install Linux Desktop App
- Connect to at least one Server
- In File/Setting enable *Leave app running in notification area when application window is closed*
- Click the tray icon with left/right mouse button

**Expected behavior**
- right mouse button click on tray icon: context menu opens
- left mouse button click on tray icon:
  - when application window is hidden: show the application window
  - when application window is not hidden: hide the application window

**Observed behavior**
- left mouse button click on tray icon opens context menu like right mouse button click does
- to show the application window when it's hidden you need two mouse clicks:
  - one to open the context menu
  - one to select the the Mattermost server in the contect menu

**Why not a feature request?**
- It's really bugging to always have to click twice and even move the mouse pointer in between clicks. It's all about efficiency.
- People migrating from XMPP via Pidgin (like me) might be bugged.

**Comment by devinbinnie** [comment] 2022-01-04 16:29
This is a duplicate of [this](https://github.com/mattermost/desktop/issues/950) issue, closing.

**Closed by devinbinnie** 2022-01-04 16:29 UTC
