### ISSUE TITLE
Crash when downloading an image (`TypeError: s.nativeImage.createThumbnailFromPath is not a function`)

### ISSUE THREAD

**Issue by SimonWoidig** [mattermost/desktop#3223] opened 2024-11-18 08:31 UTC
#### Summary

Mattermost crashes when trying to download an image.

#### Steps to reproduce

1. Click on any image in a chat, this opens the thumbnail
2. Click on download in the top right corner
3. See error as Mattermost crashes, the download is cancelled

#### Operating System

Fedora 39 KDE Plasma with Linux kernel 6.11.5-100.fc39.x86_64

#### Mattermost Server Version

Mattermost Version: 10.0.1
Database Schema Version: 125
Build Number: 11258452730

#### Expected behavior

The image downloads without a problem.

#### Observed behavior

Mattermost crashes, download is cancelled

#### Log Output

```
Application: Mattermost 5.9.0
Platform: Linux 6.11.5-100.fc39.x86_64 x64
TypeError: s.nativeImage.createThumbnailFromPath is not a function
    at C.formatDownloadItem (/app/main/resources/app.asar/index.js:2:258218)
    at C.upsertFileToDownloads (/app/main/resources/app.asar/index.js:2:255626)
    at C.doneEventController (/app/main/resources/app.asar/index.js:2:256982)
    at DownloadItem.<anonymous> (/app/main/resources/app.asar/index.js:2:254788)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)
```

#### Additional Information

Search through Jira returned this ticket: https://mattermost.atlassian.net/issues/MM-60232
The ticket is for an older version and the bug seems a bit different aswell.

Image of the crash: 
![387127913-a03d39b0-4387-4c20-80b6-bcff7ef7683b](https://github.com/user-attachments/assets/f3c8b278-442e-4943-963d-e7cbbf32970f)

**EDIT**: Mattermost says that the download was cancelled but the image gets saved anyway.

**Comment by devinbinnie** [comment] 2024-11-25 14:09
Duplicate of https://github.com/mattermost/desktop/issues/3129 which was fixed in v5.9.1 and v5.10. Closing.

**Closed by devinbinnie** 2024-11-25 14:09 UTC
