### ISSUE TITLE
URLs from notification pop-ups are broken on Linux

### ISSUE THREAD

**Issue by srustagi** [mattermost/desktop#2377] opened 2022-11-11 19:34 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
URLs from notification pop-ups are broken; only containing as many characters as are able to fit in the pop-up itself, rather than the full URL.

**Environment**
- Operating System: Ubuntu 22.04.1 LTS (jammy)
- Mattermost Desktop App version: Version 5.2.0 (commit: 023ac00)

**Steps to reproduce**
Recieve a message containing a URL, and open that URL via the notification pop-up.
**Expected behavior**
URL links to the full URL contained in the original message.
**Observed behavior**
URL links to only what displays in the notification (https://goog... instead of https://google.com)

**Possible fixes**
I have no idea where the string message for a notification is actually handled (where it checks to see whether any content is a URL or not), but I believe it *might* be [here](https://github.com/mattermost/desktop/blob/cf647ce3e98d49317d5c7b2a3723efd0d120b101/src/main/i18nManager.ts#L11)

**Comment by devinbinnie** [comment] 2022-11-14 14:55
Duplicate of https://github.com/mattermost/desktop/issues/1067

**Closed by devinbinnie** 2022-11-14 14:55 UTC
