### ISSUE TITLE
URL blocks input field

### ISSUE THREAD

**Issue by janhaertel** [mattermost/desktop#880] opened 2018-10-25 09:49 UTC
Sometimes when I **focus** the **chat window**, a **URL** is displayed in the **bottom left** and it **won't disappear**. This is really annoying because I can't completely see the text I'm typing.

**Comment by amyblais** [comment] 2018-10-29 16:17
Hi @janhaertel,

Can you help with more details on your Environment
- Operating System
- Mattermost Desktop App version: X.X.X - See Help > Version Number
- Mattermost Server version: X.X.X - See Mattermost Menu > About Mattermost, where Mattermost Menu can be accessed by clicking on three dots next to your profile picture

**Comment by janhaertel** [comment] 2018-10-30 07:30
Windows 10
Mattermost Desktop Version 4.12
Mattermost-Version: 5.2.0

**Comment by janhaertel** [comment] 2018-10-30 07:31
I'm still trying to find the exact cases when this happens and will append them here, fortunately this bug doesn't come up too often.

**Comment by janhaertel** [comment] 2018-11-05 14:51
It seems to happen if the mouse hovers over a date next to the user name but not everytime :/

**Comment by STRML** [comment] 2018-11-20 16:40
Dupe of #615, #610, #689

**Comment by amyblais** [comment] 2019-02-06 01:15
Closing as a dup of https://github.com/mattermost/desktop/issues/909

A Jira ticket for this is here: https://mattermost.atlassian.net/browse/MM-13995,

**Closed by amyblais** 2019-02-06 01:15 UTC
