### ISSUE TITLE
No dot or notifications present in the Gnome notifications area

### ISSUE THREAD

**Issue by echosa** [mattermost/desktop#810] opened 2018-05-21 17:30 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When a Mattermost desktop app notifications comes through while Mattermost is in the background, no dot or notification is added to the Gnome notifications area (i.e. the pop-up when you click the date/time at the top of the screen).

**Steps to reproduce**
- Pop!_OS (`$ uname`: `Linux pop-os 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)
- Mattermost Desktop App version `4.0.1`
- Mattermost Server version `4.0.0 (4.0.1)`

- Open Mattermost and login to a server.
- Focus some other program to put Mattermost in the background.
- Receive a notification from Mattermost.

**Expected behavior**
There should be a dot next to the date/time and, when clicked, the notifications popup should have a notification.

**Observed behavior**
There is not dot nor notifications in the pop-up.

![screenshot from 2018-05-21 12-25-30](https://user-images.githubusercontent.com/133786/40320815-8728af9e-5cf2-11e8-82ab-2e3c50d4f2cc.png)

**Comment by cassidyjames** [comment] 2018-05-21 17:32
It seems the cause for this is that Mattermost is expiring or withdrawing its notifications, which cases them to disappear from GNOME Shell. 

This is probably due to a mismatch in APIs between web notifications and GNOME notifications. On the web, withdrawing means it doesn't appear on screen. In GNOME, that means it won't appear in the notifications area any more (and there's no way to determine how long a notification displays on screen).

**Comment by jasonblais** [comment] 2018-05-22 11:33
@cassidyjames By expiring/withdrawing, do you mean the notifications aren't persistent and disappear after a few seconds?

**Comment by jasonblais** [comment] 2018-05-23 01:12
@cassidyjames Makes sense. If we fixed this issue, it should also cover your report here? https://github.com/mattermost/desktop/issues/539

If so, I can migrate your report there so we have all the information part of the issue.

**Comment by cassidyjames** [comment] 2018-05-23 15:25
@jasonblais I'm unfamiliar with how Windows or macOS use notifications, but it looks like it might be the same issue.

**Comment by jasonblais** [comment] 2018-05-23 18:10
@echosa @cassidyjames I've ported your issue description to the issue https://github.com/mattermost/desktop/issues/539

If it's not fixed with that issue, we can reopen this ticket.

Thanks for the follow-ups!

**Closed by jasonblais** 2018-05-23 18:10 UTC
Labels: Linux, Priority 4
