### ISSUE TITLE
Windows, desktop app: CTRL/CMD+Q shortcut does not work

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#692] opened 2018-01-23 18:11 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
CTRL/CMD+Q shortcut does not work on Windows (Desktop app v.4.0.0, Server v.4.6.0)

**Steps to reproduce**
Open pre-release desktop app, press CTRL/CMD+Q which should quit the desktop app.

**Expected behavior**
Desktop app should quit.

**Observed behavior**
Nothing happens.

**Comment by yuya-oc** [comment] 2018-01-24 12:25
Reproduce while I'm opening a context menu though, I think this case is not a bug. Explorer.exe can't close a window with `Ctrl+W` while opening a context menu.

@amyblais What situation did the shortcut not work?

**Comment by amyblais** [comment] 2018-01-24 14:04
@yuya-oc It works in the web browser, but not in the desktop app. I just have the desktop app open, I press Ctrl+Q, and nothing happens (on the desktop app on windows).

**Comment by yuya-oc** [comment] 2018-01-24 14:52
@amyblais Hmm...this part had been implemented at #187, so I feel it doesn't make problem now.

- I can assume another situation: the app window doesn't have focus. Is the window actually activated?
- What about other shortcuts? For example, `Ctrl+R` to reload.

**Comment by amyblais** [comment] 2018-01-24 15:00
@yuya-oc I tried again and it doesn't work. I tested some other shortcuts and they work (such as Ctrl+R and Ctrl+Shift+A). Perhaps we see if #187 fixes it and we can test in RC-2.

**Comment by jasonblais** [comment] 2018-01-24 15:01
https://github.com/mattermost/desktop/pull/187 is actually an old PR from 2016.

@amyblais If you go to the help menu bar at the top of the app window, select File, then Exit, does the app quit?

**Comment by amyblais** [comment] 2018-01-24 15:02
Yes it quits when I do that. @jasonblais

**Comment by jasonblais** [comment] 2018-01-24 15:52
Hm. @amyblais Maybe try downloading the latest version from https://about.mattermost.com/download, and see if it reproduces?

That way at least we'll know if it's a regressions/new issue.

**Comment by amyblais** [comment] 2018-01-24 15:58
Did that and everything that I've tried above is the same. @jasonblais

**Comment by jasonblais** [comment] 2018-01-24 16:06
Thanks! So this doesn't appear to be a regression.

@yuya-oc This one is fine to push and not fix in v4.0. But wondering if there's anything else we can do to try and investigate?

@yuya-oc Let's also cut 4.0.0-RC2.

**Comment by yuya-oc** [comment] 2018-01-25 11:42
>> If you go to the help menu bar at the top of the app window, select File, then Exit, does the app quit?

> Yes it quits when I do that.

From this fact, I think our javascript is working well once it's triggered. So I feel the problem is the shortcut is not caught by electron. However in such case, other shortcuts should not work as well.

So we need to get logs in order to know what is working or not.

**Comment by jasonblais** [comment] 2018-01-25 14:42
> So we need to get logs in order to know what is working or not.

Can you help provide the steps for @amyblais to get the logs?

**Comment by yuya-oc** [comment] 2018-01-25 14:56
@jasonblais I have noticed a strange thing when I add a log function for `Ctrl+Q`. The app finishes, but its log doesn't appear.
Perhaps #187 might not be enough for Windows. I'll create a PR to test new code.

**Comment by jasonblais** [comment] 2018-03-20 11:58
Closing for now as per comments in #695

**Closed by jasonblais** 2018-03-20 11:58 UTC
Labels: Bug, More Information Needed, Priority 4, Windows
