### ISSUE TITLE
Increasing the font size causes rendering issues on next restart

### ISSUE THREAD

**Issue by nerfologist** [mattermost/desktop#334] opened 2016-10-06 08:05 UTC
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

If I increase the font size (CTRL+-), quit the Mattermost Desktop application and restart it, the content will not occupy the entire UI space, but show a wide white (empty) margin on the right and bottom sides.
#### Steps to reproduce
- Open the Mattermost desktop application for Linux.
- Increase the font size using the CTRL-+ shortcut.
- Exit the application (CTRL+Q).
- Open the application again.

Please include: 
- Operating System: Linux Mint 17.3 Cinnamon 64bit
- Mattermost Desktop App version (See **Help > Version Number**): 3.4.0 (also present in 3.4.1)
- Mattermost Server version (See **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture): Mattermost Team Edition 3.4.0 (database: postgres)
- Clear steps to reproduce the issue: see above
#### Expected behavior

The UI scales and resizes properly.
#### Observed behavior

A wide white border is displayed in the right and bottom side of the rendering area. No errors are displayed.
#### Possible fixes

Workaround: if you reduce the font size again (CTRL -), and restart the application, the problem is fixed.

**Comment by yuya-oc** [comment] 2016-10-06 13:18
Reproduced on macOS 10.12. Probably it's a bug of electron. electron/electron#7375

![zoom](https://cloud.githubusercontent.com/assets/1412057/19153771/d1c528dc-8c12-11e6-9c5e-5b5ebd76bb6a.png)

**Comment by jasonblais** [comment] 2016-10-07 21:28
I saw a note that the [Brave browser (built off of Electron) doesn't seem to have the issue](https://discuss.atom.io/t/why-does-webview-reset-its-zoomfactor-on-url-navigate/27064/4), 

something to consider looking into?

The zoom in/out functions are a little useless at the moment, at least in their current form

**Comment by yuya-oc** [comment] 2016-10-08 07:40
As far as reading that, our issue looks a little different. In our case, the zoom level is correct, but only the region is incorrect. Just for reference, I tried `brave/electron-prebuilt`. But I could not execute the app. 
And, their changes seems not to be well-documented, so I feel it's not good choice even if the folk worked.

**Comment by jasonblais** [comment] 2016-10-22 18:05
Update:

With https://github.com/mattermost/desktop/pull/240, this issue is partially fixed on `master` branch -- the zoom level is properly updated if the focus is inside the app window.

The issue continues to reproduce after clicking on the tab bar and attempting to use the zoom shortcuts, for instance.

**Comment by siebertm** [comment] 2017-08-14 13:18
I was able to reproduce the issue with

OS: Ubuntu 16.04 LTS
MMD: 3.7.0
MMS: 4.0.0 (4.0.2)

Steps to reproduce: 

* delete `~/.config/Mattermost/Preferences`
* Start Mattermost Desktop
* zoom one step (Ctrl++)
* quit the app (Ctrl+Q)
* Start again

=> Problem, as described above.

To fix the problem again, you need quit the app, then remove `~/.config/Mattermost/Preferences`. 

After that, starting the app again leaves you 'clean-slate' with default zoom factor, but when you change zoom, then restart -> same problem.

I didn't have the issue with MMD < 3.7.0, it wasn't remembering the zoom factor until 3.7.0.

**Comment by jasonblais** [comment] 2017-10-17 19:06
@yuya-oc I moved this issue to the v3.8 milestone after the above repro steps, but wondering if I should move it back to `Unscheduled` if it's an Electron issue?

**Comment by yuya-oc** [comment] 2017-10-18 15:37
@jasonblais I'm not sure there is workaround because zoom in/out is strongly depends on Electron's implementation. However investigation is good to know current behavior since Electron was upgraded.

**Closed** 2017-10-31 17:43 UTC
Labels: All Platforms, Bug, Electron
