### ISSUE TITLE
Message not marked as read

### ISSUE THREAD

**Issue by tyh94** [mattermost/desktop#834] opened 2018-07-03 11:20 UTC
Message marked as read only when you read it second time. MacOS

**Comment by yuya-oc** [comment] 2018-07-03 15:22
Hi @tyh94, thanks for reporting.

Would you write about your environment? It would be helpful for us.

- Desktop app version
  ([Help] > [Version Number] of the menu bar)
- Mattermost server version
  ([Mattermost Menu] > [About Mattermost], where [Mattermost Menu] can be accessed by clicking on three dots next to your profile picture)

**Comment by tyh94** [comment] 2018-07-04 03:55
App version 4.0.1 (4.0.1.45)

Mattermost Enterprise Edition

Mattermost Version: 4.10.0
Database Schema Version: 4.10.0
Database: postgres

**Comment by esethna** [comment] 2018-08-07 19:05
@tyh94 I am unable to reproduce this. Does this also occur if you try to use the browser to access your Mattermost server? Have you tried updating to Desktop app v4.1 and seeing if that resolved your issue?

**Comment by jazzzz** [comment] 2018-08-13 14:47
Same issue on Mattermost Desktop 4.1.2, Mattermost server 5.0.2, on Windows 10.
When I am on a channel and there is a notification in this channel, if I click on the input box, the channel notification does not disappear. It only disappears if I leave the focus and I click on the input box a second time.

**Comment by lkraav** [comment] 2018-09-03 10:00
Our team is experiencing this daily on both Windows and OS X clients (4.1.2), but my Linux client has been fine throughout.

What other information is needed for diagnosis?

We already know that clicking into another channel and back resets the "unread" counter.

**Comment by lkraav** [comment] 2018-09-03 12:50
> Would you provide a screenshot of left-hand sidebar (Channel/DM list) when you are experiencing the problem?

We have client project names there. Any way to do without? I can say, all other channels are marked all read. We have a total of maybe 6 channels thus far.

**Comment by yuya-oc** [comment] 2018-09-03 13:04
Simply you can cover channel names by editing the screenshot. First letters of Channel/DM items are enough for me.

**Comment by tralafiti** [comment] 2018-09-11 08:08
This problem also exists the other way around: There are new unread messages in a channel but the sidebar doesn't reflect this. When I open the channel it includes the orange "new message" separator, so it clearly knows there are unread messages. 

macOS 10.13.6
Client: Mattermost Version 4.1.2 (4.1.2.46)
Server: Mattermost Team Edition Version: 4.7.1 (4.7.3), Database: mysql

**Comment by amyblais** [comment] 2019-02-13 19:02
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14173.

**Comment by ducttapecoder-vt** [comment] 2019-03-14 16:04
I can confirm a similar issue. I generally minimize the desktop client (v4.1.2 windows 10 1809) with the Town Square public channel open. When I get a notification, I maximize it, but sometimes the channel is marked as read after a few seconds and other times I have to click a different channel and back again to get it to indicate read.

Windows 10 1809
Desktop Client v.4.1.2
Server: MatterMost EE 5.3.1
Server DB schema: 5.3.0
DB: mysql

P.S. It would be really nice if I could right click a channel and indicate "mark as read" or "Mute channel" to hide unread notifications.

**Comment by amyblais** [comment] 2019-06-21 14:52
This has been fixed in servers v5.8 and v5.9 releases.

**Closed by amyblais** 2019-06-21 14:52 UTC
