### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by markgookin** [mattermost/desktop#605] opened 2017-09-28 23:05 UTC
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**

**Expected behavior**
Not a blank screen

**Observed behavior**
Blank screen

**Possible fixes**

**Comment by yuya-oc** [comment] 2017-09-29 11:03
Could you describe in more detail? Now we can't understand the problem and can't tell any suggestion.
 (Please see also [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md#write-detailed-information)).

Please include: 
- Operating System
- Mattermost Desktop App version (See **Help > Version Number**) 
- Mattermost Server version (See **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture) 
- Clear steps to reproduce the issue (Or, the situation you met the problem)

**Comment by markgookin** [comment] 2017-09-29 13:02
I’m running OS 10.12.6 in parallels.  The problem looks to be 3D acceleration – Google Chrome was having a similar issue that was resolved by disabling acceleration in its settings.

Towers seems to be working, so I’ll just be using it instead of github desktop.

Thanks,
Mark

**Comment by jasonblais** [comment] 2017-10-01 19:30
@markgookin Are you having an issue with the Mattermost Desktop App? Or another app?

**Comment by markgookin** [comment] 2017-10-01 19:35
I was having a problem with the Mattermost Desktop App – the resolution was to user another app.
Mark

**Comment by jasonblais** [comment] 2017-10-02 12:48
Thanks @markgookin, 

If you'd be able to provide more information about your setup including the following, it'll help us investigate the problem

- Operating System
- Mattermost Desktop App version (See **Help > Version Number**) 
- Mattermost Server version (See **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture) 
- Clear steps to reproduce the issue (Or, the situation you met the problem)

**Comment by yuya-oc** [comment] 2017-10-02 15:11
@markgookin If the problem is actually caused by 3D acceleration, would you try using `--disable-gpu` command line option?

**Comment by jasonblais** [comment] 2017-10-10 12:52
I'll close this issue for now as it's related to 3D acceleration.

@markgookin if you run `--disable-gpu`, that might resolve the issue for you (it did for a few people in the past).

**Closed by jasonblais** 2017-10-10 12:52 UTC
Labels: More Information Needed
