### ISSUE TITLE
Build from source archive impossible

### ISSUE THREAD

**Issue by alerque** [mattermost/desktop#1638] opened 2021-06-26 14:47 UTC
Building from the `git archive` generated source download from the last tagged release (v4.7.0) is not possible. Somewhere deep in the webpack step it assumes the build is happening from a Git clone and runs `git rev-parse --short HEAD`.

Please either:

* Add a source distribution asset to releases with the necessary meta data baked in
* Add the special repo metadata that will allow `git archive` tag names to be identified and script to use that.
* Script in such a way this is an optional step.
* Script in a way that can be set externally with a variable or file at build time.

At this time I am unable to properly update the Arch Linux packages because of this.

**Comment by amyblais** [comment] 2021-06-28 12:10
@Willyfrog ^

**Comment by Willyfrog** [comment] 2021-06-28 12:14
@amyblais thanks for the heads up!

@alerque hello and thanks for reporting, we made some changes to have a daily build and we added a git hash to track the daily builds. This seems to cause a problem to some users like you that build from source, so we created a [help wanted issue](https://github.com/mattermost/mattermost-server/issues/17393) to try and fix that.

**Comment by amyblais** [comment] 2021-09-07 17:39
I'll close this as a duplicate of the Help Wanted Issue,

**Closed by amyblais** 2021-09-07 17:39 UTC
