### ISSUE TITLE
macOS: Not able to access microphone, video, screen recording permissions

### ISSUE THREAD

**Issue by jf-jflo** [mattermost/desktop#1330] opened 2020-06-23 00:36 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

When using the macos mattermost desktop app, I am unable to use Jitsi Video Conferencing since the mattermost app does not request the webcam, microphone, or screen recording permissions. 

**Environment**
- Operating System: macOS Catalina 10.15.5
- Mattermost Desktop App version: 4.4.2 
- Mattermost Server version: 5.23.1 

**Steps to reproduce**
1. Start a Jitsi Meeting using the Jitsi Plugin from here: https://github.com/mattermost/mattermost-plugin-jitsi with "Embed Jitsi video inside Mattermost" set to true in system console plugin management
2. Click on the generated Jitsi Meeting link
3. Jitsi pops up within the mattermost app

**Expected behavior**
Prompt user to allow permissions for webcam, microphone, and screen recording (to allow for screensharing). Able to use webcam, talk to others, and share screen.

**Observed behavior**

Displays the following error and does not prompt user for webcam, microphone, or screen recording permissions.
![Screen Shot 2020-06-22 at 5 20 11 PM](https://user-images.githubusercontent.com/67297761/85347636-fc181500-b4ad-11ea-8f60-618ed2ec8e12.png)

**Possible fixes**

Unknown

**Comment by amyblais** [comment] 2020-06-24 14:00
@rollitoJFLO Do you see the same issue on desktop v4.5?

**Comment by rollitoJFLO** [comment] 2020-06-24 19:15
Hello, I wasn't even aware there was a new version. Downloaded and yes still same issue

**Comment by amyblais** [comment] 2020-06-24 19:23
I was browsing through the issues in the Jitsi plugin repo and noticed that our QA team just opened an issue for this, so the team will be triaging the issue: https://github.com/mattermost/mattermost-plugin-jitsi/issues/120.

**Comment by r3ggi** [comment] 2020-06-25 08:38
Hey,

In order to be able to request for camera & microphone permissions you have to sign the client with the following entitlements:
- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_camera
- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_microphone

BTW. Mattermost uses also an excessive entitlement that has bad security impact - `com.apple.security.cs.disable-library-validation`. You can read more about this entitlement there -> https://objective-see.com/blog/blog_0x56.html

**Comment by dpanic** [comment] 2020-06-25 12:56
Probably duplicate of https://github.com/mattermost/desktop/issues/1288

Audio and Video permisions are solved in this PR https://github.com/mattermost/desktop/pull/1311

Origin permission must be obeyed here.

**Comment by rollitoJFLO** [comment] 2020-06-26 00:02
happy to test any possible solutions as we're looking to replace our current chat system with mattermost

**Comment by rollitoJFLO** [comment] 2020-06-26 02:34
i was able to clone, build, and test and video and microphone permissions now work. The only thing that still doesn't work is screen sharing

**Comment by dpanic** [comment] 2020-06-26 06:52
> i was able to clone, build, and test and video and microphone permissions now work. The only thing that still doesn't work is screen sharing

Well that screen sharing thing I will handle later, but I have it in my todo list

**Comment by rollitoJFLO** [comment] 2020-06-26 19:50
awesome, thank you for the help

**Comment by diego-caceres** [comment] 2020-08-20 17:05
Hi everyone, just a question, I see that a PR has been merged to fix this, is that supposed to be in the latest release (4.5.2)? 
I have that version and I still have the issue that the Mattermost Mac App didn't request for camera or microphone permission.

Thanks!

**Comment by dpanic** [comment] 2020-08-25 11:52
> Hi everyone, just a question, I see that a PR has been merged to fix this, is that supposed to be in the latest release (4.5.2)?
> I have that version and I still have the issue that the Mattermost Mac App didn't request for camera or microphone permission.
> 
> Thanks!

Product manager set milestone to 4.6.0. I don't know when that will happen.

https://github.com/mattermost/desktop/pull/1311

**Comment by bozicm** [comment] 2020-08-27 05:48
Camera doesn't work in my case too:

    Operating System: Fedora 32
    Mattermost Desktop App version: 4.5.2
    Mattermost  Server version: 5.24.2 (came with GitLab)

**Comment by dpanic** [comment] 2020-11-20 14:21
> Camera doesn't work in my case too:
> 
> ```
> Operating System: Fedora 32
> Mattermost Desktop App version: 4.5.2
> Mattermost  Server version: 5.24.2 (came with GitLab)
> ```

Works on 4.6.1 Client APP...
But you must open url as /trusted and must be same origin as mattermost...

I solved this by enabling NGINX proxy to Jitsi.

```
   location ~ /c/(.*)$ {
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;

       proxy_buffers 256 32k;
       proxy_buffer_size 32k;
       proxy_busy_buffers_size     256k;
       proxy_read_timeout 600s;

       proxy_http_version 1.1;
       proxy_pass https://meet.salestrekker.com/$1;

       add_header Alternate-Protocol 443:h2;
    }
```

**Comment by dpanic** [comment] 2020-11-20 14:38
I just tested following:

Ubuntu 20.04
Mattermost Desktop App version: 4.6.1
Mattermost  Server version: 5.29.0
**Camera: NOT WORKING**
Microphone: WORKING


MacOS: 10.15.7
Mattermost Desktop App version: 4.6.1
Mattermost  Server version: 5.29.0

**Camera: NOT WORKING
Microphone: NOT WORKING**

**Comment by estebanz01** [comment] 2021-02-23 22:17
just echoing what I posted in https://github.com/mattermost/mattermost-plugin-jitsi/issues/120 it works on version 4.6.2 with MacOS Cataline (10.15.17)

**Comment by devinbinnie** [comment] 2021-12-09 20:59
Closing as this seems to be working with version v4.6.2
Feel free to re-open if this still exists in v5.0+

**Closed by devinbinnie** 2021-12-09 20:59 UTC
