### ISSUE TITLE
Upgrade from 4.6.1 to 4.7.0 causes nginx bad gateway

### ISSUE THREAD

**Issue by Tampa** [mattermost/desktop#1670] opened 2021-07-23 09:17 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Upgrade from 4.6 to 4.7 causes bad gateway on nginx

**Environment**
- Operating System:
- Mattermost Desktop App version: 4.6.0 
- Mattermost Server version: 5.37.0 

**Steps to reproduce**

Install 4.6.1 and connect to server that uses nginx as reverse proxy
Install 4.7.0 on top and attempt to connect to the same server

**Expected behavior**

Connection working just as in browser

**Observed behavior**

Shows main window 502 bad request from nginx on windows, on mac just repeats loading animation
Nginx error log states: connect() failed (111: Connection refused) while connecting to upstream, GET /api/v4/websocket?connection_id=&sequence_number=940 HTTP/1.1
along with an error simply HTTP / HTTP/1.1

Log only shows "timeout expired will show the browserview"

**Possible fixes**

Nuked the appdata folder for Mattermost on windows and re-added the server, works fine now
Suspect something between those two client versions changed in config or perhaps something in cookies or network state. Files touched in appdata are: bounds-info.json, Network Persistent State, config.json, Preferences, TransportSecurity, app-state.json, Cookies, Cookies-journal. Removing any of these forcing a refresh might work. Might be a good idea to force a cache clear or refresh of some data on major version upgrades to prevent this in future.

**Comment by Willyfrog** [comment] 2021-07-23 14:58
hello and thanks for reporting! Also glad that you got it back into working state in no time.

Sadly your solution is the only one I know for the time being, we might consider some sort of utility to help do this process if it reproduces frequently as it probably is caused by some cached data not being cleaned properly.

**Comment by Tampa** [comment] 2021-07-23 15:04
An option to "Perform clean install" in the installer might make the most sense in that it would delete pretty much all cached data leaving only the minimum needed to reconnect to the server.

I expect at least some reproducibility given I was informed of this issue by a mac user and could replicate it on Win10 myself, so it seems to transcend operating systems already. I do not have all that many users on the server, but will keep my ears up if those do report also running into this problem.

Generally a full clear of old data between major version changes might not be a bad idea given the cons of increased traffic and having to re-cache images somewhat outweighs the pro of actually being able to connect at all, at least from my point of view. :)

**Comment by Willyfrog** [comment] 2021-07-24 09:28
I've created a [ticket](https://mattermost.atlassian.net/browse/MM-37379) for that

**Comment by devinbinnie** [comment] 2021-12-09 22:19
Closing as we have a ticket internally to deal with the clear data script. Thanks for the suggestions :)

**Closed by devinbinnie** 2021-12-09 22:19 UTC
