### ISSUE TITLE
Ctrl+Q does not minimize to the system tray

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#235] opened 2016-08-10 16:39 UTC
I confirm (by marking "x" in the [ ] below): 

- [ x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [ x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [ x] This is a product defect issue that can be reproduced using the steps listed below.
- [ x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Closing the application with Ctrl+Q does not minimize to the system tray.

#### Steps to reproduce

- Operating System: Windows 7 Pro
- Mattermost Desktop App version: 1.3.0
- Mattermost Server version (See Main Menu > About Mattermost) — There is no "About Mattermost" in the main menu.

Steps to reproduce the issue:
1) Open the Mattermost desktop application
2) Press Ctrl+Q to close it

#### Expected behavior

Mattermost minimizes to the system tray.
(The changelog states for v1.3.0: "The app now minimizes to the system tray when closed.")

#### Observed behavior

Mattermost is completely closed and does not appear in the system tray.

**Comment by jasonblais** [comment] 2016-08-12 13:42
Thanks @nmatt for the report!

There are actually two ways to "close/quit" the app:
1) *Close the app* by
   - clicking on the "X" on the top right corner of the app
   - pressing `ALT+F4`
   - right-clicking the taskbar icon and selecting `Close window`
2) *Quit the app* by
   - clicking `File > Quit` from the menu bar
   - pressing `CTRL+Q`

The expected behaviour is that closing the app minimizes it to the system tray, but quitting the app completely closes the app removing it from the system tray.

PS: The *About Mattermost* dialog can be found by clicking on the three dots next to your profile name on the top left, which opens the *Mattermost Main Menu*.

**Comment by nmatt** [comment] 2016-08-12 14:12
I think it's mostly a matter of terminology. On Windows, normally "closing an application" denotes the same thing as "quitting an application". The distinction that is meant here with Mattermost would be more commonly worded as the distinction between "closing a window" (or "closing the application window") and "exiting the application". "Quit" is the standard terminology on MacOS, but on Windows it's "Exit". So when describing the minimize-to-system-tray feature, it would be betterless ambiguous to talk about "closing the window" than "closing the application".

Thanks for the info about the About Mattermost dialog. Here again, the terminology "main menu" is confusing, because on Windows (and I guess similarly on MacOS) that generally refers to the application's native main menu bar at the top of the Window. In the context of the Mattermost desktop application, maybe a less ambiguous wording could be found to refer to the on-page Mattermost main menu — maybe "three-dots Mattemost menu". (It doesn't help that the three-dots menu has no title or tooltip that would inform the user about what that menu is called.)

**Comment by yuya-oc** [comment] 2016-08-13 02:25
By #187, "Quit" was changed to "Exit" on Windows.

**Comment by jasonblais** [comment] 2016-08-16 05:01
Thanks @nmatt for the feedback! 

As @yuya-oc mentioned above, @Razzeee helped change `Quit` to `Exit`, which is more standard with Windows applications.

Also agree that it's not clear what "main menu" is in this context. I've submitted a [pull request to update our issue template](https://github.com/mattermost/desktop/pull/244), feel free to share further feedback if you have any.

**Comment by yuya-oc** [comment] 2016-08-21 15:21
@jasonblais Should this be closed by merging #187 and #244?

**Comment by jasonblais** [comment] 2016-08-22 05:43
Thanks @yuya-oc for circling back, 

@nmatt, given `Quit` will be changed to `Exit` with the next release (thanks to #187), will this be sufficient to clarify the intended behaviour of the shortcut?

If you have further feedback, let us know. Otherwise it sounds like we'd be ready to close this issue.

By the way, thank you @nmatt for the reports you've filed recently here: they are clear, easy to reproduce and easy to understand. Much appreciated! We'd love to see you join our [Desktop community channel](https://pre-release.mattermost.com/core/channels/desktop-app) if you'd like (and already haven't). There is a lot of discussion around the desktop app with latest updates as well.

**Comment by nmatt** [comment] 2016-08-22 17:45
@jasonblais: `Exit` is certainly clear enough. My issue was more caused by the wording in the changelog: "The app now minimizes to the system tray when closed." Without qualification, "closing" an application usually means exiting, which is why I expected the minimizing for Quit/Exit as well. (There actually are applications that do exactly that, i.e. minimize to the system tray upon "Exit", and you can only really exit them from the system tray.) What was really meant in the changelog though was "closing the window", as opposed to "closing the application" (= exiting/quitting). It's a distinction that the documentation should be careful to make, so that it's unambiguous.

As far as I'm concerned, this issue can be closed, It was more caused by my misinterpreting the changelog entry, and it's great if it has raised awareness about the appropriate terminology to use.

I just joined the community channel per your suggestion. Likewise, I have to say that I am pleasantly surprised about the developer/maintainer feedback here on the issues I reported. The consideration and general courtesy is certainly above the norm for OSS projects.

**Comment by jasonblais** [comment] 2016-08-30 12:55
Thanks @nmatt, I see what you mean! 

I've updated the entry in the changelog to `The app now minimizes to the system tray when application window is closed.` Agree it should be less ambiguous and we'll be more careful in the future - your feedback is much appreciated.

And sorry for the delayed response here, I was away last week. Really glad to see you in our community channel!

**Closed by jasonblais** 2016-08-30 12:55 UTC
Labels: windows
