### ISSUE TITLE
Mattermost Desktop Relocates itself on Taskbar

### ISSUE THREAD

**Issue by nyclabels** [mattermost/desktop#1239] opened 2020-03-16 17:12 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When using Mattermost across multiple monitors, it will reset its position on the taskbar to the primary monitor.

**Environment**
- Operating System: Windows 10 x64 Pro 1903
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.16.3

**Steps to reproduce**
1) Have a Windows 10 machine with two monitors
2) Have your taskbar settings set to "Show taskbar on all displays" and "Taskbar where window is open".
3) Have Mattermost Desktop open, dragging the window to your "extended" monitor.
4) Minimize Mattermost to taskbar.
5) Click on taskbar section to re-open Mattermost.

**Expected behavior**
Mattermost's taskbar "section" stays displaying on the "extended" monitor.

**Observed behavior**
The taskbar section defaults back to the primary monitor, regardless of which monitor it is installed on.

Screenshot is attached.
![Untitled](https://user-images.githubusercontent.com/17073218/76783205-d3ce9b00-6787-11ea-8fd7-597c41fa7f8b.png)

**Comment by Stypox** [comment] 2020-03-18 14:17
This seems to be duplicate of #1225

**Comment by nyclabels** [comment] 2020-03-18 15:22
Upon further research, it actually appears to be a duplicate of #1209. My
apologies for the duplicate issue report.

**Comment by amyblais** [comment] 2020-03-25 13:40
I'll close this as a duplicate,

**Closed by amyblais** 2020-03-25 13:40 UTC
