### ISSUE TITLE
5.2.0 App require add server url and name after update (msi/gpo) - Windows

### ISSUE THREAD

**Issue by krzaq90** [mattermost/desktop#2348] opened 2022-11-03 08:07 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost client app after update to 5.2.0 require to add a Mattermost server when the server has been added before update. 

**Environment**
- Operating System: Windows 10 / Windows 11
- Mattermost Desktop App version: 5.2.0
- Mattermost Server version: 5.37.1 

**Steps to reproduce**
1. Install older Mattermost client using msi installer, 
2. Configure GPO to add server url and name automaticaly,
3. Update GPO on client computer
4. Update Mattermost client to 5.2.0 using msi installer by GPO
5. After update please run the client app, the app will require to add a Mattermost server url and name. You cannot postpone it, you cannot switch to the existing server in the Mattermost app.
 
**Expected behavior**
If a Mattermsot server has been added before do not show welcome screen „Add a Mattermost server”

**Comment by devinbinnie** [comment] 2022-11-03 13:38
Closed as a dupe of #2335.

**Closed by devinbinnie** 2022-11-03 13:38 UTC
Labels: Duplicate
