### ISSUE TITLE
.deb package missing for 1.3.0

### ISSUE THREAD

**Issue by phaidros7** [mattermost/desktop#259] opened 2016-08-22 10:22 UTC
#### Summary

there are only tarballs available for linux for the latest release (1.3.0)

#### Steps to reproduce

https://github.com/mattermost/desktop/releases

no url for mattermost-desktop-1.3.0-linux-x64.deb

**Comment by jasonblais** [comment] 2016-09-01 21:39
Very sorry for my late reply here @phaidros7 , was away last week and have been catching up. 

I posted a note previously in our [desktop app community channel](https://pre-release.mattermost.com/core/channels/desktop-app), which everyone is welcome to join, or we can continue discussion in this thread. 

For Mattermost Desktop 1.3, we moved to an automated build process with code-signing for Windows and Mac OS X, along with a list of other improvements. They are now considered release-quality apps for Mattermost. Linux .tar packages are considered Beta.

This change has built trust, which sets additional expectations for the desktop apps that we should both embrace and respect. 

The automated build process for the Mattermost server doesn't include .deb packages, as there isn't an easy way for the Mattermost team to troubleshoot issues and in general fix problems that affects the usability of the product. 

A similar situation applies for the desktop app. There was a long and thoughtful discussion on which packages we should include in the automated build process for desktop apps, and we have decided to not include the .deb packages for now, due to the reasons outlined above.

That being said, if the Debian community is ready to fix issues, test prior to releases and build the binaries themselves, we would gladly include unofficial .deb packages with the release tag. The effort would be community-driven, but would result in a much better outcome.

If there is interest, please let us know and we'd be happy to work through the process together to have unofficial .deb packages for v1.4 and beyond.

**Comment by thanosk** [comment] 2016-09-07 09:04
I've also posted my comment in the [desktop app community channel](https://pre-release.mattermost.com/core/channels/desktop-app). 

In few simple words, this is just unfair to the open-source community upon which you capitalized all the "love" you could get in order to rival Slack.

In the end, it's not too time-consuming to undertake the management of a mattermost-owned .deb repository or an unofficial ppa repo, in order to include all possible gpg signatures you'd wish.

**Comment by jasonblais** [comment] 2016-09-07 21:10
Thanks @thanos for the feedback, much appreciated!

I've discussed with our team members based on your notes to reconsider having debian packages in the build.

Since v1.3 saw an official release of the windows and mac desktop apps, we wanted to be careful about setting expectations on the Linux distributions. This was also the first time Mattermost created the automated build process, which didn't have the .deb packages by default. As we don't have an easy way to reproduce critical issues on Debian, we felt uncomfortable adding .deb packages for v1.3.

This was not intended to be against or that we'd ignore the Debian open-source community, quite the opposite. We wanted to ensure that if we were to add them to our automated build process, what we provide can be trusted.

However, after discussing with Mattermost team members and re-evaluating the decision, we'd be happy to consider adding .deb for v1.4 as "Beta", given the interest towards it from the community. 

If anyone would like to run other Linux distributions, they would need the community's help to take the management of the builds as our team is not very familiar with those packages. 

Would anyone have further thoughts? We really appreciate the feedback so far and want to build something that is beneficial for the community while can be trusted by those who use it.

**Comment by St-Ex** [comment] 2016-09-16 10:57
Hi,
I'm highly interested with .deb release. We (15 devs) are using Mattermost desktop on Mint 17/18 since may. Using .deb package is really helpful to push a new version on everyone computer.

**Comment by jasonblais** [comment] 2016-09-16 12:27
Thanks again everyone!

I've been talking to our devs and here is a proposal:

1. We will look into adding the .deb packages to the build for 3.4 release, and include them as 'unofficial' release packages.
2. However, in order for us to be comfortable doing that, we would need the community's help 

 a. testing the packages each release, including future release candidates
 b. taking responsibility for fixing critical issues, whether for 3.4 or for future releases
 c. testing each PR applicable for .deb before merged to the `desktop` repo

as we don't have the resources to do 2a-2c on our end.

@thanosk @phaidros7 @St-Ex and others, how would you feel about the above proposal?

**Comment by St-Ex** [comment] 2016-09-16 12:29
I'm OK with that. I'll be glad to help test and improve the linux part.

**Comment by jnugh** [comment] 2016-09-17 13:32
I will help out for sure ;)

**Comment by abij** [comment] 2016-09-23 12:21
Hi Guys,

We are trying to install Linux Desktop Client on RH6. 

Yum install works, but it cannot run on RedHat 6, because RH6 uses libstdc++.so.6.0.13.
If you start the Mattermost app it will complain that: GLIBCXX_3.4.15 is not available.
We have researched a bit. Looks like RH7 uses newer gcc-compiler which uses the newer  libstdc++.so.6.0.19.

The 'electron-packager' is used to create Linux distribution. Is it possible to create a distribution for RH6?

**Comment by jasonblais** [comment] 2016-09-23 13:16
Thanks @abij! We would probably need the community's help managing the distribution for RH6, would there be any interest in doing so?

@thanosk mentioned above that there would be the possibility of managing an unofficial ppa repo, in order to include all possible gpg signatures. Not sure if that's an option?

**Comment by jasonblais** [comment] 2016-09-23 13:17
@St-Ex @jnugh @phaidros7 @thanosk and others, here are .deb packages generated by CircleCI - we'd like to have at least two members testing the packages to ensure there are no critical errors.

Once you've tested it, please reply back to this thread with a report of issues you have found (if any) and we'll add them to the 3.4 build and the corresponding [release tag](https://github.com/mattermost/desktop/releases/tag/v3.4.0) as unofficial builds if nothing critical is found:
 - [...-linux-amd64.deb](https://703-43964563-gh.circle-artifacts.com/0//tmp/circle-artifacts.xJlTrfO/mattermost-3.4.0.deb)
 - [...-linux-i386.deb](https://703-43964563-gh.circle-artifacts.com/0//tmp/circle-artifacts.xJlTrfO/mattermost-3.4.0-ia32.deb)

Thank you everyone for your feedback these past weeks!

**Comment by thanosk** [comment] 2016-09-23 15:12
@jasonblais I'm testing the amd64 deb on my Ubuntu 16.04 workstation and so far no issues found. Thanks for sharing.

Considering hosting a (Canonical/Ubuntu/Launchpad) PPA, technically it needs some considerable changes around the mattermost-desktop project building mechanism (aka writing deb source rules), which IMHO are not worth our time. 

Instead, I would suggest building as is (using electron's mechanisms), which is perfectly fine, and then host the debs on a simple repository tool like [aptly](https://www.aptly.info/) or keep distributing these packages via GitHub, both options are OK.

However, all above options are for Debian and Debian-derivative Linux distributions. RedHat cannot take advantage of PPAs or aptly.

**Comment by St-Ex** [comment] 2016-09-24 08:54
Installed on my personal machine.No issue for now on.

I'll deploy it at work on Monday with coworkers.

**Comment by jasonblais** [comment] 2016-09-27 17:29
Thanks @thanosk and @St-Ex! Unofficial .deb packages added to release tag: https://github.com/mattermost/desktop/releases/tag/v3.4.0

We'll look at alternate options for next release, but will likely continue sharing them via GitHub for now.

**Closed by jasonblais** 2016-09-27 17:29 UTC
