### ISSUE TITLE
Ctrl, Shift or Alt + Click on a channel

### ISSUE THREAD

**Issue by CometKim** [mattermost/desktop#406] opened 2016-12-29 16:13 UTC
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
A child window is opened when I click on channel with holding on Crtl/Shift/Alt.
![image](https://cloud.githubusercontent.com/assets/9696352/21547752/62c60054-ce2b-11e6-8fd9-d6b69a19e0df.png)

**Steps to reproduce**
1. Just hold on pushing one key of Ctrl, Shift and Alt.
2. Click on any channel

**Expected behavior**
I'm not sure what is the expected behavior... it seems not a designed.

In a case, my customer like this behavior to show many channels in a view.
And I like to use this when I open admin console

**Observed behavior**
Channel is opened as a new child window.

As a child of child is also possible. 

Grandchild window is destroyed when its parent is destroyed.

**Comment by yuya-oc** [comment] 2016-12-31 10:45
The behavior is not by design, new windows should not appear. In this case, some functionality added by the desktop app would be lost (e.g. unread count, context menu, etc).

**Comment by jasonblais** [comment] 2016-12-31 20:21
While I agree the current behaviour isn't correct, propose we take a moment to consider what would a webapp user expect to happen if they hold any of the three keys (CTRL, SHIFT or ALT) and click on a link (whether a URL in a message or a channel on left-hand sidebar).

Similarly, what would a desktop app user on Slack, Skype or HipChat expect?

**Comment by jasonblais** [comment] 2017-01-23 04:52
After looking at the webapp experience and the experience in other desktop apps, it would make sense not to open a new window, I agree. I would just expect it to open the channel on the window itself.

There were cases (e.g. Slack) where holding down the `CTRL` key and clicking on a channel name opened a new browser tab for it, but I didn't find that obvious as it brings the user away from the desktop app.

By the way, I just tried this on the test build in #415, and holding down CTRL, SHIFT or ALT and clicking on a channel name does nothing. So I'm not sure if the issue has been resolved.

----

>In a case, my customer like this behavior to show many channels in a view. And I like to use this when I open admin console

That's something we can consider looking at in the future, which is multiple views of the desktop app. But as @yuya-oc mentions this loses some functionality like unread indicators, so it's better not to do so for now.

**Comment by jasonblais** [comment] 2017-03-22 16:42
Before we implement this --

I've heard many people would actually like to have multiple Mattermost windows open, so they can have several conversations simultaneously.

So I'm not sure if we should turn this into a "feature" where you can have multiple windows open. We'd of course need to design the user experience carefully so that it makes sense, and also fix issues where you lose functionality on the child pages.

**Comment by jasonblais** [comment] 2017-03-22 17:32
Here's a uservoice request actually: https://mattermost.uservoice.com/forums/306457-general/suggestions/17521477-open-channels-and-direct-messages-in-different-win

**Comment by jasonblais** [comment] 2017-03-29 17:11
I've moved this to `Unscheduled` milestone for now --> we're getting lots of feedback where people would like to have multiple Mattermost windows open.

So we'll want to revisit the design here and carefully evaluate what we want to do here

**Comment by jasonblais** [comment] 2017-04-30 02:50
We've been getting an increasing interest towards a Windows docking/tiling system, where you can have multiple chats open within the same app window.

The idea is similar to a [tiling window manager](https://en.wikipedia.org/wiki/Tiling_window_manager)

![image](https://cloud.githubusercontent.com/assets/13119842/25560912/0f16c49a-2d2e-11e7-8b68-ed1925ced6a7.png)


----

I've looked into it a little more and found that there used to be a dockable framework based on Electron, but it had to be closed sourced due to copyright and licensing issues: https://discuss.atom.io/t/my-dockable-framework-based-on-electron/16459

There is a second tiling system for Electron, but it's an unfinished project: https://github.com/rhysd/Tilectron

Would be curious if anyone knew of an existing framework for Electron that allowed a tiling window manager?

**Comment by yuya-oc** [comment] 2017-04-30 03:56
I wondered something like Chrome's tab system. I feel Docking panel is appropriate when there is many kind of panels. But we have only one kind.
Anyway we would need a little complex management in code. :)

**Comment by jasonblais** [comment] 2017-05-26 16:58
@yuya-oc Would this be feasible with the current framework, and if so, how much work would you estimate it would be?

We would probably only need to support four tiles at first, equal sized. We can get more fancy later.

PS: Of course, design work will also be needed, e.g. how do you switch between channels (or teams) in the panel view.

**Comment by yuya-oc** [comment] 2017-05-30 13:51
@jasonblais Does "this" mean docking tiles? or tab system?

For docking tiles:
Especially we need to change the way to layout webview. (I will do that as a prior work for #457)
Currently it assumes only one panel and is not applicable for four tiles.

For tab system:
Currently no because almost of codes assumes only one main window. I feel we need following works:

1. Expand the code base to consider multiple main windows.
2. Add drag&drop events to control tabs between windows.

**Comment by jasonblais** [comment] 2017-05-30 14:01
Thanks @yuya-oc 

I think a docking tile system would be a good start, similar to a windows tiling manager: https://en.wikipedia.org/wiki/Tiling_window_manager

It sounds like this could be feasible to look into after some of the prior work for #457

**Comment by arkayy** [comment] 2017-07-06 15:26
You can add tabs with multiple servers or teams to a single window which makes managing them much easier. This can be achieved (at least in Windows and OSX) by going to File>Settings>Add new server. Copy the team url to the new server and give it a descriptive name. Tada!
![mattermost tabs](https://user-images.githubusercontent.com/4443014/27918754-e09cb8f0-623d-11e7-8abb-25c2f87ddc34.PNG)

**Comment by jasonblais** [comment] 2017-11-05 00:50
Thanks @arkayy for participating in the discussion! Much appreciated :)

**Comment by jasonblais** [comment] 2017-11-05 00:52
@yuya-oc Server changes have been made to hide the URL on internal links. In particular, channels on the left-hand sidebar are now considered as buttons on the desktop app (you can try it out on pre-release.mattermost.com).

As a result, clicking CTRL/ALT/SHIFT and a channel on the sidebar no longer opens a new app window. Hence, closing this issue as resolved.

We can later open a new ticket for a Windows docking/tiling system, but this is beyond the scope of the original ticket.

**Closed by jasonblais** 2017-11-05 00:52 UTC
Labels: All Platforms, Bug, Needs Design
