### ISSUE TITLE
No Text Reply, Single File Attachement - Javascript Error

### ISSUE THREAD

**Issue by tonyD-2016** [mattermost/desktop#381] opened 2016-12-05 18:54 UTC
| Version | OS | Issues | Tester | Date |
| :-- | :-- | :-- | :-- | :-- |
| 3.4.1 | Windows 10 64-bit |  | [@tonyD-2016](https://github.com/tonyD-2016) | 2016-05-12 |

I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
"Add Comment" does not execute does not execute with no text, single file attachment reply

**Steps to reproduce**
1. Select any message.
2. Click  "...". Pop-up opens.
3. Select "Reply". Reply sidebar window opens.
4. Leave Add a comment box empty. Attache a single file.
5. Click "Add Comment".
6.  ERROR: DEVELOPER MODE: A javascript error has occured. Please use the javascript console to capture and report the error (row: 15 col: 6684).

**Expected behavior**
1. File is attached to the comment.
2. Comment is added to the board. 

**Observed behavior**
1. App does not attach the single file.
2. Error Message appears below the menu.

**Possible fixes**

**Screen Capture of Issue**

![no text single file attachement](https://cloud.githubusercontent.com/assets/24369162/20897813/e323b7c0-baf1-11e6-8fdf-4f89062331b7.PNG)

**Comment by jnugh** [comment] 2016-12-06 18:43
This looks as it has happened inside the webview... It might be a platform issue.
However I was not able to reproduce this on pre-release (using browser OR desktop app).
Does this happen if you try it again?

**Comment by jasonblais** [comment] 2016-12-06 18:52
Thanks @tonyD-2016 for the report and for @jnugh for following up.

Looks like this was fixed by the platform team earlier today, so I'll close this issue as resolved.

Thanks! :)

**Closed** 2016-12-07 04:37 UTC
Labels: bug, server side
